Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -2209,7 +2209,6 @@ runs: # Uses default x86_64 / linux user machine
         github="${GITHUB_WORKSPACE}";
         repository=$(echo ${{ github.repository }} | cut -d'/' -f 2-);
         error_log="${github}/${{ env.filename }}_error.log";
-        version="clang-${{ inputs.version }}";
         checked=false; include_count=1; missing_count=1
         countX=0; count1=0; count2=0; error=0; error1=0; error2=0;
         process_input() {
@@ -2264,21 +2263,13 @@ runs: # Uses default x86_64 / linux user machine
           fi;
         fi;
         if [[ "${file_type}" == [cth]* ]] && [[ -n "${files}" ]]; then
-          if ${{ env.dirname != '' }}; then
-            echo -e "\n####################\nWorkspace Folder: ${{ env.dirname }}\n####################" | process_input;
-          else
-            echo -e "\n####################\nWorkspace Folder: ${repository}\n####################" | process_input;
-          fi;
+          ${{ env.dirname != '' }} && echo -e "\n####################\nWorkspace Folder: ${{ env.dirname }}\n####################" | process_input || echo -e "\n####################\nWorkspace Folder: ${repository}\n####################" | process_input;
           if [[ -f "${clang_file}" ]] && ${{ inputs.repair == 'true' }}; then
             echo -e '\n####################\n\t.clang-tidy found continuing...\n####################' | process_input;
           elif [[ ! -f "${clang_file}" ]] && ${{ inputs.repair == 'true' }}; then
             echo -e "\n####################\n::error:: .clang-tidy not found exiting...\n####################" | process_input;
           fi;
-          if [[ -f "${compile_json}" ]]; then
-            echo -e '\n####################\n\tA compile_commands.json was found continuing...\n####################' | process_input;
-          elif [[ ! -f "${compile_json}" ]]; then
-            echo -e '\n####################\n\tA compile_commands.json was not found\nSet option ( project: true ) to create one if needed, continuing....\n####################' | process_input;
-          fi;
+          [[ -f "${compile_json}" ]] && echo -e '\n####################\n\tA compile_commands.json was found continuing...\n####################' | process_input || echo -e '\n####################\n\tA compile_commands.json was not found\nSet option ( project: true ) to create one if needed, continuing....\n####################' | process_input;
           if [[ -f "${cppchecks}" ]]; then
              echo -e "\n####################\n\t${cppchecks} config file was found continuing...\n####################" | process_input;
              cppchecks="$(cat ${cppchecks} | tr -d ' \n')";
