Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -95,7 +95,8 @@ inputs:
     options:
     - 1 # Locate all includes in sources and display all content found about files.
     - 2 # Locate all includes in sources and display more content found about files.
-    - 3 # Locate all includes in sources and display less content found about files. 
+    - 3 # Locate all includes in sources and display less content found about files.
+    - 4 # Locate all needed includes in sources and display all using gcc.
   number:
     description: 'Number of files to check before stopping action'
     type: number
@@ -651,15 +652,16 @@ runs:
           done;
         }
         echo -e "####################\n\t\033[33mPROGRESSIVE SCAN MODE\033[0m\n####################" | process_input;
-        include_files1=$(fdfind -p -c auto -a -e "${{ inputs.filetype }}" "${{ env.base }}" | sort);
+        include_files1=$(fdfind -p -c auto -a -e "${{ inputs.filetype }}" "${{ env.base }}" | awk -F'/' '{print $NF, $0}' | sort -k1,1 | cut -d' ' -f2-);
         include_files2=$(find "${{ env.base }}" -type f -name "*.${{ inputs.filetype }}" -print | LC_ALL=C xargs -r grep -HEo '^#include[[:space:]]+[<"].*[>"]' | tr -d '<">' | awk '{ print $NF, $0 }' | sort -k1,1 -us | cut -d' ' -f2-);
         include_files3=$(find "${{ env.base }}" -type f -name "*.${{ inputs.filetype }}" -print | LC_ALL=C xargs -r grep -sEo '^#include[[:space:]]+[<"].*[>"]' | awk '{print $2}' | tr -d '<">' | sort -u);
         [[ -f "${include_list}" ]] && mv -f "${include_list}" "${include_list}.old";
         [[ -f "${include1}" ]] && rm -f "include-file*.txt";
         [[ -f "${name_count_file}" ]] && rm -f "${name_count_file}";
         [[ -f "${include_count_file}" ]] && rm -f "${include_count_file}";
-        if [[ $(echo "${{ inputs.filetype }}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]] && ${{ inputs.source == '1' }} && [[ "${include_files1}" ]]; then
+        if [[ "${{ inputs.filetype }}" == *.[c][c]*  ]] && ${{ inputs.source == '1' }} && [[ "${include_files1}" ]]; then
           declare -A processed
+          echo -e "\n\033[32mCheck-File discovered include objectives running full scan now: \033[0m\033[1mContent Display\033[0m  [\033[32m all \033[0m]" | process_input;
           echo -e "\n####################\nCheck-File Auto Fix Sources Include [ Status: \033[32mAnalzying\033[0m ]\n####################" | process_input;
           while IFS= read -r file; do
             include_count=0
@@ -669,20 +671,13 @@ runs:
             echo -e "\nAnalyzing Includes Source File ${count1}: ${file##*/}" | process_input;
             if ${{ inputs.include }}; then
               includes_found=false
-              include_source=$(awk '
-                /^[[:space:]]*#[[:space:]]*include[[:space:]]+[<"]/ {
-                split($0, parts, /[<>"]/)
-                filename = parts[2]
-                if (filename != "" && !seen[filename]++) {
-                  print filename
-                }
-              }' "${file}");
+              include_source=$(awk '/^[[:space:]]*#[[:space:]]*include[[:space:]]+[<"]/ {split($0, parts, /[<>"]/) filename = parts[2] if (filename != "" && !seen[filename]++) { print filename; }}' "${file}");
               if [[ "${include_source}" ]]; then
                 echo -e "\n\tinclude file objectives:\n\n${include_source}" | process_input;
                 while IFS= read -r include; do
-                  if ([[ "${include}" == *".h" ]] || [[ "${include}" == *".hh" ]] || [[ "${include}" == *".hpp" ]] || [[ "${include}" == *".h++" ]]) && [[ -n "${processed[$include]}" ]]; then
+                  if [[ "${include}" == *.[h][h]* ]] && [[ -n "${processed[$include]}" ]]; then
                     echo -e "\n\033[1mNotice:\033[0m\033[32mSource file include \033[0m( ${include} )\033[33m was added already!!!\033[0m [ \033[1mskipped\033[0m ]" | process_input;
-                  elif [[ "${include}" == *".h" ]] || [[ "${include}" == *".hh" ]] || [[ "${include}" == *".hpp" ]] || [[ "${include}" == *".h++" ]]; then
+                  elif [[ "${include}" == *.[h][h]* ]]; then
                     processed["$include"]=1
                     path1="${include##+(*./)}";
                     path2="${path1##[:]*}";
@@ -727,7 +722,7 @@ runs:
           if [[ -s "${include2}" ]]; then
             while IFS= read -r includes; do
               count4=$((include_dirs++));
-              if [[ "${includes}" == *".h" ]] || [[ "${includes}" == *".hh" ]] || [[ "${includes}" == *".hpp" ]] || [[ "${includes}" == *".h++" ]]; then
+              if [[ "${include}" == *.[h][h]* ]]; then
                 echo "${includes%/*}" >> "${include3}";
               else
                 echo "${includes}" >> "${include3}";
@@ -748,7 +743,7 @@ runs:
             echo -e '\n::notice::\033[31mNo include objectives discovered or check-file encountered an issue!!!\033[0m' | process_input;
           fi;
           if [[ "${count5}" > '0' ]]; then
-            echo -e "\n::notice::\033[34m⚠️ Total include source files missing during scan\033[0m\033[1m ${count5}\033[0m\n[Hint] Many source files calling the same \033[31mmissing include files.\033[0m\nSet option \033[1m( content: false )\033[0m to get a exact missing list count quickly!" | process_input;
+            echo -e "\n::notice::\033[34m⚠️ Total include source files missing during scan\033[0m\033[1m ${count5}\033[0m\n[Hint] Many source files calling the same \033[31mmissing include files.\033[0m\nSet option \033[1m( source: 3 )\033[0m to get a exact missing list count quickly!" | process_input;
           fi;
           unset processed;
           [[ -s "${include_list}" ]] && mkdir -p build && cp -vf "${include_list}" build/ | process_input;
@@ -756,7 +751,8 @@ runs:
           m=$((seconds / 60));
           s=$((seconds % 60));
           printf "Project Auto Include Runtime: %d minutes and %d seconds\n" "$m" "$s" | process_input;
-        elif [[ $(echo "${{ inputs.filetype }}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]] && ${{ inputs.source == '2' }} && [[ "${include_files2}" ]]; then
+        elif [[ "${{ inputs.filetype }}" == *.[c][c]*  ]] && ${{ inputs.source == '2' }} && [[ "${include_files2}" ]]; then
+          echo -e "\n\033[32mCheck-File discovered include objectives running full scan now: \033[0m\033[1mContent Display\033[0m  [\033[32m mid \033[0m]" | process_input;
           echo -e "\n####################\nCheck-File Auto Fix Sources Include [ Status: \033[32mAnalzying\033[0m ]\n####################" | process_input;
           while IFS= read -r file; do         
             name="${file%%:*}";
@@ -775,7 +771,7 @@ runs:
             if [[ "${include_source}" ]]; then
               includes_found=true
               echo -e "\n\tinclude source: ${include_source}" | process_input;
-              if [[ "${include_source}" == *".h" ]] || [[ "${include_source}" == *".hh" ]] || [[ "${include_source}" == *".hpp" ]] || [[ "${include_source}" == *".h++" ]]; then
+              if [[ "${include}" == *.[h][h]* ]]; then
                 path1="${include_source##+(*./)}";
                 path2="${path1##[:]*}";
                 path3="${path2%'\n'}";
@@ -820,7 +816,7 @@ runs:
           if [[ -s "${include2}" ]]; then
             while IFS= read -r includes; do
               count4=$((include_dirs++));
-              if [[ "${includes}" == *".h" ]] || [[ "${includes}" == *".hh" ]] || [[ "${includes}" == *".hpp" ]] || [[ "${includes}" == *".h++" ]]; then
+              if [[ "${include}" == *.[h][h]* ]]; then
                 echo "${includes%/*}" >> "${include3}";
               else
                 echo "${includes}" >> "${include3}";
@@ -841,17 +837,18 @@ runs:
             echo -e '\n::notice::\033[31mNo include objectives discovered or check-file encountered an issue!!!\033[0m' | process_input;
           fi;
           if [[ "${count5}" > '0' ]]; then
-            echo -e "\n::notice::\033[34m⚠️ Total include source files missing during scan\033[0m\033[1m ${count5}\033[0m\n[Hint] Many source files calling the same \033[31mmissing include files.\033[0m\nSet option \033[1m( content: false )\033[0m to get a exact missing list count quickly!" | process_input;
+            echo -e "\n::notice::\033[34m⚠️ Total include source files missing during scan\033[0m\033[1m ${count5}\033[0m\n[Hint] Many source files calling the same \033[31mmissing include files.\033[0m\nSet option \033[1m( source: 3 )\033[0m to get a exact missing list count quickly!" | process_input;
           fi;
           [[ -s "${include_list}" ]] && mkdir -p build && cp -vf "${include_list}" build/ | process_input;
           seconds=$((SECONDS - start_time));
           m=$((seconds / 60));
           s=$((seconds % 60));
           printf "Project Auto Include Runtime: %d minutes and %d seconds\n" "$m" "$s" | process_input;
-        elif [[ $(echo "${{ inputs.filetype }}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]] && ${{ inputs.source == '3' }} && [[ "${include_files3}" ]]; then
+        elif [[ "${{ inputs.filetype }}" == *.[c][c]*  ]] && ${{ inputs.source == '3' }} && [[ "${include_files3}" ]]; then
           echo -e "\n\033[32mCheck-File discovered include objectives running full scan now: \033[0m\033[1mContent Display\033[0m  [\033[32m low \033[0m]" | process_input;
+          echo -e "\n####################\nCheck-File Auto Fix Sources Include [ Status: \033[32mAnalzying\033[0m ]\n####################" | process_input;
           while IFS= read -r include; do
-            if [[ "${include}" == *".h" ]] || [[ "${include}" == *".hh" ]] || [[ "${include}" == *".hpp" ]] || [[ "${include}" == *".h++" ]]; then
+            if [[ "${include}" == *.[h][h]* ]]; then
               path1="${include##+(*./)}";
               path2="${path1##[:]*}";
               path3="${path2%'\n'}";
@@ -886,7 +883,7 @@ runs:
           if [[ -s "${include2}" ]]; then
             while IFS= read -r includes; do
               count4=$((include_dirs++));
-              if [[ "${includes}" == *".h" ]] || [[ "${includes}" == *".hh" ]] || [[ "${includes}" == *".hpp" ]] || [[ "${includes}" == *".h++" ]]; then
+              if [[ "${include}" == *.[h][h]* ]]; then
                 echo "${includes%/*}" >> "${include3}";
               else
                 echo "${includes}" >> "${include3}";
@@ -909,6 +906,14 @@ runs:
             echo -e "\n::warning::\033[34m⚠️ Total include source files missing during scan:\033[0m\033[31m ${count5}\033[0m\n[Hint] Many source files might be calling these same \033[31mmissing include files!\033[0m" | process_input;
           fi;
           [[ -s "${include_list}" ]] && mkdir -p build && cp -vf "${include_list}" build/ | process_input;
+          seconds=$((SECONDS - start_time));
+          m=$((seconds / 60));
+          s=$((seconds % 60));
+          printf "Project Auto Include Runtime:\033[1m %d minutes and %d seconds\033[0m\n" "$m" "$s" | process_input;
+        elif [[ "${{ inputs.filetype }}" == *.[c][c]*  ]] && ${{ inputs.source == '4' }} && [[ "$(which gcc)" ]]; then
+          echo -e "\n\033[32mCheck-File gcc include objectives running full scan now: \033[0m\033[1mContent Display\033[0m  [\033[32m all \033[0m]" | process_input;
+          echo -e "\n####################\nCheck-File Auto Fix Sources Include [ Status: \033[32mAnalzying\033[0m ]\n####################" | process_input;
+          gcc -M init/main.c | process_input;
           seconds=$((SECONDS - start_time));
           m=$((seconds / 60));
           s=$((seconds % 60));
@@ -1045,7 +1050,7 @@ runs:
               file_count='500';
               echo "include_source=false" >> "${GITHUB_ENV}";
             fi;            
-            if ${{ inputs.source > '0' }} && [[ -s "${clang_sources}" ]] && ${{ inputs.include }}; then
+            if [[ -s "${clang_sources}" ]] && ${{ inputs.include }}; then
               if [[ "${file_count}" < '2000' ]]; then
                 while IFS= read -r include; do
                   include_source_count=$((include_source_count + 1));      
@@ -1091,23 +1096,23 @@ runs:
           }
           mkdir -p build/fixes
           echo 'build_error=false' >> "${GITHUB_ENV}";
-          echo "github_source_dirs=$(source_dirs)" >> "${GITHUB_ENV}";
-          echo "github_source_files=false" >> "${GITHUB_ENV}";
+          echo 'github_source_files=false' >> "${GITHUB_ENV}";
           echo 'github_include_dirs=false' >> "${GITHUB_ENV}";
+          echo 'github_source_dirs=false' >> "${GITHUB_ENV}";
           if [[ "$(source_files)" ]]; then
-            echo "github_source_files=true" >> "${GITHUB_ENV}";
+            echo 'github_source_files=true' >> "${GITHUB_ENV}";
           fi;
           if [[ "$(cmake_includes)" ]]; then
             echo "github_include_dirs=$(cmake_includes)" >> "${GITHUB_ENV}";
-            if ${{ env.include_count > '2000' }}; then
-              echo -e "\n####################\n\tcheck-file added \033[1m${{ env.include_count }}\033[0m source include directories [source:\033[32m auto mode\033[0m]\n\tcmake max additional header objectives updated successfully!\n####################" | process_input;
-            elif [[ -f "${count3}" ]]; then
+           if [[ -f "${count3}" ]]; then
               echo -e "\n####################\n\tcheck-file added \033[1m$(cat ${count3})\033[0m source include directories [source:\033[32m auto mode\033[0m]\n\tcmake additional header objectives updated successfully!\n####################" | process_input;
             elif [[ -f "${count2}" ]]; then
               echo -e "\n####################\n\tcheck-file added $(cat ${count1}) header include directories\n\tcheck-file updated $(cat ${count2}) additional header directories\n####################" | process_input;
             else
               echo -e "\n####################\n\tcheck-file added $(cat ${count1}) header include directories\n####################" | process_input;
             fi;
+          elif ${{ env.include_count > '2000' }}; then
+              echo -e "\n####################\n\tcheck-file added \033[1m${{ env.include_count }}\033[0m source include directories [source:\033[32m auto mode\033[0m]\n\tcmake max additional header objectives updated successfully!\n####################" | process_input;
           fi;
           if [[ -f "${clang_tidy}" ]]; then
             echo -e '\n####################\n\t.clang-tidy found continuing...\n####################' | process_input;
@@ -1117,10 +1122,11 @@ runs:
           fi;
           if [[ -d 'build' ]]; then
             echo -e '\n####################\n\tbuild directory created continuing...\n####################\n' | process_input;
-            if [[ "$(source_dirs)" ]] && [[ "$(cmake_includes)" ]] && [[ ! -f "${compile_json}" ]]; then
-              cmake -S . -DPROJECT_INCLUDE_DIRS="$(cmake_includes)" -DPROJECT_SRC_DIRS="$(source_dirs)" -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
+            if ([[ "$(source_dirs)" ]] || [[ "$(cmake_includes)" ]]) && [[ ! -f "${compile_json}" ]]; then
+              echo "github_source_dirs=$(source_dirs)" >> "${GITHUB_ENV}";
+              cmake -S . -DPROJECT_INCLUDE_DIRS="$(cmake_includes)" -DPROJECT_SRC_DIRS="$(source_dirs)" -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning::( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
             elif [[ ! -f "${compile_json}" ]]; then
-              cmake -S . -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
+              cmake -S . -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning::( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
             fi;
             if [[ "${PIPESTATUS[0]}" == '0' ]]; then
               if ${{ inputs.upload }}; then
