Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -2004,12 +2004,12 @@ runs:
                 elif ${{ inputs.stored == 'true' }} && ${{ env.update == 'true' }}; then
                   echo -e "\n\n####################\nGCC/G++ FILES ANALYZER: ( ${count1} )\n####################\n" | process_input;
                   if [[ "${file_type}" == [c] ]]; then
-                    gcc -M -MG "${file}" | process_input || echo -e "::notice gcc:: ( exit $? )" | process_input;
+                    gcc -M -MG "${file}" | process_input || echo -e "::notice::gcc ( exit $? )" | process_input;
                   elif [[ "${file_type}" == [c]* ]]; then
-                    g++ -M -MG "${file}" | process_input || echo -e "::notice g++:: ( exit $? )" | process_input;
+                    g++ -M -MG "${file}" | process_input || echo -e "::notice::g++ ( exit $? )" | process_input;
                   fi;
                   echo -e "\n\n####################\nCLANG-TIDY FIX FILES ANALYZER: ( ${count1} )\n####################\n" | process_input;
-                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>&1 | process_input || echo -e "::notice clang-tidy:: ( exit $? )" | process_input;
+                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>&1 | process_input || echo -e "::notice::clang-tidy ( exit $? )" | process_input;
                   if [[ -s "${error_log}" ]] && [[ ! $(grep -sE "${file}.*error:" "${error_log}") ]]; then
                     echo -e "\n####################\nSTORING NO ERRORS FOUND: ${file##*/}\n####################" | process_input;
                   else
@@ -2021,11 +2021,11 @@ runs:
                 elif ${{ inputs.stored == 'false' }} || ${{ env.update == 'false' }}; then
                   echo -e "\n\n####################\nCLANG-TIDY FILES ANALYZER: ( ${count1} )\n####################\n" | process_input;
                   if [[ "${file_type}" == [c] ]]; then
-                    gcc -MM "${file}" | process_input || echo -e "::notice:: ( exit $? ) gcc" | process_input;
+                    gcc -MM "${file}" | process_input || echo -e "::notice::gcc ( exit $? )" | process_input;
                   elif [[ "${file_type}" == [c]* ]]; then
-                    g++ -MM "${file}" | process_input || echo -e "::notice:: ( exit $? ) g++" | process_input;
+                    g++ -MM "${file}" | process_input || echo -e "::notice::g++ ( exit $? )" | process_input;
                   fi;
-                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>&1 | process_input || echo -e "::notice clang-tidy:: ( exit $? )" | process_input;
+                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>&1 | process_input || echo -e "::notice::clang-tidy ( exit $? )" | process_input;
                   if [[ -s "${error_log}" ]] && [[ ! $(grep -sE "${file}.*error:" "${error_log}") ]]; then
                     echo -e "\n####################\nCHECK-FILE NO ERRORS FOUND: ${file##*/}\n####################" | process_input;
                   else
@@ -2037,9 +2037,9 @@ runs:
               else
                 echo -e "\n####################\nCPPCHECK INCLUDE FILE(S) ANALYZER: ( ${count1} )\n####################\n" | process_input;
                 if [[ "${compile_json}" ]]; then
-                  cppcheck -j "$(nproc)" -l 2 --verbose --force --enable="${cppchecks}" --report-progress --suppress=* --suppress=checkersReport --cppcheck-build-dir="${build_dir}" --project="${compile_json}" --file-filter="${file}" --exitcode-suppressions="${file##*/}" 2>&1 | process_input || echo -e "::notice cppcheck:: ( exit $? )" | process_input;
+                  cppcheck -j "$(nproc)" -l 2 --verbose --force --enable="${cppchecks}" --report-progress --suppress=* --suppress=checkersReport --cppcheck-build-dir="${build_dir}" --project="${compile_json}" --file-filter="${file}" --exitcode-suppressions="${file##*/}" 2>&1 | process_input || echo -e "::notice::cppcheck ( exit $? )" | process_input;
                 else
-                  cppcheck -j "$(nproc)" -l 2 --verbose --force --enable="${cppchecks}" --report-progress --suppress=* --suppress=checkersReport --cppcheck-build-dir="${build_dir}" "${file}" -I"${include_path}" --exitcode-suppressions="${file##*/}" 2>&1 | process_input || echo -e "::notice cppcheck:: ( exit $? )" | process_input;
+                  cppcheck -j "$(nproc)" -l 2 --verbose --force --enable="${cppchecks}" --report-progress --suppress=* --suppress=checkersReport --cppcheck-build-dir="${build_dir}" "${file}" -I"${include_path}" --exitcode-suppressions="${file##*/}" 2>&1 | process_input || echo -e "::notice::cppcheck ( exit $? )" | process_input;
                 fi;
                 if [[ -s "${error_log}" ]] && [[ ! $(grep -sE "${file}.*error:" "${error_log}") ]]; then
                   echo -e "\n####################\nCHECK-FILE NO ERRORS FOUND: ${file##*/}\n####################" | process_input;
@@ -2055,7 +2055,7 @@ runs:
                   echo -e "\n####################\nChecked on ${check_date}\n\033[32mSkipping:\033[0m ${file}\n####################" | process_input;
                 elif ${{ inputs.stored == 'true' }} && ${{ env.update == 'true' }}; then
                   echo -e "\n\n####################\nCLANG-TIDY FILES ANALYZER: ( ${count1} )\n####################\n" | process_input;
-                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>&1 | process_input || echo -e "::notice clang-tidy:: ( exit $? )" | process_input;
+                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>&1 | process_input || echo -e "::notice::clang-tidy ( exit $? )" | process_input;
                   if [[ -s "${error_log}" ]] && [[ ! $(grep -sE "${file}.*error:" "${error_log}") ]]; then
                     echo -e "\n####################\nSTORING NO ERRORS FOUND: ${file##*/}\n####################" | process_input;
                   else
@@ -2066,7 +2066,7 @@ runs:
                   fixed=true
                 elif ${{ inputs.stored == 'false' }} || ${{ env.update == 'false' }}; then
                   echo -e "\n\n####################\nCLANG-TIDY FILES ANALYZER: ( ${count1} )\n####################\n" | process_input;
-                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>&1 | process_input || echo -e "::notice clang-tidy:: ( exit $? )" | process_input;
+                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>&1 | process_input || echo -e "::notice::clang-tidy ( exit $? )" | process_input;
                   if [[ -s "${error_log}" ]] && [[ ! $(grep -sE "${file}.*error:" "${error_log}") ]]; then
                     echo -e "\n####################\nCHECK-FILE NO ERRORS FOUND: ${file##*/}\n####################" | process_input;
                   else
@@ -2077,7 +2077,7 @@ runs:
                 fi;
               else
                 echo -e "\n\n####################\nCPPCHECK FILE ANALYZER: ( ${count1} )\n####################\n" | process_input;
-                cppcheck -j "$(nproc)" -l 2 --clang --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress="*" --cppcheck-build-dir="${build_dir}" "${file}" --exitcode-suppressions="${file##*/}" 2>&1 | process_input || echo -e "::notice cppcheck:: ( exit $? )" | process_input;
+                cppcheck -j "$(nproc)" -l 2 --clang --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress="*" --cppcheck-build-dir="${build_dir}" "${file}" --exitcode-suppressions="${file##*/}" 2>&1 | process_input || echo -e "::notice::cppcheck ( exit $? )" | process_input;
                 if [[ -s "${error_log}" ]] && [[ ! $(grep -sE "${file}.*error:" "${error_log}") ]]; then
                   echo -e "\n####################\nCHECK-FILE NO ERRORS FOUND: ${file##*/}\n####################" | process_input;
                 else
@@ -2087,12 +2087,12 @@ runs:
               fi;
             fi;
             if ${{ inputs.recheck == 'true' }} && ${{ inputs.repair == 'true' }}; then
-              echo -e "\n\n####################\nCPPCHECK RE-ANALYZING FILE(S) (${count1})\n####################\n" | process_input;
-              cppcheck -j "$(nproc --all)" --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress=* --quiet "${file}" 2>&1 | process_input || echo -e "::notice cppcheck:: ( exit $? )" | process_input;
+              echo -e "\n\n####################\nCPPCHECK RE-ANALYZING FILE ( ${count1} )\n####################\n" | process_input;
+              cppcheck -j "$(nproc --all)" --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress=* --quiet "${file}" 2>&1 | process_input || echo -e "::notice::cppcheck ( exit $? )" | process_input;
               if [[ -s "${error_log}" ]] && [[ ! $(grep -sE "${file}.*error:" "${error_log}") ]]; then
-                echo -e "\n####################\nRECHECK-FILE NO ERRORS FOUND ${file##*/}\n####################" | process_input;
+                echo -e "\n####################\nRECHECK-FILE NO ERRORS FOUND: ${file##*/}\n####################" | process_input;
               else
-                echo -e "\n####################\nRECHECK-FILE FOUND ERROR(S) TO REPAIR\n####################" | process_input;
+                echo -e "\n####################\nRECHECK-FILE FOUND ERRORS TO REPAIR\n####################" | process_input;
                 errors=true
               fi;
             fi;
@@ -2193,15 +2193,15 @@ runs:
               fi;
             fi;
             if ${{ inputs.repair == 'true' }}; then
-              echo -e "\n####################\nSHELLCHECK REPAIR ${file##*/} ERRORS ( ${count3} )\n####################" | process_input;
+              echo -e "\n####################\nSHELLCHECK REPAIR ${file##*/} ERRORS: ( ${count3} )\n####################" | process_input;
               if ${{ inputs.stored == 'true' }} && ${{ inputs.update == 'true' }} && [[ $(grep -sF "${search_path}" "${repaired}") ]]; then
                 echo -e "\n####################\nSTORED NOTHING TO REPAIR\n####################" | process_input;
                 echo -e "\n####################\nRepaired on ${check_date}\nSkipping ${file##*/}\n####################" | process_input;
               elif ${{ inputs.stored == 'true' }} && ${{ inputs.update == 'true' }}; then
-                echo -e "\n\n####################\nSHELLHARDEN ANALYZING ${file##*/} FOR ERRORS ( ${count3} )\n####################\n" | process_input;
+                echo -e "\n\n####################\nSHELLHARDEN ANALYZING ${file##*/} FOR ERRORS: ( ${count3} )\n####################\n" | process_input;
                 shellharden --syntax-suggest --transform "${file}" 2>&1 | process_input || echo -e "::notice shellharden:: ( exit $? )" | process_input;
-                if [[ -s "${error_log}" ]] && [[ ! $(sed -n "/${file}/,/(error):/p" "${error_log}") ]]; then
-                  echo -e "\n####################\nSTORING NO ERRORS FOUND\n####################\n\n${file}" | process_input;
+                if [[ -s "${error_log}" ]] && [[ ! $(sed -n "\|${file##*/}|,/error/p" "${error_log}") ]]; then
+                  echo -e "\n####################\nSTORING NO ERRORS FOUND: ${file}\n####################" | process_input;
                 else
                   echo -e "\n####################\nSTORING FOUND ERRORS TO REPAIR\n####################" | process_input;
                   errors=true
@@ -2209,10 +2209,10 @@ runs:
                 echo "${file} $(date)" >> "${repaired}";
                 fixed=true
               elif ${{ inputs.stored == 'false' }} || ${{ inputs.update == 'false' }}; then
-                echo -e "\n####################\nSHELLHARDEN ANALYZING ${file##*/} FOR ERRORS ( ${count3} )\n####################\n" | process_input;
-                shellharden --syntax-suggest --transform "${file}" 2>&1 | process_input || echo -e "::notice shellharden:: ( exit $? )" | process_input;
-                if [[ -s "${error_log}" ]] && [[ ! $(sed -n "/${file}/,/(error):/p" "${error_log}") ]]; then
-                  echo -e "\n####################\nSHELLHARDEN NO ERRORS FOUND ${file}\n####################" | process_input;
+                echo -e "\n####################\nSHELLHARDEN ANALYZING ${file##*/} FOR ERRORS: ( ${count3} )\n####################\n" | process_input;
+                shellharden --syntax-suggest --transform "${file}" 2>&1 | process_input || echo -e "::notice::shellharden ( exit $? )" | process_input;
+                if [[ -s "${error_log}" ]] && [[ ! $(sed -n "\|${file##*/}|,/error/p" "${error_log}") ]]; then
+                  echo -e "\n####################\nSHELLHARDEN NO ERRORS FOUND: ${file}\n####################" | process_input;
                 else
                   echo -e "\n####################\nSHELLHARDEN FOUND ERRORS TO REPAIR\n####################" | process_input;
                   errors=true
@@ -2220,20 +2220,20 @@ runs:
                 fixed=true
               fi;
             else
-              echo -e "\n####################\nSHELLCHECK ANALYZING ${file##*/} FOR ERRORS ( ${count3} )\n####################\n" | process_input;
-              shellcheck --norc --severity=warning --color=always "${file}" 2>&1 | process_input || echo -e "::notice shellcheck:: ( exit $? )" | process_input;
-              if [[ -s "${error_log}" ]] && [[ ! $(sed -n "/${file}/,/(error):/p" "${error_log}") ]]; then
-                echo -e "\n####################\nSHELLCHECK NO ERRORS FOUND ${file}\n####################" | process_input;
+              echo -e "\n####################\nSHELLCHECK ANALYZING ${file##*/} FOR ERRORS: ( ${count3} )\n####################\n" | process_input;
+              shellcheck --norc --severity=warning --color=always "${file}" 2>&1 | process_input || echo -e "::notice::shellcheck ( exit $? )" | process_input;
+              if [[ -s "${error_log}" ]] && [[ ! $(sed -n "\|${file##*/}|,/warning/p" "${error_log}") ]]; then
+                echo -e "\n####################\nSHELLCHECK NO ERRORS FOUND: ${file}\n####################" | process_input;
               else
                 echo -e "\n####################\nSHELLCHECK FOUND ERRORS\n####################" | process_input;
                 errors=true
               fi;
             fi;
             if ${{ inputs.recheck == 'true' }}; then
-              echo -e "\n####################\nSHELLCHECK ANALYZING ${file##*/} FOR ERRORS ( ${count3} )\n####################" | process_input;
-              shellcheck --norc --severity=warning --color=always "${file}" 2>&1 | process_input || echo -e "::notice shellcheck:: ( exit $? )" | process_input;
-              if [[ -s "${error_log}" ]] && [[ ! $(sed -n "/${file}/,/(error):/p" "${error_log}") ]]; then
-                echo -e "\n####################\nSHELLCHECK NO ERRORS FOUND ${file}\n####################" | process_input;
+              echo -e "\n####################\nSHELLCHECK ANALYZING ${file##*/} FOR ERRORS: ( ${count3} )\n####################" | process_input;
+              shellcheck --norc --severity=warning --color=always "${file}" 2>&1 | process_input || echo -e "::notice::shellcheck ( exit $? )" | process_input;
+              if [[ -s "${error_log}" ]] && [[ ! $(sed -n "\|${file##*/}|,/warning/p" "${error_log}") ]]; then
+                echo -e "\n####################\nSHELLCHECK NO ERRORS FOUND: ${file}\n####################" | process_input;
               else
                 echo -e "\n####################\nSHELLCHECK FOUND ERRORS\n####################" | process_input;
                 errors=true
@@ -2571,6 +2571,12 @@ runs:
             count=$((file_count++));
             echo -e "\nSource File: \033[32m${file} / ${count}\033[0m\n\033[1mDirectory List:\033[0m" | process_input;
             ls -ShApX "${file%/*}" | gawk '{ printf "    %s\n", $0; }' | process_input;
+            if ${{ inputs.number > '0' }}; then
+              if [[ "${{ inputs.number }}" -eq "${count}" ]]; then
+                echo -e "\nFile checking auto stopped at: ${count} / ${file##*/}" | process_input;
+                break;
+              fi;
+            fi;
           done <<< "${check_file}";
         fi;
       shell: bash
