Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -402,10 +402,10 @@ runs:
             echo -e "\n#####################\nRepository: ${repo}\nTotal Files: ${file_total}\n#####################\n";
           fi;
           if [[ "$(file_count)" ]]; then
-            echo -e "\n#####################\nProject File Types: ${file_count##*.}\n#####################\n";
+            echo -e "\n#####################\nProject File Types: $(file_count)\n#####################\n";
           fi;
           if [[ "$(dir_files)" ]]; then
-            echo -e "\n#####################\nDirectory Files: ${dir_files##*.}\n#####################\n";
+            echo -e "\n#####################\nDirectory Files: $(dir_files)\n#####################\n";
           fi;
         fi;
         center_text "\n${text10a}" 2>/dev/null;
@@ -426,11 +426,12 @@ runs:
         export LLVM_ENABLE_THREADS=ON
         export CMAKE_EXPORT_COMPILE_COMMANDS=ON
         export LC_ALL=C
+        set -o verbose
         compiler_list=$(dpkg --list | grep compiler | tr -d 'ii');
         clang_version=$(clang --version);
-        verify_config=$(clang-tidy --verify-config 2>/dev/null);
+        verify_config=$(clang-tidy --verify-config);
         cmake_version=$(cmake --version);
-        clang_checks=$(clang-tidy --list-checks 2>/dev/null);
+        clang_checks=$(clang-tidy --list-checks);
         repository=$(echo ${{ github.repository }} | cut -d'/' -f 2-);
         project_log="${GITHUB_WORKSPACE}/${repository}_project.log";
         gcc_version=$(gcc --version);
@@ -461,7 +462,151 @@ runs:
         echo -e "\n####################\nClang-Tidy: ${verify_config}\n####################\n" | process_input;
         echo -e "\n####################\n\tCLANG OPTIONS\n${clang_checks}\n####################\n" | process_input;
         echo 'check_build=false' >> "${GITHUB_ENV}";
-
+        if ! ${{ inputs.update }}; then
+          echo 'update=false' >> "${GITHUB_ENV}";
+          update=false
+        fi;
+        if ${{ inputs.filetype != 'none' }}; then
+          file_type="${{ inputs.filetype }}";
+        fi;
+        echo "filetype=${file_type}" >> "${GITHUB_ENV}";
+        if [[ -d "${src_tree}" ]]; then
+          echo -e "\n####################\nChecking Repository ${src_tree%/*}\n####################\n" | process_input;
+          echo -e "\n####################\nChecking for ${file_type} file(s)\n####################\n" | process_input;
+          cd "${src_tree%/*}";
+          project_files=$(sudo find . -type f -name "*.${file_type}" -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null);
+          compile_json=$(sudo find . -type f -name 'compile_commands.json' -print -quit);
+          include_dirs=$(sudo find . -type d -name 'include' -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null);
+          cmake_list='CMakeLists.txt';
+          clang_file='parameter-file';
+          clang_tidy='.clang-tidy';
+          clang_run=${{ github.action_path }}/scripts/tools/run-clang-tidy.py;
+          echo "repository=${repository}" >> "${GITHUB_ENV}";
+          src_dirs() {
+            sudo find -type d -maxdepth 1 -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r dir; do
+              echo -n "${dir#./} "
+            done;
+          }
+          file_list() {
+            sudo find -type f -name "*.${file_type}" -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r file; do
+              echo -e "${file#./}"
+            done;
+          }
+          if [[ -f "${clang_tidy}" ]]; then
+            echo -e '\n####################\n\t.clang-tidy found continuing...\n####################\n' | process_input;
+          fi;
+          if [[ -f "${cmake_list}" ]]; then
+            echo -e '\n####################\n\tCMakeLists.txt found continuing...\n####################\n' | process_input;
+          fi;
+          mkdir -p build/cache
+          if [[ -d 'build' ]]; then
+            echo -e '\n####################\n\tbuild directory created continuing...\n####################\n' | process_input;
+            if [[ "$(src_dirs)" ]]; then
+              cmake -S . -DPROJECT_SRC_DIRS="$(src_dirs)" -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
+            else
+              cmake -S . -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
+            fi;
+            if [[ "${PIPESTATUS[0]}" == 0 ]]; then
+              if ${{ inputs.upload }}; then
+                echo 'build_files=1' >> "${GITHUB_ENV}";
+                cp -Rf ./build ${github}/ && echo -e '\n####################\n\tbuild directory copied continuing...\n####################\n' | process_input;
+              fi;
+            fi;
+          fi;
+          if [[ -e 'compile_commands.json' ]]; then
+            echo -e '\n####################\n\tcompile_commands.json file symlinked continuing...\n####################\n' | process_input;
+          fi;
+          if [[ -f "${clang_file}" ]] && ${{ env.analysis == 1 }}; then
+            echo ' ' >> "${clang_file}";
+            files_list=false
+            if [[ `file_list` ]]; then
+              echo -e "\n####################\n\t${file_type} file(s) found continuing...\n####################\n" | process_input;
+              file_list >> "${clang_file}";
+              files_list=true
+            else	
+              echo -e "\n::error:: No ${file_type} files found searching repository\nExiting...\n" | process_input;
+            fi;
+            echo -e "\n####################\n\t${clang_file} found continuing...\n####################\n" | process_input;
+            echo -e '\n####################\nCLANG-TIDY CONFIG CHECKED\n####################\n' | process_input;
+            if [[ "${files_list}" ]]; then
+              cp -vf "${clang_file}" 'build/cmake-source-files.txt' 2>/dev/null;
+              echo -e '\n####################\nCLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
+              { time clang-tidy @parameter-file 2>/dev/null; } 2>&1 | process_input || echo -e "::warning:: ( $? ) checking project files" | process_input;
+              if [[ "${PIPESTATUS[0]}" == 0 ]]; then
+                echo -e '\n|RUNTIME|\n' | process_input;
+                check_build=true
+                echo 'check_build=true' >> "${GITHUB_ENV}";
+              fi;
+            else
+              exit 1
+            fi;
+          elif [[ ! -e "${clang_file}" ]] && ${{ env.analysis == 1 }}; then
+            echo -e "\n####################\n\t::error:: parameter-file missing in repo Exiting...\n####################\n" | process_input;
+            exit 1
+          fi;
+          if [[ $(which run-clang-tidy.py) ]] && ${{ env.analysis == 2 }}; then
+            echo -e "\n####################\n\trun-clang-tidy.py found continuing...\n####################\n" | process_input;
+            echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
+            { time "${clang_run}" -p build -config-file "${clang_tidy}" -fix -fix-errors -export-fixes build/cache -j "$(nproc --all)" 2>/dev/null; } 2>&1 | process_input || echo -e "::warning:: ( $? ) checking project files" | process_input;
+            if [[ "${PIPESTATUS[0]}" == 0 ]]; then
+              echo -e '\n|RUNTIME|\n' | process_input;
+              check_build=true
+              echo 'check_build=true' >> "${GITHUB_ENV}";
+            fi;
+          elif [[ -e "${clang_run}" ]] && ${{ env.analysis == 2 }}; then
+            echo -e "\n####################\n\trun-clang-tidy.py found continuing...\n####################\n" | process_input;
+            sudo chmod -v 0755 "${clang_run}" 2>/dev/null | process_input;
+            echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
+            "${clang_run}" -p build -config-file "${clang_tidy}" -fix -fix-errors -export-fixes build -j "$(nproc --all)" # | process_input;
+            if [[ "${PIPESTATUS[0]}" == 0 ]]; then
+              echo -e '\n|RUNTIME|\n' | process_input;
+              check_build=true
+              echo 'check_build=true' >> "${GITHUB_ENV}";
+            fi;
+          elif [[ ! -e "${clang_run}" ]] && ${{ env.analysis == 2 }}; then
+            echo -e "\n####################\n\t::error:: run-clang-tidy.py missing in repo Exiting...\n####################\n" | process_input;
+            exit 1
+          fi;
+          if [[ -d 'build' ]] && ${{ env.analysis == 3 }}; then
+            echo -e '\n####################\n\tbuild directory created continuing...\n####################\n' | process_input;
+            { time cmake --build build; } 2>&1 | process_input || echo "::warning:: ( $? ) cmake build source corrupted or malformed CMakeList.txt (?)" | process_input;
+            if [[ "${PIPESTATUS[0]}" == 0 ]]; then
+              echo -e '\n|RUNTIME|\n' | process_input;
+              check_build=true
+              echo 'check_build=true' >> "${GITHUB_ENV}";
+            fi;
+            if ${{ inputs.upload }}; then
+              echo 'build_files=1' >> "${GITHUB_ENV}";
+              cp -Rf ./build ${github}/ && echo -e '\n####################\n\tbuild directory copied continuing...\n####################\n' | process_input;
+            fi;
+          elif [[ ! -d 'build' ]] && ${{ env.analysis == 3 }}; then
+            echo -e "\n####################\n\t::error:: build directory missing in repo Exiting...\n####################\n" | process_input;
+            exit 1
+          fi;
+          if [[ -s "${project_log}" ]] && [[ "${project_files}" ]]; then
+            echo -e "\n####################\n\t${project_log##*/} file found continuing...\n####################\n" | process_input;
+            for file in ${project_files[@]}; do
+              file_errors=$(grep -sE "${file}.*error:" "${project_log}" 2>/dev/null);
+              if [[ "${file_errors}" ]]; then
+                count=$((count++));
+              fi;
+            done;
+            if [[ "${count}" -gt 1 ]]; then
+              echo -e "\n::notice:: ${count} ${file_type} file(s) were found with errors\nCheck them for Fix-its applied in ${project_log##*/}" | process_input;
+            fi;
+          fi;
+          if [[ ${update} ]] && ${{ env.analysis == 1 }}; then
+            echo -e "\nPARAMETERS: $(rm -vf ${clang_file} 2>/dev/null)\n" | process_input;
+          fi;
+          echo -e "\n####################\n# INSTALLED COMPILERS #\n${compiler_list}\n####################\n" | process_input;
+          if [[ ${check_build} ]]; then
+            echo -e '\n####################\n\tProject Checked Exiting...\n####################\n' | process_input;
+          else
+            echo -e '\n####################\n\tProject Not Checked Exiting...\n####################\n' | process_input;
+          fi;
+        else
+          echo -e '::error:: .git directory not found?' | process_input;
+        fi;
       shell: bash
       continue-on-error: true
 
