Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -510,7 +510,7 @@ runs:
             if [[ $(which run-clang-tidy.py) ]]; then
               echo -e "\n####################\n\trun-clang-tidy.py found continuing...\n####################\n";
               echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n';
-              { time -p run-clang-tidy.py @parameter-file -p build/ -fix -checks=-*,clang-analyzer-*,readability-*,llvm-header-guard-* -header-filter=extra/clang-tidy -j "$(nproc --all)"; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
+              { time -p run-clang-tidy.py -regex ".*\.${file_type}" -p build/ -fix -j "$(nproc --all)"; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
               echo -e '\n|RUNTIME|\n';
               check_build=true
               echo 'check_build=true' >> "${GITHUB_ENV}";
@@ -518,7 +518,7 @@ runs:
               sudo chmod -v 0755 "${clang_run}" 2>/dev/null;
               echo -e "\n####################\n\trun-clang-tidy.py found continuing...\n####################\n";
               echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n';
-              { time -p "${clang_run}" @parameter-file -p build/ -fix -checks=-*,clang-analyzer-*,readability-*,llvm-header-guard-* -header-filter=extra/clang-tidy -j "$(nproc --all)"; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
+              { time -p "${clang_run}" -regex ".*\.${file_type}" -p build/ -fix -j "$(nproc --all)"; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
               echo -e '\n|RUNTIME|\n';
               check_build=true
               echo 'check_build=true' >> "${GITHUB_ENV}";
