Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -157,11 +157,16 @@ runs:
         text7="\n####################\nshellcheck dependencies Installed\n####################\n";
         text8="\n####################\ncheckmake dependencies Installed\n####################\n";
         text9="\n####################\nbatcat dependencies Installed\n####################\n";
+        codechecker="$(which codechecker)";
         file_name="${{ inputs.filename }}";
         file_type="${file_name##*.}";
         if [[ ! $(which git) ]]; then
           sudo apt-get -yq install git git-core >/dev/null && echo -e "${text0}" || echo -e '::error::No git installed for repo updates';
           [[ ! $(which git) ]] && exit 1
+        fi;
+        if [[ ! $(which python3) ]] && ${{ inputs.project }} && ${{ inputs.analysis == 2 }}; then
+          sudo apt-get -yq install python3 >/dev/null >/dev/null && echo -e "\n####################\npython3 dependencies Installed\n####################\n" || echo -e '::error::No python3 installed for project checks';
+          [[ ! $(which python3) ]] && exit 1
         fi;
         if [[ ! $(which clangd) ]] && ${{ inputs.project }}; then
           sudo apt-get -yq install clang clangd >/dev/null && echo -e "\n####################\nclang dependencies Installed\n####################\n" || echo -e '::error::No clang installed for project build';
@@ -171,11 +176,20 @@ runs:
           sudo apt-get install -yq clang-tidy clang-tools >/dev/null && echo -e "${text5}" || echo -e '::error::No clang-tidy installed Exiting';
           [[ ! $(clang-tidy --version 2>/dev/null) ]] && exit 1
         fi;
-        if [[ ! $(which clangd-tidy) ]] &&  ${{ inputs.project }} && ${{ inputs.analysis == 3 }}; then
+        if [[ ! $(which clangd-tidy) ]] && ${{ inputs.project }} && ${{ inputs.analysis == 3 }}; then
           python -m pip install clangd-tidy >/dev/null && echo -e "\n####################\nclangd-tidy dependencies Installed\n####################\n" || echo -e '::error::No clangd-tidy installed for project checks';
           if [[ $(which clangd-tidy) ]] && [[ -d '/home/runner/.local/bin' ]]; then
             echo -e "export PATH=$PATH:/home/runner/.local/bin" | sudo tee -a ~/.bashrc >/dev/null;
-            echo -e "\nclangd-tidy to bin:\n$(cp -vpf /home/runner/.local/bin/clangd-tidy /usr/bin/ 2>/dev/null)\n";
+            echo -e "\nclangd-tidy to bin:\n$(cp -vpf /home/runner/.local/bin/clangd-tidy /usr/bin/ )\n";
+          else
+            exit 1
+          fi;
+        fi;
+        if [[ ! -f "${codechecker}" ]] &&  ${{ inputs.project }} && ${{ inputs.analysis == 4 }}; then
+          python -m pip3 install codechecker >/dev/null && echo -e "\n####################\ncodechecker dependencies Installed\n####################\n" || echo -e '::error::No codechecker installed for project checks';
+          if [[ "${codechecker}" ]] && [[ -d "${codechecker%/*}" ]]; then
+            echo -e "export PATH=$PATH:${codechecker%/*}" | sudo tee -a ~/.bashrc >/dev/null;
+            echo -e "\ncodechecker to bin:\n$(cp -vpf ${codechecker} /usr/bin/ )\n";
           else
             exit 1
           fi;
@@ -192,10 +206,6 @@ runs:
         if [[ ! $(which cmake) ]] && ${{ inputs.project }}; then
           sudo apt-get -yq install cmake >/dev/null >/dev/null && echo -e "\n####################\ncmake dependencies Installed\n####################\n" || echo -e '::error::No cmake installed for project build';
           [[ ! $(which cmake) ]] && exit 1
-        fi;
-        if [[ ! $(which python3) ]] && ${{ inputs.project }} && ${{ inputs.analysis == 2 }}; then
-          sudo apt-get -yq install python3 >/dev/null >/dev/null && echo -e "\n####################\npython3 dependencies Installed\n####################\n" || echo -e '::error::No python3 installed for project checks';
-          [[ ! $(which python3) ]] && exit 1
         fi;
         if [[ ! $(which npm) ]]; then
           sudo npm install >/dev/null && echo -e "\n####################\nnpm dependencies Installed\n####################\n" || echo -e '::error::No npm installed for term_width';
@@ -576,7 +586,7 @@ runs:
             sudo chmod -v 0755 "${clang_run}" 2>/dev/null | process_input;
             sudo chmod -R 0755 "${clang_fix}" 2>/dev/null;
             echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
-            { time find -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune -o -path "*/.github/*" -prune -o -path "*/CMakeFiles/*" -prune \) -type f -name "*.${file_type}" -exec ${{ github.action_path }}/scripts/tools/run-clang-tidy.py '{}' -p build -config-file "${clang_tidy}" -export-fixes build/fixes -j "$(nproc --all)" -fix \; | process_input; } 2>&1;
+            { time find -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune -o -path "*/.github/*" -prune -o -path "*/CMakeFiles/*" -prune \) -type f -name "*.${file_type}" -exec sh -c '"${{ github.action_path }}/scripts/tools/run-clang-tidy.py" "$@" -p build -config-file "${clang_tidy}" -export-fixes build/fixes -j "$(nproc --all)" -fix' sh {} + | process_input; } 2>&1;
             if [[ "${PIPESTATUS[1]}" == 0 ]]; then
               echo -e '\n|RUNTIME|\n' | process_input;
               check_build=true
@@ -589,8 +599,8 @@ runs:
             exit 1
           fi;
           if [[ -f "${clang_tidy}" ]] && ${{ env.analysis == 3 }}; then
-              echo -e '\n####################\nCLANGD-TIDY ANALYZING FILE\n####################\n' | process_input;
-              { time find -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune -o -path "*/.github/*" -prune -o -path "*/CMakeFiles/*" -prune \) -type f -name "*.${file_type}" -print0 | xargs -0 -r -n 4 -I {} sh -c 'clangd-tidy "{}" -p build -j "$(nproc --all)"' -- {} | process_input; } 2>&1;
+            echo -e '\n####################\nCLANGD-TIDY ANALYZING FILE\n####################\n' | process_input;
+            { time find -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune -o -path "*/.github/*" -prune -o -path "*/CMakeFiles/*" -prune \) -type f -name "*.${file_type}" -exec sh -c 'clangd-tidy "$@" -p build -j "$(nproc --all)"' sh {} + | process_input; } 2>&1;
             if [[ -s "${project_log}" ]] && [[ $(grep -sE ': Error:' "${project_log}") ]]; then
               echo -e '\n|RUNTIME|\n' | process_input;
               echo -e "::notice::Errors found checking project files" | process_input;
@@ -608,11 +618,24 @@ runs:
           fi;
           if [[ -d 'build' ]] && ${{ env.analysis == 4 }}; then
             echo -e '\n####################\n\tbuild directory created continuing...\n####################\n' | process_input;
-            { \
-              time \
-              cmake --build build \
-              | process_input;
-            } 2>&1;
+            source ~/codechecker/venv/bin/activate
+            export PATH=~/codechecker/build/CodeChecker/bin:$PATH
+            if ${{ inputs.build }}; then
+              { \
+                time \
+                  CodeChecker check -b "cmake clean && cmake" -o ./results | process_input \
+                  CodeChecker server | process_input \
+                  CodeChecker store ./results -n "${repository}" | process_input;
+              } 2>&1;
+            else
+              [[ -e 'compile_commands.json' ]] && rm -vf compile_commands.json | process_input;
+              { \
+                time \
+                  CodeChecker log --build "make" --output ./compile_commands.json | process_input \
+                  CodeChecker analyze ./compile_commands.json --enable sensitive --output | process_input; 
+               } 2>&1;
+              [[ -e 'compile_commands.json' ]] && cp -vf compile_commands.json ./build | process_input;
+            fi;
             if [[ "${PIPESTATUS[1]}" == 0 ]]; then
               echo -e '\n|RUNTIME|\n' | process_input;
               check_build=true
@@ -637,6 +660,9 @@ runs:
           fi;
           if [[ ${update} ]] && ${{ env.analysis == 1 }}; then
             echo -e "\nPARAMETERS: $(rm -vf ${clang_file} 2>/dev/null)\n" | process_input;
+          fi;
+          if ${{ inputs.build }}; then
+            cp -Rf ./build ${github}/ && echo -e '\n####################\n\tbuild directory updated continuing...\n####################\n' | process_input;
           fi;
           echo -e "\n####################\n\tINSTALLED COMPILERS\n####################\n\n${compiler_list}\n" | process_input;
           if [[ ${check_build} ]]; then
