Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -454,9 +454,9 @@ runs:
           clang_tidy='.clang-tidy';
           clang_run=${{ github.action_path }}/scripts/tools/run-clang-tidy.py;
           echo "repository=${repository}" >> "${GITHUB_ENV}";
-          include_dirs() {
-            sudo find . -type d -name 'include' -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r dir; do
-              echo -n "${dir#./} "
+          src_dirs() {
+            sudo find . -type d -maxdepth 1 -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r dir; do
+              echo -e "${dir#./}"
             done;
           }
           file_list() {
@@ -473,8 +473,8 @@ runs:
           mkdir -p build
           if [[ -d 'build' ]]; then
             echo -e '\n####################\n\tbuild directory created continuing...\n####################\n' | process_input;
-            if [[ "$(include_dirs)" ]]; then
-              cmake -S . -DPROJECT_INCLUDE_DIRS="$(include_dirs)" -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
+            if [[ "$(src_dirs)" ]]; then
+              cmake -S . -DPROJECT_SRC_DIRS="$(src_dirs)" -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
             else
               cmake -S . -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
             fi;
