Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -235,6 +235,10 @@ runs:
           sudo apt-get -yq install git git-core 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "${text0}" || echo -e '::error::No git installed for repo updates';
           [[ ! $(which git) ]] && exit 1
         fi;
+        if [[ ! $(which gcc) ]] || [[ ! $(which g++) ]] && ${{ inputs.repair }} && ${{ inputs.filename != '' }}; then
+          sudo apt-get -yq install gcc g++ 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "\n####################\ngcc g++ dependencies Installed\n####################\n" || echo -e '::error::No gcc or g++ installed for repo updates';
+          [[ ! $(which gcc) ]] || [[ ! $(which g++) ]] && exit 1
+        fi;
         if [[ ! $(which python3) ]] && ${{ inputs.project }} && ${{ inputs.analyzer == 2 }}; then
           sudo apt-get -yq install python3 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "\n####################\npython3 dependencies Installed\n####################\n" || echo -e '::error::No python3 installed for project checks';
           [[ ! $(which python3) ]] && exit 1
@@ -242,7 +246,7 @@ runs:
         if [[ ! $(llvm-config --version 2>/dev/null) ]] && ${{ inputs.project }}; then
           sudo bash -c "$(sudo wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - >/dev/null 2>&1)"
           sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs) main" >/dev/null;
-          sudo apt-get -yq install llvm-22-dev liblldb-22-dev llvm llvm-dev lld libclang-dev 2>&1 >/dev/null | sed -e 's/^.*host\.//' && echo -e "\n####################\nllvm tools dependencies Installed\n####################\n" || echo -e '::error::No llvm tools installed for project build';
+          sudo apt-get -yq install lld llvm llvm-dev liblldb-dev libclang-dev 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "\n####################\nllvm tools dependencies Installed\n####################\n" || echo -e '::error::No llvm tools installed for project build';
           [[ ! $(llvm-config --version 2>/dev/null) ]] && exit 1
         fi;
         if [[ ! $(which clang-tidy) ]] && ([[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]] && ${{ inputs.repair }}) || ${{ inputs.project }}; then
@@ -352,27 +356,27 @@ runs:
       id: display-type
       uses: actions/github-script@v6
       with:
-      script: |
-        const core = require('@actions/core');
-        const github = require('@actions/github');
-        const name = core.getInput('who-to-greet');
-        core.setOutput('time', new Date().toTimeString());
-        console.log(`Hello ${name}!`);
-        function getWindowSize() {
-          const width = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
-          const height = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;
-          return { width, height };
-        }
-        const size = getWindowSize();
-        console.log(`Browser window size: ${size.width}x${size.height}`);
-        if (window.matchMedia("(min-width: 400px)").matches) {
-          core.setOutput("mobile-view", true);
-        } else {
-          core.setOutput("mobile-view", false);
-        }
+        script: |
+          const core = require('@actions/core');
+          const github = require('@actions/github');
+          const name = core.getInput('who-to-greet');
+          core.setOutput('time', new Date().toTimeString());
+          console.log(`Hello ${name}!`);
+          function getWindowSize() {
+            const width = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
+            const height = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;
+            return { width, height };
+          }
+          const size = getWindowSize();
+          console.log(`Browser window size: ${size.width}x${size.height}`);
+          if (window.matchMedia("(min-width: 400px)").matches) {
+            core.setOutput("mobile-view", true);
+          } else {
+            core.setOutput("mobile-view", false);
+          }
       shell: bash
       continue-on-error: true
-
+      
     - name: Set Directory Base
       if: inputs.pattern != '' || inputs.filename != '' || inputs.project != 'false'
       id: set_dirname 
