Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -62,6 +62,16 @@ inputs:
     type: boolean
     required: false
     default: 'false'
+  version:
+    description: 'LLVM Clang vsrsion used for project'
+    type: number
+    required: false
+    default: '21'
+  release:
+    description: 'LLVM embeded-toolchain-arm version used for arm kernels only'
+    type: number
+    required: false
+    default: '19.1.1'
   recheck:
     description: 'Recheck files repaired by check-file'
     type: boolean
@@ -77,11 +87,6 @@ inputs:
     type: boolean
     required: false
     default: 'false'
-  version:
-    description: 'LLVM Clang compiler used for project building only'
-    type: number
-    required: false
-    default: '21'
   content:
     description: 'Search will list dir contents of found filename'
     type: boolean
@@ -280,35 +285,28 @@ runs:
       continue-on-error: true
 
     - name: Install LLVM and Clang
-      if: inputs.project == 'true' && runner.os == 'Linux' && inputs.arch != 'arm'
+      if: runner.os == 'Linux' && (inputs.project == 'true' || inputs.filename != '' || inputs.filetype != '')
       run: |
         source ~/.bashrc
         bash -c "${{ github.action_path }}/scripts/linux.sh";
+        if ${{ inputs.project == 'true' }} && ${{ inputs.kernel == 'true' }} && ${{ inputs.arch == 'arm' }}; then
+          bash -c "${{ github.action_path }}/scripts/linux-arm.sh";
+        fi;
       env:
         LLVM_VERSION: ${{ inputs.version }}
+        LLVM_ARM_VERSION: ${{ inputs.release }}
         SETUP_LLVM_GITHUB_TOKEN: ${{ inputs.token }}
       shell: bash
       continue-on-error: true
 
     - id: output-path
-      if: inputs.project == 'true' && runner.os == 'Linux' && inputs.arch != 'arm'
+      if: runner.os == 'Linux' && (inputs.project == 'true' || inputs.filename != '' || inputs.filetype != '')
       run: |
         print('')
         import os
         with open(os.getenv("GITHUB_OUTPUT"), "a") as f:
           print(f"llvm-path={os.getenv('LLVM_PATH')}", file=f)
       shell: python
-      continue-on-error: true
-
-    - name: Install LLVM Embedded Toolchain for Arm
-      if: inputs.project == 'true' && inputs.kernel == 'true' && inputs.arch == 'arm'
-      uses: stellar-aria/llvm-embedded-toolchain-for-arm-action@latest
-      with:
-        release: '18.1.3'
-        path-env-var: LLVM_ARM_PATH
-        toolchain-env-var: LLVM_ARM_TOOLCHAIN
-      env:
-        SETUP_LLVM_GITHUB_TOKEN: ${{ inputs.token }}
       continue-on-error: true
 
     - name: Setup An Clang Clean
@@ -362,30 +360,30 @@ runs:
         sudo apt-get clean
         sudo add-apt-repository universe >/dev/null;
         sudo apt-get -yq update 2>&1 >/dev/null | sed '/Running/,/host./d';
-        sudo apt-get -yq install aptitude 2>&1 >/dev/null | sed '/Running/,/host./d';
+        sudo apt-get -yq install aptitude 2>&1 >/dev/null | sed '/Running/,/host./d' || echo -e '::error::No aptitude installer for installing packages';
+        linux_distro1="24.04";
+        linux_distro2="22.04";
+        linux_distro3="20.04";
+        linux_verison=$(lsb_release -r | awk '{ print $2; }');
         if ${{ inputs.project == 'true' }} && [[ ! $(which cmake) ]]; then
           sudo aptitude -yq install cmake make 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\ncmake dependencies installed\n####################" || echo -e '::error::No cmake installed for project build';        
           [[ ! $(which cmake) ]] && exit 1
         fi;
+        if [[ ! $(which clang) ]]; then
+          sudo aptitude -yq install clang 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "####################\nclang dependencies installed\n####################" || echo -e '::error::No clang installed for repo updates';
+          [[ ! $(which clang) ]] && exit 1
+        fi;
+        cmake_version=$(cmake --version 2>/dev/null | grep version | awk '{ print $3; }');
+        clang_version=$(clang --version 2>/dev/null | awk '{ print $4; }');
+        clang_tidy_version=$(clang-tidy --version 2>/dev/null | grep version | awk '{ print $3; }');
+        clang_tidy_required_version='21.1.6';
+        cmake_required_version="4.2.1";
         if (${{ inputs.project == 'true' }} || [[ "${file_type}" == [cth]* ]]) && ([[ ! $(which clang-tidy) ]] || [[ $(printf '%s\n%s' "${clang_tidy_version}" "${clang_tidy_required_version}" | sort -V | head -n1) == "${clang_tidy_version}" ]] && [[ "${clang_tidy_version}" != "${clang_tidy_required_version}" ]]); then
           python3 -m pip install --upgrade clang-tools >/dev/null && echo -e "\n####################\nclang tools pip dependencies installed\n####################\n" || echo -e '::error::No clang tools installed for project check';
           [[ ! -e '/usr/bin/clang-tidy' ]] && [[ -e "${HOME}/.local/bin/clang-tidy" ]] && sudo mv -vf "${HOME}/.local/bin/clang-tidy" '/usr/bin/clang-tidy'
           [[ -e "${HOME}/.local/bin/run-clang-tidy" ]] && sudo mv -vf "${HOME}/.local/bin/run-clang-tidy" '/usr/bin/run-clang-tidy'
           [[ ! $(which clang-tidy) ]] && exit 1
         fi;
-        if [[ ! $(which clang) ]]; then
-          sudo aptitude -yq install clang 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "####################\nclang dependencies installed\n####################" || echo -e '::error::No clang installed for repo updates';
-          [[ ! $(which clang) ]] && exit 1
-        fi;
-        cmake_version=$(cmake --version | grep version | awk '{ print $3; }');
-        clang_version=$(clang --version | awk '{ print $4; }');
-        clang_tidy_version=$(clang-tidy --version | grep version | awk '{ print $3; }');
-        clang_tidy_required_version='21.1.6';
-        cmake_required_version="4.2.1";
-        linux_distro1="24.04";
-        linux_distro2="22.04";
-        linux_distro3="20.04";
-        linux_verison=$(lsb_release -r | awk '{ print $2; }');
         if ${{ inputs.project == 'true' }}; then
           if [[ $(printf '%s\n%s' "${cmake_version}" "${cmake_required_version}" | sort -V | head -n1) == "${cmake_version}" ]] && [[ "${cmake_version}" != "${cmake_required_version}" ]] && ${{ inputs.project }}; then
             echo -e "Current CMake version (${cmake_version}) is older than ${cmake_required_version}. Updating....";
