Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -2328,7 +2328,7 @@ runs: # Uses default x86_64 / linux user machine
               include_paths='check-file-includes';
               echo -n > 'temp-file';
               include_source=$( { rg --sort=path --trim -o '^#include[[:space:]]+[<"].*[">]' "${file}" 2>/dev/null || true; } | gawk '{print $2}' | tr -d '<">' | sort -u);
-              [[ -n "${include_source}" ]] && echo -e "\n\033[1mTotal header objectives found\033[0m:\n${include_source}" | gawk '{ printf "    %s\n", $0; }' | process_input;
+              [[ -n "${include_source}" ]] && echo -e "\n\033[1mTotal header objectives found\033[0m:\n${include_source}" | gawk '{ printf "    \033[4m%s\033[0m\n", $0; }' | process_input;
               while IFS= read -r include; do
                 if [[ "${include}" == *.[ch]* ]]; then
                   clean_path="${include##*./}";
@@ -2342,24 +2342,24 @@ runs: # Uses default x86_64 / linux user machine
                     while IFS= read -r includes; do
                       count2=$((include_count++));
                       echo "${includes%/*}" >> 'temp-file';
-                      echo -e "\n\033[33mSource file #include \033[0m\033[1m( ${includes##*/} )\033[0m\033[43m is located!\033[0m  [ ${count2} / ✅ ]\n\033[32mLOCATION:\033[0m ${includes}" | process_input;
+                      echo -e "\n\033[33mSource file #include \033[0m\033[1m( ${includes##*/} )\033[0m\033[33m is located!\033[0m  [ ${count2} / ✅ ]\n\033[32mLOCATION:\033[0m ${includes}" | process_input;
                     done <<< "${header[@]}";
                     includes_found=true
                   elif [[ -n "${missing[$include]}" ]]; then
-                    echo -e "\n\033[33mSource file #include \033[0m( ${include} )\033[33m already listed missing!\033[0m  [\033[41m skipped \033[0m]" | process_input;
+                    echo -e "\n\033[33mSource file #include \033[0m( ${include} )\033[33m already listed missing!\033[0m  [\033[31m skipped \033[0m]" | process_input;
                     includes_found=false      
                   else
                     includes_found=false
                     missing["${include}"]=1
                     countX=$((include_missing++));
-                    echo -e "\n::notice::\033[31mSource file #include \033[0m( ${clean_file##*./} )\033[41m is missing!?\033[0m  [ ${countX} / ❌ ]" | process_input;
+                    echo -e "\n::notice::\033[31mSource file #include \033[0m( ${clean_file##*./} )\033[31m is missing!?\033[0m  [ ${countX} / ❌ ]" | process_input;
                   fi;
                 fi;
               done <<< "${include_source[@]}";
-              echo -e "\n::notice::Total include files found: ${count2}" | gawk '{ printf " \033[42m%s\033[0m\n", $0; }' | process_input;
+              echo -e "\n::notice::Total include files found: ${count2}" | gawk '{ printf " \033[32m%s\033[0m\n", $0; }' | process_input;
               if [[ -s 'temp-file' ]]; then
                 sed -E '/\/include\// s|/[^/]+$||' temp-file | sort -u > "${include_paths}";
-                echo -e "\ncheck-file: objectives for \033[1m${file##*/}\033[0m -I/\033[44minclude/directory/paths\033[0m/ added!" | process_input;
+                echo -e "\ncheck-file: objectives for \033[1m${file##*/}\033[0m -I/\033[43minclude/directory/paths\033[0m/ added!" | process_input;
                 [[ -s "${include_paths}" ]] && cp -v "${include_paths}" build/
               fi;
               if ${{ inputs.repair == 'true' }}; then
@@ -2407,7 +2407,7 @@ runs: # Uses default x86_64 / linux user machine
                   else
                     file="${file#*./}";
                   fi;
-                  cppcheck -j "$(nproc)" -l 2 --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --cppcheck-build-dir="${build_dir}" --includes-file="${include_paths}" --project="${compile_json}" --file-filter="${file}" 2>&1 | process_input || error="$?";
+                  cppcheck -j "$(nproc)" -l 2 --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --cppcheck-build-dir="${build_dir}" --project="${compile_json}" --file-filter="${file}" --includes-file="${include_paths}" 2>&1 | process_input || error="$?";
                 else
                   cppcheck -j "$(nproc)" -l 2 --verbose --force --enable="${cppchecks}" --report-progress --suppress=missingIncludeSystem --suppress=checkersReport --cppcheck-build-dir="${build_dir}" "${file}" --includes-file="${include_paths}" 2>&1 | process_input || error="$?";
                 fi;
