Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -313,10 +313,6 @@ runs: # Uses default x86_64 / linux user machine
         file_name="${{ env.filename }}";
         file_type="${file_name##*.}";
         github="${GITHUB_WORKSPACE}";
-        linux_distro1="24.04";
-        linux_distro2="22.04";
-        linux_distro3="20.04";
-        linux_verison=$(lsb_release -r | awk '{ print $2; }');
         repo=$(echo ${{ github.repository }} | cut -d'/' -f 2-);
         echo "github_repository=${repo}" >> "${GITHUB_ENV}";
         if ${{ inputs.filename != '' }}; then
@@ -401,61 +397,11 @@ runs: # Uses default x86_64 / linux user machine
         sudo apt-get -yq update 2>&1 >/dev/null | sed '/Running/,/host./d';
         sudo apt-get -yq install aptitude 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\naptitude dependencies installed\n####################" || echo -e '::error::No aptitude installer for installing packages';
         echo 'deb [trusted=yes] https://apt.gabe565.com /' | sudo tee -a /etc/apt/sources.list.d/gabe565.list >/dev/null;
-        if ${{ inputs.project == 'true' }} && [[ ! $(which cmake) ]]; then
-          sudo aptitude -yq install cmake make 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\ncmake dependencies installed\n####################" || echo -e '::error::No cmake installed for project build';        
-          [[ ! $(which cmake) ]] && exit 1
-        fi;
-        if [[ ! $(which clang) ]]; then
-          sudo aptitude -yq install clang 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "####################\nclang dependencies installed\n####################" || echo -e '::error::No clang installed for repo updates';
-          [[ ! $(which clang) ]] && exit 1
-        fi;
-        if [[ ! $(which python3) ]]; then
-          sudo aptitude -yq install python3 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "####################\npython3 dependencies installed\n####################" || echo -e '::error::No python3 installed for project checks';
-          [[ ! $(which python3) ]] && exit 1
-        fi;
-        cmake_version=$(cmake --version 2>/dev/null | grep version | awk '{ print $3; }');
-        clang_version=$(clang --version 2>/dev/null | awk '{ print $4; }');
-        clang_tidy_version=$(clang-tidy --version 2>/dev/null | grep version | awk '{ print $3; }');
-        clang_tidy_required_version='21.1.6';
-        cmake_required_version="4.2.1";
-        if (${{ inputs.project == 'true' }} || [[ "${file_type}" == [cth]* ]]) && ([[ ! $(which clang-tidy) ]] || [[ $(printf '%s\n%s' "${clang_tidy_version}" "${clang_tidy_required_version}" | sort -V | head -n1) == "${clang_tidy_version}" ]] && [[ "${clang_tidy_version}" != "${clang_tidy_required_version}" ]]); then
-          python3 -m pip install --upgrade clang-tools >/dev/null && echo -e "\n####################\nclang tools pip dependencies installed\n####################\n" || echo -e '::error::No clang tools installed for project check';
-          [[ -e "${HOME}/.local/bin/clang-tidy" ]] && sudo mv -vf "${HOME}/.local/bin/clang-tidy" '/usr/bin/clang-tidy' && echo '';
-          [[ -e "${HOME}/.local/bin/run-clang-tidy" ]] && sudo mv -vf "${HOME}/.local/bin/run-clang-tidy" '/usr/bin/run-clang-tidy'
-          [[ ! $(which clang-tidy) ]] && exit 1
-        fi;
-        [[ ! $(which make) ]] && sudo aptitude install -yq make >/dev/null && echo -e "\n####################\nmake dependencies installed\n####################";
-        if ${{ inputs.project == 'true' }}; then
-          if [[ $(printf '%s\n%s' "${cmake_version}" "${cmake_required_version}" | sort -V | head -n1) == "${cmake_version}" ]] && [[ "${cmake_version}" != "${cmake_required_version}" ]] && ${{ inputs.project }}; then
-            echo -e "Current CMake version (${cmake_version}) is older than ${cmake_required_version}. Updating....";
-            sudo apt-get remove --purge -yq cmake 2>&1 >/dev/null | sed '/Running/,/host./d'
-            sudo aptitude install -yq ca-certificates gpg wget 2>&1 >/dev/null | sed '/Running/,/host./d'
-            sudo bash -c "$(sudo wget -qO - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null)";
-            if [[ "${linux_verison}" == "${linux_distro1}" ]]; then
-              echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | sudo tee -a /etc/apt/sources.list.d/kitware.list >/dev/null;
-            elif [[ "${linux_verison}" == "${linux_distro2}" ]]; then
-              echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee -a /etc/apt/sources.list.d/kitware.list >/dev/null;
-            elif [[ "${linux_verison}" == "${linux_distro3}" ]]; then
-              echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | sudo tee -a /etc/apt/sources.list.d/kitware.list >/dev/null;
-            else
-              echo -e "\nKitWare Keyring: Noble ${linux_verison}\n";
-              echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | sudo tee -a /etc/apt/sources.list.d/kitware.list >/dev/null;
-            fi;
-          fi;
-        fi;
-        if ${{ inputs.project == 'true' }} && [[ $(printf '%s\n%s' "${cmake_version}" "${cmake_required_version}" | sort -V | head -n1) == "${cmake_version}" ]] && [[ "${cmake_version}" != "${cmake_required_version}" ]]; then
-          python3 -m pip install --upgrade pip >/dev/null && echo -e "\n####################\npip dependencies installed\n####################" || echo -e '::warning::pip not updated for project checks';
-          echo -e "\nCMake version $cmake_version upgrading to latest python cmake";
-          sudo rm -f "$(which cmake)";
-          sudo mkdir -p '/usr/local/bin';
-          echo "/usr/local/bin" >> "${GITHUB_PATH}";
-          python3 -m pip install --upgrade cmake >/dev/null && echo -e "\n####################\ncmake pip dependencies installed\n####################" || echo -e '::error::No cmake pip installed for project checks';
-          sudo cp -vpf "${HOME}/.local/bin/cmake" '/usr/local/bin/';
-        fi;
-        echo '';
       shell: bash
       continue-on-error: false
 
+
+    
     - name: Install LLVM and Clang
       if: runner.os == 'Linux' && inputs.pattern == '' && (inputs.project == 'true' || inputs.filename != '' || inputs.filetype != '')
       run: |
@@ -486,8 +432,76 @@ runs: # Uses default x86_64 / linux user machine
           print(f"llvm-path={os.getenv('LLVM_PATH')}", file=f)
       shell: python
       continue-on-error: true
-    
+
     - name: Installing Dependencies
+      if: inputs.project == 'true' || inputs.filename != '' || inputs.filetype != ''
+      run: |
+        echo '';
+        set +e
+        source ~/.bashrc
+        file_name="${{ env.filename }}";
+        file_type="${file_name##*.}";
+        github="${GITHUB_WORKSPACE}";
+        linux_distro1="24.04";
+        linux_distro2="22.04";
+        linux_distro3="20.04";
+        linux_verison=$(lsb_release -r | awk '{ print $2; }');
+        if ${{ inputs.project == 'true' }} && [[ ! $(which cmake) ]]; then
+          sudo aptitude -yq install cmake make 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\ncmake dependencies installed\n####################" || echo -e '::error::No cmake installed for project build';        
+          [[ ! $(which cmake) ]] && exit 1
+        fi;
+        if [[ ! $(which clang) ]]; then
+          sudo aptitude -yq install clang 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "####################\nclang dependencies installed\n####################" || echo -e '::error::No clang installed for repo updates';
+          [[ ! $(which clang) ]] && exit 1
+        fi;
+        if [[ ! $(which python3) ]]; then
+          sudo aptitude -yq install python3 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "####################\npython3 dependencies installed\n####################" || echo -e '::error::No python3 installed for project checks';
+          [[ ! $(which python3) ]] && exit 1
+        fi;
+        cmake_version=$(cmake --version 2>/dev/null | grep version | awk '{ print $3; }');
+        clang_version=$(clang --version 2>/dev/null | awk '{ print $4; }');
+        clang_tidy_version=$(clang-tidy --version 2>/dev/null | grep version | awk '{ print $3; }');
+        clang_tidy_required_version='21.1.6';
+        cmake_required_version="4.2.1";
+        if (${{ inputs.project == 'true' }} || [[ "${file_type}" == [cth]* ]]) && ([[ ! $(which clang-tidy) ]] || [[ $(printf '%s\n%s' "${clang_tidy_version}" "${clang_tidy_required_version}" | sort -V | head -n1) == "${clang_tidy_version}" ]] && [[ "${clang_tidy_version}" != "${clang_tidy_required_version}" ]]); then
+          python3 -m pip install --upgrade clang-tools >/dev/null && echo -e "\n####################\nclang tools pip dependencies installed\n####################\n" || echo -e '::error::No clang tools installed for project check';
+          [[ -e "${HOME}/.local/bin/clang-tidy" ]] && sudo mv -f "${HOME}/.local/bin/clang-tidy" '/usr/bin/clang-tidy' && echo '';
+          [[ -e "${HOME}/.local/bin/run-clang-tidy" ]] && sudo mv -f "${HOME}/.local/bin/run-clang-tidy" '/usr/bin/run-clang-tidy'
+          [[ ! $(which clang-tidy) ]] && exit 1
+        fi;
+        [[ ! $(which make) ]] && sudo aptitude install -yq make >/dev/null && echo -e "\n####################\nmake dependencies installed\n####################";
+        if ${{ inputs.project == 'true' }}; then
+          if [[ $(printf '%s\n%s' "${cmake_version}" "${cmake_required_version}" | sort -V | head -n1) == "${cmake_version}" ]] && [[ "${cmake_version}" != "${cmake_required_version}" ]] && ${{ inputs.project }}; then
+            echo -e "Current CMake version (${cmake_version}) is older than ${cmake_required_version}. Updating....";
+            sudo apt-get remove --purge -yq cmake 2>&1 >/dev/null | sed '/Running/,/host./d'
+            sudo aptitude install -yq ca-certificates gpg wget 2>&1 >/dev/null | sed '/Running/,/host./d'
+            sudo bash -c "$(sudo wget -qO - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null)";
+            if [[ "${linux_verison}" == "${linux_distro1}" ]]; then
+              echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | sudo tee -a /etc/apt/sources.list.d/kitware.list >/dev/null;
+            elif [[ "${linux_verison}" == "${linux_distro2}" ]]; then
+              echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee -a /etc/apt/sources.list.d/kitware.list >/dev/null;
+            elif [[ "${linux_verison}" == "${linux_distro3}" ]]; then
+              echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | sudo tee -a /etc/apt/sources.list.d/kitware.list >/dev/null;
+            else
+              echo -e "\nKitWare Keyring: Noble ${linux_verison}\n";
+              echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | sudo tee -a /etc/apt/sources.list.d/kitware.list >/dev/null;
+            fi;
+          fi;
+        fi;
+        if ${{ inputs.project == 'true' }} && [[ $(printf '%s\n%s' "${cmake_version}" "${cmake_required_version}" | sort -V | head -n1) == "${cmake_version}" ]] && [[ "${cmake_version}" != "${cmake_required_version}" ]]; then
+          python3 -m pip install --upgrade pip >/dev/null && echo -e "\n####################\npip dependencies installed\n####################" || echo -e '::warning::pip not updated for project checks';
+          echo -e "\nCMake version $cmake_version upgrading to latest python cmake";
+          sudo rm -f "$(which cmake)";
+          sudo mkdir -p '/usr/local/bin';
+          echo "/usr/local/bin" >> "${GITHUB_PATH}";
+          python3 -m pip install --upgrade cmake >/dev/null && echo -e "\n####################\ncmake pip dependencies installed\n####################" || echo -e '::error::No cmake pip installed for project checks';
+          sudo cp -pf "${HOME}/.local/bin/cmake" '/usr/local/bin/';
+        fi;
+        echo '';
+      shell: bash
+      continue-on-error: false
+    
+    - name: Installing Extra Dependencies
       if: inputs.pattern != '' || env.filename != '' || inputs.project != 'false'
       run: |
         source ~/.bashrc
@@ -655,7 +669,7 @@ runs: # Uses default x86_64 / linux user machine
         EOF
           sudo rm -rf /var/lib/apt/lists/*
           sudo apt update >/dev/null 2>&1
-          sudo aptitude install -yq gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-multilib libc6-dev libgcc-s1 gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "####################\narm dependencies installed\n####################\n"; 
+          sudo aptitude install -yq gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-multilib libc6-dev libgcc-s1 gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\narm dependencies installed\n####################\n"; 
         elif [[ "${linux_verison}" == "${linux_distro2}" ]] && [[ "${{ env.arch }}" == "arm"* ]] && [[ -z "${{ inputs.pattern }}" ]]; then
           echo -e "\n#### Copying ARM jammy sources to /etc/apt/sources.list ####\n";
           sudo dpkg --add-architecture armhf
@@ -671,7 +685,7 @@ runs: # Uses default x86_64 / linux user machine
         EOF
           sudo rm -rf /var/lib/apt/lists/*
           sudo apt update >/dev/null 2>&1
-          sudo aptitude install -yq gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-multilib libc6-dev libgcc-s1 gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "####################\narm dependencies installed\n####################\n";
+          sudo aptitude install -yq gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-multilib libc6-dev libgcc-s1 gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\narm dependencies installed\n####################\n";
         elif [[ "${linux_verison}" == "${linux_distro3}" ]] && [[ "${{ env.arch }}" == "arm"* ]] && [[ -z "${{ inputs.pattern }}" ]]; then
           echo -e "\n#### Copying ARM focal sources to /etc/apt/sources.list ####\n";
           sudo dpkg --add-architecture armhf
@@ -687,7 +701,7 @@ runs: # Uses default x86_64 / linux user machine
         EOF
           sudo rm -rf /var/lib/apt/lists/*
           sudo apt update >/dev/null 2>&1
-          sudo aptitude install -yq gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-multilib libc6-dev libgcc-s1 gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "####################\narm dependencies installed\n####################\n";
+          sudo aptitude install -yq gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-multilib libc6-dev libgcc-s1 gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\narm dependencies installed\n####################\n";
         fi;
         if [[ "${{ env.arch }}" == "arm"* ]]; then
           sudo dpkg --add-architecture i386 >/dev/null;
@@ -2885,12 +2899,12 @@ runs: # Uses default x86_64 / linux user machine
               fi;
             fi;
             echo -e "\n####################\nCHECKMAKE ANALYZING ${file##*/} FOR ERRORS ($count4)\n####################\n" | process_input;
-            checkmake "${file}" 2>&1 | process_input || error="$?";
-            if [[ -s "${error_log}" ]] && [[ ! $(grep -zPo "(?s)${file}.*?error" "${error_log}") ]]; then
-              echo -e "\n####################\n\033[1mCHECK-FILE\033[0m NO ERRORS FOUND ${file}\n####################" | process_input;
-            else
+            checkmake "${file}" | process_input || error="$?";
+            if [[ -s "${error_log}" ]] && grep -zPoq "(?s)${file}.*?error" "${error_log}"; then
               echo -e "\n####################\n\033[1mCHECK-FILE\033[0m FOUND ERRORS\n####################" | process_input;
               errors=true
+            else
+              echo -e "\n####################\n\033[1mCHECK-FILE\033[0m NO ERRORS FOUND ${file}\n####################" | process_input;
             fi;
             if ${{ inputs.number > '0' }}; then
               if [[ "${{ inputs.number }}" -eq "${count4}" ]]; then
