Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -320,7 +320,23 @@ runs:
           sudo apt-get -yq install shellcheck 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "${text7}" || echo -e '::error::No shellcheck installed Exiting';
           [[ ! $(which shellcheck) ]] && exit 1
         fi;
-        if [[ -d "${repository}" ]]; then
+        echo 'repository_base=null' >> "${GITHUB_ENV}";
+        if [[ -n "${{ inputs.dirname }}" ]]; then
+          cd "${{ inputs.dirname }}";
+          checkmake_src='checkmake.ini';
+          checkmake_des="${HOME}/checkmake.ini";
+          if [[ "${checkmake_src}" ]] && [[ -n $(echo "${file_type}" | egrep -i "^mk$|.*Makefile$") ]] && [[ $(which checkmake) ]]; then
+            sudo cp -vf "${checkmake_src}" "${checkmake_des}" 2>/dev/null;
+          elif [[ -n $(echo "${file_type}" | egrep -i "^mk$|.*Makefile$") ]] && [[ $(which checkmake) ]]; then
+            echo -e '\ncheckmake.ini file missing, needed for checkmake to function properly\n';
+          fi;
+          if [[ "${checkmake_src}" ]] && [[ -n $(echo "${file_type}" | egrep -i "^mk$|.*Makefile$") ]] && [[ ! $(which checkmake) ]]; then
+            go install "github.com/checkmake/checkmake/cmd/checkmake@latest" >/dev/null && echo -e "\n${text8}\n" || echo -e '::error::No checkmake installed Exiting';
+            sudo cp -vf "${checkmake_src}" "${checkmake_des}" 2>/dev/null;
+            [[ ! $(which checkmake) ]] && exit 1
+          fi;
+          echo "repository_base=${{ inputs.dirname }}" >> "${GITHUB_ENV}";
+        elif [[ -d "${repository}" ]]; then
           cd "${repository%/*}";
           checkmake_src='checkmake.ini';
           checkmake_des="${HOME}/checkmake.ini";
@@ -334,6 +350,7 @@ runs:
             sudo cp -vf "${checkmake_src}" "${checkmake_des}" 2>/dev/null;
             [[ ! $(which checkmake) ]] && exit 1
           fi;
+          echo "repository_base=${repository%/*}" >> "${GITHUB_ENV}";
         fi;
         if ${{ inputs.filename != '' }} || ${{ inputs.pattern != '' }}; then
           if [[ $(which bat) ]] && [[ ! $(which batcat) ]]; then
@@ -366,7 +383,6 @@ runs:
       run: |
         echo '';
         repair_file='check-file-repaired.txt';
-        repository=$(sudo find ${GITHUB_WORKSPACE} -type d -name '.git' -print -quit);
         repo=$(echo ${{ github.repository }} | cut -d'/' -f 2-);
         echo 'database=database' >> "${GITHUB_ENV}";
         text1a="####################";
@@ -486,8 +502,8 @@ runs:
         else
           echo "analyzer=${{ inputs.analyzer }}" >> "${GITHUB_ENV}";
         fi;
-        if [[ -d ${repository} ]]; then
-          cd "${repository%/*}";
+        if [[ -n "${{ env.repository_base }}" ]]; then
+          cd "${{ env.repository_base }}";
           src=$(ls 2>/dev/null);
           total_files=$(find -type f | grep -v '\.git/.' | wc -l);
           file_type=$(find -type f -name "*.${{ inputs.filetype }}" | grep -v '\.git/.' | wc -l);
@@ -556,7 +572,6 @@ runs:
         export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
         export LC_ALL=C
         set +e
-        repository=$(echo ${{ github.repository }} | cut -d'/' -f 2-);
         project_log="${GITHUB_WORKSPACE}/${repository}_project.log";
         check_build=false
         file_type='c';
@@ -585,8 +600,8 @@ runs:
           file_type="${{ inputs.filetype }}";
         fi;
         echo "filetype=${file_type}" >> "${GITHUB_ENV}";
-        if [[ -d "${src_tree}" ]]; then
-          cd "${src_tree%/*}";
+        if [[ -n "${{ env.repository_base }}" ]]; then
+          cd "${{ env.repository_base }}";
           clang_tidy_version=$(clang-tidy --version);
           clang_version=$(clang --version);
           verify_config=$(clang-tidy --verify-config);
@@ -637,22 +652,21 @@ runs:
             done;
           }
           cmake_includes() {
-            echo -n "${src_tree%/*}/include ";
-            find "${src_tree%/*}" -not \( -path '*/.github' -prune -o -path '*/.git' -prune \) -type d \( -name 'asm' -o -name 'mfd' -o -name 'mtk' -o -name 'mach' -o -name 'linux' \) -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r include; do
-              if [[ -d "${include}" ]]; then
-                echo -n "${include} ";
+            find "${{ env.repository_base }}" -not \( -path '.github/' -prune -o -path '.git/' -prune \) -type d \( -name 'asm' -o -name 'mfd' -o -name 'mtk' -o -name 'mach' -o -name 'linux' -o -name 'include' \) -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r dir; do
+              if [[ -d "${dir}" ]]; then
+                echo -n "${dir} ";
               fi;
             done;
           }
           clang_includes() {
-            find "${src_tree%/*}" -not \( -path '*/.github' -prune -o -path '*/.git' -prune \) -type d -name 'include' -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r include; do
+            find "${{ env.repository_base }}" -not \( -path '*/.github' -prune -o -path '*/.git' -prune \) -type d -name 'include' -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r include; do
               if [[ -d "${include}" ]]; then
                 echo -e "--extra-arg=-I${include}";
               fi;
             done;
           }
           source_files() {
-            find "${src_tree%/*}" -not \( -path '*/CMakeFiles' -prune -o -path '*/build' -prune -o -path '*/.git' -prune -o -path '*/.github' -prune \) -type f -name "*.${file_type}" -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r file; do
+            find "${{ env.repository_base }}" -not \( -path '*/CMakeFiles' -prune -o -path '*/build' -prune -o -path '*/.git' -prune -o -path '*/.github' -prune \) -type f -name "*.${file_type}" -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r file; do
               echo -e "${file#./}";
             done;
           }
@@ -1569,7 +1583,7 @@ runs:
         echo ''
         check_file=$(dirname $(sudo find ${{ env.file_path }} -type f \( -path "*/${{ env.dirname }}/*" -o -path "*" \) -name "${{ inputs.filename }}"));
         if [[ ${{ env.file_found }} != 0  ]]; then
-          echo -e "\n####################\nNOTE: Contents found in directory for $(echo ${{ inputs.filename }} | sed 's/[\/\$]//g')\n####################\n";
+          echo -e "\n####################\nNOTE: Contents found in directory for ${{ inputs.filename }} file(s)\n####################\n";
           ls -Shap "${check_file}";
         fi;
       shell: bash
@@ -1610,20 +1624,19 @@ runs:
         echo '';
         error_log="${GITHUB_WORKSPACE}/${{ inputs.filename }}_error.log";
         repair_date="$(date +%Y%m%d)";
-        repository=$(sudo find ${GITHUB_WORKSPACE} -type d -name ".git" -print -quit);
-        if [[ -d ${repository} ]]; then
+        if [[ -n "${{ env.repository_base }}" ]]; then
           process_input() {
             while IFS= read -r log; do
-              if [[ ${{ inputs.output == 1 }} ]]; then
+              if [[ ${{ inputs.output == '1' }} ]]; then
                 echo "$log" | tee -a "${error_log}";
-              elif [[ ${{ inputs.output == 2 }} ]]; then
+              elif [[ ${{ inputs.output == '2' }} ]]; then
                 echo "$log" >> "${error_log}";
-              elif [[ ${{ inputs.output == 3 }} ]]; then
+              elif [[ ${{ inputs.output == '3' }} ]]; then
                 echo "$log";
               fi;
             done;
           }
-          cd "${repository%/*}";
+          cd "${{ env.repository_base }}";
           if ${{ inputs.project }}; then
             git config --global --add safe.directory .
           fi;
