Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -347,7 +347,7 @@ runs:
           echo 'update=true' >> "${GITHUB_ENV}";
         fi;
         if ${{ inputs.database }}; then
-          sudo find "${file_path}" -type f -print | sort -t/ -k1.2 > "${GITHUB_WORKSPACE}/database";
+          sudo find "${file_path}" -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune \) -type f -print | sort -t/ -k1.2 > "${GITHUB_WORKSPACE}/database";
           if [[ -s "${GITHUB_WORKSPACE}/database" ]]; then
             center_text "\n${text5a}";
             center_text "${text5b}";
@@ -497,13 +497,13 @@ runs:
           echo "repository=${repository}" >> "${GITHUB_ENV}";
           export PATH="${clang_fix}:${PATH}"
           src_dirs() {
-            sudo find -type d -maxdepth 1 -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r dir; do
+            sudo find -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune \) -type d -maxdepth 1 -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r dir; do
               echo -n "${dir#./} "
             done;
           }
           file_list() {
-            sudo find -type f -name "*.${file_type}" -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r file; do
-              echo -e "${file#./}"
+            sudo find -not \( -path "*/CMakeFiles/*" -prune -o -path "*/build/*" -prune -o -path "*/.git/*" -prune \) -type f -name "*.${file_type}" -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r file; do
+              echo -n "${file#./} "
             done;
           }
           if [[ -f "${clang_tidy}" ]]; then
@@ -515,8 +515,8 @@ runs:
           mkdir -p build/fixes
           if [[ -d 'build' ]]; then
             echo -e '\n####################\n\tbuild directory created continuing...\n####################\n' | process_input;
-            if [[ "$(src_dirs)" ]]; then
-              cmake -S . -DPROJECT_SRC_DIRS="$(src_dirs)" -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
+            if [[ "$(file_list)" ]]; then
+              cmake -S . -DPROJECT_SRC_FILES="$(file_list)" -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
             else
               cmake -S . -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
             fi;
@@ -594,13 +594,13 @@ runs:
           fi;
           if [[ -f "${clang_tidy}" ]] && ${{ env.analysis == 3 }}; then
               echo -e '\n####################\nCLANGD-TIDY ANALYZING FILE\n####################\n' | process_input;
-              find -type f -name "*.${file_type}" -print0 2>/dev/null | xargs -0 -r -n 2 -P "$(nproc --all)" clangd-tidy -p build 2>/dev/null | process_input || echo -e "::notice::PipeStatus Check\npipe0=${PIPESTATUS[0]}, pipe1=${PIPESTATUS[1]}, pipe2=${PIPESTATUS[2]}";
-            if [[ "${PIPESTATUS[2]}" == 0 ]]; then
+              sudo find -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune \) -type f -name "*.${file_type}" -print0 2>/dev/null | xargs -0 -r -n 1 -P "$(nproc --all)" clangd-tidy -p build 2>/dev/null | process_input;
+            if [[ "${PIPESTATUS[1]}" != 0 ]]; then
+              echo -e "::warning:: ( $? ) checking project files" | process_input;
+            else
               echo -e '\n|RUNTIME|\n' | process_input;
               check_build=true
               echo 'check_build=true' >> "${GITHUB_ENV}";
-            else
-              echo -e "::warning:: ( $? ) checking project files" | process_input;
             fi;
           elif [[ ! -e "${clang_tidy}" ]] && ${{ env.analysis == 3 }}; then
             echo -e "\n####################\n\t::error:: "${clang_tidy}" file missing in repo Exiting...\n####################\n" | process_input;
@@ -697,9 +697,9 @@ runs:
           repaired=$(grep -sF -m 1 'check-file-repaired.txt' "${{ env.database }}");
         else
           if [[ $(echo "${{ inputs.filename }}" | sed 's/[\/\$]//g' | grep -Po "\b\w+\.\w+\b") ]]; then
-            files=$(sudo find ${{ env.file_path }} -type f \( -path "*/${{ env.dirname }}/*" -o -path "*" \) -name "${{ inputs.filename }}" -print);
+            files=$(sudo find ${{ env.file_path }} -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune \) -type f \( -path "*/${{ env.dirname }}/*" -o -path "*" \) -name "${{ inputs.filename }}" -print);
           else
-            files=$(sudo find ${{ env.file_path }} -type f \( -path "*/${{ env.dirname }}/*" -o -path "*" \) -name "*${{ inputs.filename }}" -print);
+            files=$(sudo find ${{ env.file_path }} -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune \) -type f \( -path "*/${{ env.dirname }}/*" -o -path "*" \) -name "*${{ inputs.filename }}" -print);
           fi;
           clang_file=$(sudo find ${{ env.file_path }} -type f -name '.clang-tidy' -print -quit);
           repaired=$(sudo find ${{ env.file_path }} -type f -name 'check-file-repaired.txt' -print -quit);
