Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -562,13 +562,9 @@ runs:
             if [[ "${files_list}" ]]; then
               cp -vf "${clang_file}" 'build/cmake-source-files.txt' 2>/dev/null;
               echo -e '\n####################\nCLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
-              { \
-                time \
-                clang-tidy @parameter-file 2>/dev/null \
-                | process_input; 
-              } 2>&1;
-              if [[ "${PIPESTATUS[1]}" == 0 ]]; then
-                echo -e '\n|RUNTIME|\n' | process_input;
+              clang-tidy @parameter-file --enable-check-profile | process_input || echo -e "\nError:($?)\n"
+              if [[ "${PIPESTATUS[0]}" == 0 ]]; then
+                # echo -e '\n|RUNTIME|\n' | process_input;
                 check_build=true
                 echo 'check_build=true' >> "${GITHUB_ENV}";
               else
@@ -586,9 +582,9 @@ runs:
             sudo chmod -v 0755 "${clang_run}" 2>/dev/null | process_input;
             sudo chmod -R 0755 "${clang_fix}" 2>/dev/null;
             echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
-            { time find -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune -o -path "*/.github/*" -prune -o -path "*/CMakeFiles/*" -prune \) -type f -name "*.${file_type}" -exec "${{ github.action_path }}/scripts/tools/run-clang-tidy.py" "{}" -p build -config-file "${clang_tidy}" -fix -export-fixes build/fixes -j "$(nproc --all)" -enable-check-profile \; | process_input; } 2>&1;
-            if [[ "${PIPESTATUS[1]}" == 0 ]]; then
-              echo -e '\n|RUNTIME|\n' | process_input;
+            find -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune -o -path "*/.github/*" -prune -o -path "*/CMakeFiles/*" -prune \) -type f -name "*.${file_type}" -exec "${{ github.action_path }}/scripts/tools/run-clang-tidy.py" "{}" -p build -config-file "${clang_tidy}" -fix -export-fixes build/fixes -j "$(nproc --all)" -enable-check-profile \; | process_input;
+            if [[ "${PIPESTATUS[0]}" == 0 ]]; then
+              # echo -e '\n|RUNTIME|\n' | process_input;
               check_build=true
               echo 'check_build=true' >> "${GITHUB_ENV}";
             else
@@ -600,14 +596,14 @@ runs:
           fi;
           if [[ -f "${clangd_tidy}" ]] && ${{ env.analysis == 3 }}; then
             echo -e '\n####################\nCLANGD-TIDY ANALYZING FILE\n####################\n' | process_input;
-            { time find -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune -o -path "*/.github/*" -prune -o -path "*/CMakeFiles/*" -prune \) -type f -name "*.${file_type}" -exec "${clangd_tidy}" "{}" -p build -j "$(nproc --all)" \; | process_input; } 2>&1;
+            find -not \( -path "*/build/*" -prune -o -path "*/.git/*" -prune -o -path "*/.github/*" -prune -o -path "*/CMakeFiles/*" -prune \) -type f -name "*.${file_type}" -exec "${clangd_tidy}" "{}" -p build -j "$(nproc --all)" -- -enable-check-profile \; | process_input;
             if [[ -s "${project_log}" ]] && [[ $(grep -sE ': Error:' "${project_log}") ]]; then
-              echo -e '\n|RUNTIME|\n' | process_input;
+              # echo -e '\n|RUNTIME|\n' | process_input;
               echo -e "::notice::Errors found checking project files" | process_input;
               check_build=true
               echo 'check_build=true' >> "${GITHUB_ENV}";
             elif [[ -s "${project_log}" ]] && [[ "${PIPESTATUS[0]}" == 0 ]]; then
-              echo -e '\n|RUNTIME|\n' | process_input;
+              # echo -e '\n|RUNTIME|\n' | process_input;
               echo -e "::notice::No errors found checking project files" | process_input;
               check_build=true
               echo 'check_build=true' >> "${GITHUB_ENV}";
@@ -621,24 +617,18 @@ runs:
             source ~/codechecker/venv/bin/activate
             export PATH=~/codechecker/build/CodeChecker/bin:$PATH
             if ${{ inputs.build }}; then
-              { \
-                time \
-                  CodeChecker check -b "cmake clean && cmake" -o ./results | process_input \
-                  CodeChecker server | process_input \
-                  CodeChecker store ./results -n "${repository}" | process_input;
-              } 2>&1;
+              CodeChecker check -b "cmake clean && cmake" -o ./results | process_input;
+              CodeChecker server | process_input;
+              CodeChecker store ./results -n "${repository}" | process_input;
             else
               [[ -e 'compile_commands.json' ]] && rm -vf compile_commands.json | process_input;
-              { \
-                time \
-                  CodeChecker log --build "make" --output ./compile_commands.json | process_input \
-                  CodeChecker analyze ./compile_commands.json --enable sensitive --output ./reports | process_input \
-                  CodeChecker fixit --checker-name bugprone-suspicious-string-compare --apply ./reports | process_input;
-               } 2>&1;
+              CodeChecker log --build "make" --output ./compile_commands.json | process_input;
+              CodeChecker analyze ./compile_commands.json --enable sensitive --output ./reports | process_input;
+              CodeChecker fixit --checker-name bugprone-suspicious-string-compare --apply ./reports | process_input;
               [[ -e 'compile_commands.json' ]] && cp -vf compile_commands.json ./build | process_input;
             fi;
-            if [[ "${PIPESTATUS[1]}" == 0 ]]; then
-              echo -e '\n|RUNTIME|\n' | process_input;
+            if [[ "${PIPESTATUS[0]}" == 0 ]]; then
+              # echo -e '\n|RUNTIME|\n' | process_input;
               check_build=true
               echo 'check_build=true' >> "${GITHUB_ENV}";
             else
