Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -130,17 +130,22 @@ runs:
         fi;
 
         if [[ ! -n $(dpkg -s build-essential 2>/dev/null) ]] && ${{ inputs.project }}; then
-          sudo apt-get -yq install build-essential device-tree-compiler >/dev/null && echo -e "\n####################\nbuild-essential dependencies Installed\n####################\n" || echo 'No build-essential installed for use by cmake';
+          sudo apt-get -yq install build-essential device-tree-compiler >/dev/null && echo -e "\n####################\nbuild-essential dependencies Installed\n####################\n" || echo 'No build-essential installed for project build';
+        fi;
+
+        if [[ ! $(which ninja) ]]; then
+          sudo apt-get install ninja-build >/dev/null && echo -e "\n####################\nninja dependencies Installed\n####################\n" || echo 'No ninja installed for project build';
+          [[ ! $(which ninja) ]] && exit 1
+        fi;
+
+        if [[ ! $(which cmake) ]] && ${{ inputs.project }}; then
+          sudo apt-get -yq install cmake >/dev/null >/dev/null && echo -e "\n####################\ncmake dependencies Installed\n####################\n" || echo 'No cmake installed for project build';
+          [[ ! $(which cmake) ]] && exit 1
         fi;
 
         if [[ ! $(which npm) ]]; then
           sudo npm install >/dev/null && echo -e "\n####################\nnpm dependencies Installed\n####################\n" || echo 'No npm installed for term_width';
           [[ ! $(which tput) ]] && exit 1
-        fi;
-
-        if [[ ! $(which cmake) ]] && ${{ inputs.project }}; then
-          sudo apt-get -yq install cmake >/dev/null >/dev/null && echo -e "\n####################\ncmake dependencies Installed\n####################\n" || echo 'No cmake installed for term_width';
-          [[ ! $(which cmake) ]] && exit 1
         fi;
 
         if [[ ! $(which tput) ]]; then
@@ -1200,8 +1205,12 @@ runs:
         repository=$(sudo find ${GITHUB_WORKSPACE} -type d -name ".git" -print -quit);
         if [[ -d ${repository} ]]; then
           cd "${repository%/*}";
-          cmake .
-          build=$(time -p cmake --build . |& tee -a "${GITHUB_WORKSPACE}/$(echo ${{ github.repository }} | sed 's/[\/\$]//g')_build.log" || echo "Error building repository project");
+          mkdir build
+          cd build
+          cmake ..
+          cmake --build .
+          #clang-tidy-11 -format-style=file -header-filter=. -p build
+          build=$(time -p cmake -G Ninja -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON |& tee -a "${GITHUB_WORKSPACE}/$(echo ${{ github.repository }} | sed 's/[\/\$]//g')_build.log" || echo "Error building repository project");
           if [[ -n ${build} ]]; then
             echo "file_fixed=1" >> "${GITHUB_ENV}";
           fi;
