Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -241,29 +241,17 @@ runs:
           sudo apt-get -yq install python3 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\npython3 dependencies Installed\n####################" || echo -e '::error::No python3 installed for project checks';
           [[ ! $(which python3) ]] && exit 1
         fi;
-        if ${{ inputs.project }} && ${{ inputs.analyzer == '3' }} && [[ ! $(which clangd-tidy) ]]; then
-          python3 -m pip install clangd-tidy >/dev/null && echo -e "\n####################\nclangd-tidy dependencies Installed\n####################\n" || echo -e '::error::No clangd-tidy installed for project checks';
-          if [[ $(which clangd-tidy) ]]; then
-            echo -e "\nclangd-tidy path: $(which clangd-tidy)\n";
-          else
-            exit 1
-          fi;
-        fi;
-        if ${{ inputs.project }} && [[ ! $(which clangd) ]]; then
-          sudo apt-get -yq install clangd 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\nclangd dependencies Installed\n####################" || echo -e '::error::No clangd installed for project build';
-          [[ ! $(which clangd) ]] && exit 1
-        fi;
         if ${{ inputs.project }} && [[ ! $(llvm-config --version 2>/dev/null) ]]; then
           echo '';
           sudo bash -c "$(sudo wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - >/dev/null 2>&1)"
           sudo bash -c "$(sudo wget -qO - https://apt.llvm.org/llvm.sh | sudo bash -s -- 21 >/dev/null 2>&1)"
           sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs) main" >/dev/null;
-          sudo apt-get -yq install lld llvm llvm-dev liblldb-dev libclang-dev 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\nllvm tools dependencies Installed\n####################" || echo -e '::error::No llvm tools installed for project build';
+          sudo apt-get -yq install lld llvm llvm-dev liblldb-dev libclang-dev 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\nllvm tools dependencies Installed\n####################\n" || echo -e '::error::No llvm tools installed for project build';
           sudo apt-get remove --purge -yq clang-tidy >/dev/null;
           [[ $(which clang-tidy) ]] && sudo rm -vf "$(which clang-tidy)" && echo '';
-          [[ $(which run-clang-tidy) ]] && sudo rm -vf "$(which run-clang-tidy)" && echo '';
-          python3 -m pip install clang-tools >/dev/null && clang-tools --install latest --directory /usr/local/bin >/dev/null && echo -e "####################\nclang tools pip dependencies Installed\n####################" || echo -e '::error::No clang tools installed for project check'; # Adjust directory as needed
-          sudo cp -vpf "${HOME}/.local/bin/clang-tidy" '/usr/local/bin/'
+          [[ $(which run-clang-tidy) ]] && sudo rm -vf "$(which run-clang-tidy)";
+          python3 -m pip install clang-tools >/dev/null && clang-tools --install latest --directory /usr/bin >/dev/null && echo -e "\n####################\nclang tools pip dependencies Installed\n####################\n" || echo -e '::error::No clang tools installed for project check'; # Adjust directory as needed
+          sudo cp -vpf "${HOME}/.local/bin/clang-tidy" '/usr/bin/' && sudo cp -vpf "${HOME}/.local/bin/run-clang-tidy" '/usr/bin/'
           [[ ! $(llvm-config --version 2>/dev/null) ]] && exit 1
         fi;
         if (${{ inputs.project }} || [[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]]) && [[ ! $(which clang-tidy) ]]; then
@@ -276,6 +264,18 @@ runs:
         elif ${{ inputs.analyzer == '1' }} && ${{ inputs.project }}; then
           echo -e "\n[clang-tools] run-clang-tidy: /scripts/tools/run-clang-tidy.py";
           echo "run_clang_tidy=${{ github.action_path }}/scripts/tools/run-clang-tidy.py" >> "${GITHUB_ENV}";
+        fi;
+        if ${{ inputs.project }} && ${{ inputs.analyzer == '3' }} && [[ ! $(which clangd-tidy) ]]; then
+          python3 -m pip install clangd-tidy >/dev/null && echo -e "\n####################\nclangd-tidy dependencies Installed\n####################" || echo -e '::error::No clangd-tidy installed for project checks';
+          if [[ $(which clangd-tidy) ]]; then
+            echo -e "\nclangd-tidy path: $(which clangd-tidy)\n";
+          else
+            exit 1
+          fi;
+        fi;
+        if ${{ inputs.project }} && [[ ! $(which clangd) ]]; then
+          sudo apt-get -yq install clangd 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\nclangd dependencies Installed\n####################" || echo -e '::error::No clangd installed for project build';
+          [[ ! $(which clangd) ]] && exit 1
         fi;
         if (${{ inputs.analyzer == '4' }} || ${{ inputs.build == '1' }} || ${{ inputs.build == '2' }}) && [[ ! $(which CodeChecker) ]]; then
           sudo apt-get -yq install python3-pip python3-venv make 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "\n####################\npython3-pip dependencies Installed\n####################" || echo -e '::error::No python3-pip installed for project checks';
