Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -564,21 +564,28 @@ runs:
           echo -e "\n####################\nChecking Repository ${src_tree%/*}\n####################\n" | process_input;
           echo -e "\n####################\nChecking for ${file_type} file(s)\n####################\n" | process_input;
           echo "repository=${repository}" >> "${GITHUB_ENV}";
-          src_dirs() {
+          source_dirs() {
             find -not \( -path "*/.github" -prune -o -path "*/.git" -prune \) -type d -maxdepth 1 -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r dir; do
               if [[ "${dir}" != '.' ]]; then
                 echo -n "${dir#./} "
               fi;
             done;
           }
-          includes() {
-            find "${src_tree%/*}" -not \( -path "*/.github" -prune -o -path "*/.git" -prune \) -type d -name 'include' -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r dir; do
-              if [[ -d "${dir}" ]]; then
-                echo -n "${dir} "
-              fi;
+          header1_list() {
+            find "${src_tree%/*}" -not \( -path "*/.github" -prune -o -path "*/.git" -prune \) -type f \( -name "*.h" -o -name "*.hh" -o -name "*.hxx" -o -name "*.hpp" \) -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r header; do
+              echo -n "${header%/*} " >> headers_input.txt
             done;
+            awk '!seen[$0]++' headers_input.txt > headers_output.txt 
+            cat headers_output.txt && rm headers_output.txt || echo 'file missing headers_output.txt'
           }
-          file_list() {
+          header2_list() {
+            find "${src_tree%/*}" -not \( -path "*/.github" -prune -o -path "*/.git" -prune \) -type f \( -name "*.h" -o -name "*.hh" -o -name "*.hxx" -o -name "*.hpp" \) -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r header; do
+              echo "-I${header%/*}" >> headers_input.txt
+            done;
+            awk '!seen[$0]++' headers_input.txt > headers_output.txt 
+            cat headers_output.txt && rm headers_output.txt || echo 'file missing headers_output.txt'
+          }
+          source_list() {
             find -not \( -path "*/CMakeFiles" -prune -o -path "*/build" -prune -o -path "*/.git" -prune -o -path "*/.github" -prune \) -type f -name "*.${file_type}" -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r file; do
               echo -e "${file#./}"
             done;
@@ -592,10 +599,10 @@ runs:
           mkdir -p build/fixes
           if [[ -d 'build' ]]; then
             echo -e '\n####################\n\tbuild directory created continuing...\n####################\n' | process_input;
-            if [[ "$(src_dirs)" ]] && [[ "$(includes)" ]]; then
-              cmake -S . -DPROJECT_SRC_INCLUDES="$(includes)" -DPROJECT_SRC_DIRS="$(src_dirs)" -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
-            elif [[ "$(src_dirs)" ]]; then
-              cmake -S . -DPROJECT_SRC_DIRS="$(src_dirs)" -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
+            if [[ "$(source_dirs)" ]] && [[ "$(header1_list)" ]]; then
+              cmake -S . -DPROJECT_SRC_INCLUDES="$(header1_list)" -DPROJECT_SRC_DIRS="$(source_dirs)" -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
+            elif [[ "$(source_dirs)" ]]; then
+              cmake -S . -DPROJECT_SRC_DIRS="$(source_dirs)" -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
             else
               cmake -S . -DGITHUB_PROJECT_NAME="${repository}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build | process_input || echo "::warning:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
             fi;
@@ -612,9 +619,15 @@ runs:
           if [[ -f "${clang_file}" ]] && ${{ env.analysis == 1 }}; then
             echo ' ' >> "${clang_file}";
             files_list=false
-            if [[ `file_list` ]]; then
+            if [[ `header2_list` ]] && [[ `source_list` ]] ; then
               echo -e "\n####################\n\t${file_type} file(s) found continuing...\n####################\n" | process_input;
-              file_list >> "${clang_file}";
+              source_list >> "${clang_file}";
+              echo '--' >> "${clang_file}";
+              header2_list >> "${clang_file}";
+              files_list=true
+            elif [[ `source_list` ]]; then
+              echo -e "\n####################\n\t${file_type} file(s) found continuing...\n####################\n" | process_input;
+              source_list >> "${clang_file}";
               files_list=true
             else	
               echo -e "\n::error::No ${file_type} files found searching repository\nExiting...\n" | process_input;
@@ -622,7 +635,7 @@ runs:
             echo -e "\n####################\n\t${clang_file} found continuing...\n####################\n" | process_input;
             echo -e '\n####################\nCLANG-TIDY CONFIG CHECKED\n####################\n' | process_input;
             if [[ "${files_list}" ]]; then
-              cp -vf "${clang_file}" 'build/cmake-source-files.txt' 2>/dev/null;
+              cp -vf "${clang_file}" 'build/check-source-files.txt' 2>/dev/null;
               echo -e '\n####################\nCLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
               { time clang-tidy @parameter-file | process_input; } 2>&1;
               if [[ -s "${project_log}" ]] && [[ $(grep -sE 'error|Error|ERROR' "${project_log}") ]]; then
