Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1274,20 +1274,20 @@ runs:
             echo ' ' >> "${clang_file}";
             if [[ "${file_list}" ]]; then
               echo -e "\n####################\n\t${file_type} file(s) found continuing...\n####################\n";
-              echo -e '\n--\n' >> "${clang_file}";
-              echo -e "\n${file_list}\n" >> "${clang_file}";
+              echo -e "${file_list}" >> "${clang_file}";
             else	
               echo -e "\nNo ${file_type} files found searching repository\nExiting...\n";
               exit 1
             fi;
             if [[ -d "${included}" ]]; then
               echo -e '\n####################\n\tinclude directories found continuing...\n####################\n';
-              echo -e "\n${included//.\//}" >> "${clang_file}";
+              echo -e "-I${included//.\//}" >> "${clang_file}";
             fi;
             echo -e "\n####################\n\t${clang_file} found continuing...\n####################\n";
             echo -e '\n####################\nCLANG-TIDY ANALYZING CLANG PARAMS FILE\n####################\n';
-            { time -p clang-tidy @parameter-file && check_build=true; } 2>&1 | tee -a "${GITHUB_WORKSPACE}/${repository}_project.log" || echo "Error: ( $? ) checking project files";
+            { time -p clang-tidy @parameter-file; } 2>&1 | tee -a "${GITHUB_WORKSPACE}/${repository}_project.log" || echo "Error: ( $? ) checking project files";
             echo -e '\n|RUNTIME|';
+            check_build=true
           elif [[ ! -e "${clang_file}" ]] && ${{ inputs.analysis == 1 }} && ! ${{ inputs.build }}; then
             echo -e "\n####################\n\tparameter-file missing in repo Exiting...\n####################\n";
             exit 1
