Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -96,43 +96,43 @@ runs:
         sudo add-apt-repository ppa:git-core/ppa >/dev/null;
         sudo apt-get update -yq >/dev/null 2>&1;
 
-        if [[ ! $(which git) ]]; then
-          sudo apt-get -yq install git >/dev/null && echo -e "\n####################\n\t.Git dependencies Installed\n####################\n";
+        if [[ ! $(which git) ]] && ${{ inputs.update }}; then
+          sudo apt-get -yq install git >/dev/null && echo -e '\n####################\n\tgit dependencies Installed\n####################\n' || echo 'No .git found Exiting' && exit 1;
         fi;
 
-        if [[ ! $(which rg) ]]; then
-          sudo apt-get -yq install ripgrep >/dev/null && echo -e "\n####################\n\tRipgrep dependencies Installed\n####################\n";
+        if [[ ! $(which rg) ]] && ${{ inputs.database }}; then
+          sudo apt-get -yq install ripgrep >/dev/null && echo -e '\n####################\n\tripgrep dependencies Installed\n####################\n' || echo 'No ripgrep found Exiting' && exit 1;
         fi;
 
-        if [[ ! $(which ansi2txt) ]]; then
-          sudo apt-get -yq install ansi2txt >/dev/null && echo -e "\n####################\n\tAnsi2txt dependencies Installed\n####################\n";
+        if [[ ! $(which ansi2txt) ]] && ${{ inputs.report }}; then
+          sudo apt-get -yq install ansi2txt >/dev/null && echo -e '\n####################\n\tansi2txt dependencies Installed\n####################\n';
         fi;
 
         if [[ ! $(which update-ca-certificates) ]]; then
-          sudo apt-get -yq install ca-certificates >/dev/null && echo -e "\n####################\n\tCa-certificates dependencies Installed\n####################\n";
+          sudo apt-get -yq install ca-certificates >/dev/null && echo -e '\n####################\n\tca-certificates dependencies Installed\n####################\n';
         fi;
 
         if [[ ! $(which cppcheck) ]] && [[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]]; then
-          sudo apt-get -yq install cppcheck >/dev/null && echo -e "\n####################\n\tCppcheck dependencies Installed\n####################\n";
+          sudo apt-get -yq install cppcheck >/dev/null && echo -e '\n####################\n\tcppcheck dependencies Installed\n####################\n' || echo 'No cppcheck found Exiting' && exit 1;
         fi;
 
-        if [[ ! $(which clang-tidy) ]] && [[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]]; then
-          sudo apt-get -yq install clang-tidy clang-format >/dev/null && echo -e "\n####################\n\Clang-tool dependencies Installed\n####################\n";
+        if [[ ! $(which clang-tidy) ]] && [[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]] && ${{ inputs.repair }}; then
+          sudo apt-get -yq install clang-tidy clang-format >/dev/null && echo -e '\n####################\n\clang-tidy dependencies Installed\n####################\n' || echo 'No clang-tidy found Exiting' && exit 1;
         fi;
 
-        if [[ ! $(which shellharden) ]] && [[ -n $(echo "${file_type}" | egrep -i "^sh$") ]]; then
-          wget -qO shellharden.tar.gz https://github.com/anordal/shellharden/releases/latest/download/shellharden-x86_64-unknown-linux-gnu.tar.gz
-          sudo tar xf shellharden.tar.gz -C /usr/local/bin shellharden && rm -vrf shellharden.tar.gz && echo -e "\n####################\n\tShellharden dependencies Installed\n####################\n";
+        if [[ ! $(which shellharden) ]] && [[ -n $(echo "${file_type}" | egrep -i "^sh$") ]] && ${{ inputs.repair }}; then
+          wget -qO 'shellharden.tar.gz' 'https://github.com/anordal/shellharden/releases/latest/download/shellharden-x86_64-unknown-linux-gnu.tar.gz';
+          sudo tar xf 'shellharden.tar.gz' -C '/usr/local/bin' 'shellharden' && rm -vrf 'shellharden.tar.gz' && echo -e '\n####################\n\tshellharden dependencies Installed\n####################\n' || echo 'No shellharden found Exiting' && exit 1;
         fi;
 
-        if [[ ! $(which shellcheck) ]] && [[ -n $(echo "${file_type}" | egrep -i "^sh$") ]]; then
-          sudo apt-get -yq install shellcheck >/dev/null && echo -e "\n####################\n\tShellcheck dependencies Installed\n####################\n";
+        if [[ ! $(which shellcheck) ]] && [[ -n $(echo "${file_type}" | egrep -i "^sh$") ]] && ${{ inputs.recheck }} || ! ${{ inputs.repair }}; then
+          sudo apt-get -yq install shellcheck >/dev/null && echo -e '\n####################\n\tshellcheck dependencies Installed\n####################\n' || echo 'No shellcheck found Exiting' && exit 1;
         fi;
 
         if [[ ! $(which checkmake) ]] && [[ -n $(echo "${file_type}" | egrep -i "^mk$|.*Makefile$") ]]; then
-          go install "github.com/checkmake/checkmake/cmd/checkmake@latest" >/dev/null && echo -e "\n####################\n\tCheckmake dependencies Installed\n####################\n";     
+          go install "github.com/checkmake/checkmake/cmd/checkmake@latest" >/dev/null && echo -e '\n####################\n\tcheckmake dependencies Installed\n####################\n' || echo 'No checkmake found Exiting' && exit 1;    
           if [[ -n ${file} ]]; then
-            echo -e "\n####################\n\tcheckmake.ini found copying...\n####################\n";
+            echo -e '\n####################\n\tcheckmake.ini found copying...\n####################\n';
             sudo cp -vf "${file}" "${path}" 2>/dev/null;
           fi;
         elif [[ -n ${file} ]] && [[ -n $(echo "${file_type}" | egrep -i "^mk$|.*Makefile$") ]]; then
@@ -141,12 +141,11 @@ runs:
 
         if [[ $(which bat) ]] && [[ ! $(which batcat) ]]; then
           sudo ln -sf ~/usr/bin/bat ~/usr/bin/batcat >/dev/null 2>&1;
-          echo "########## $(which batcat) ##########" || echo "No batcat found Exiting... $(exit 1)";
-          sudo bash -c echo -e "\nalias batcat='bat'" >> ~/.bashrc 2>/dev/null;
+          echo "########## $(which batcat) ##########" || echo 'No batcat found Exiting' && exit 1;
+          sudo bash -c echo -e "\nalias batcat='bat'" | sudo tee -a ~/.bashrc 2>/dev/null;
           export BAT_THEME="ansi";
         elif [[ ! $(which batcat) ]]; then
-          sudo apt-get -yq install bat >/dev/null && echo -e "\n####################\n\tBatcat dependencies Installed\n####################\n";
-          echo "########## $(which batcat) ##########" || echo "No batcat found Exiting... $(exit 1)";
+          sudo apt-get -yq install bat >/dev/null && echo -e '\n####################\n\tbatcat dependencies Installed\n####################\n' || echo 'No batcat found Exiting' && exit 1;
           export BAT_THEME="ansi";
         fi;
 
@@ -166,12 +165,12 @@ runs:
         repository=$(sudo find ${GITHUB_WORKSPACE} -type d -name '.git' -print -quit);
         
         if ${{ inputs.rootdir }}; then
-          echo -e "\n####################\nDEFAULT DIRECTORY (SYSTEM ROOT)\n####################\n";
-          echo -e "\n ~/\n";
-          echo "FILE_PATH=/" >> "${GITHUB_ENV}";
+          echo -e '\n####################\nDEFAULT DIRECTORY (SYSTEM ROOT)\n####################\n';
+          echo -e '\n~/\n';
+          echo 'FILE_PATH=/' >> "${GITHUB_ENV}";
           FILE_PATH=/
         else
-          echo -e "\n####################\nDEFAULT DIRECTORY (GITHUB WORKSPACE)\n####################\n";
+          echo -e '\n####################\nDEFAULT DIRECTORY (GITHUB WORKSPACE)\n####################\n';
           echo -e "\n${GITHUB_WORKSPACE}\n";
           echo "FILE_PATH=${GITHUB_WORKSPACE}" >> "${GITHUB_ENV}";
           FILE_PATH=${GITHUB_WORKSPACE}
@@ -180,20 +179,20 @@ runs:
         if [[ -d ${repository} ]] && ${{ inputs.repair }}; then
           repository="${repository%/*}/${repair_file}";
           if [[ -f ${repository} ]]; then
-            echo -e "\n####################\nRepaired files list found!!!\n####################\n";
+            echo -e '\n####################\nRepaired files list found!!!\n####################\n';
           else
             echo -e "\nCreating ${repair_file} for checked files\n"
-            date "+%Y%m%d" > "${repository}" || exit 1
+            date '+%Y%m%d' > "${repository}" || exit 1
           fi;
         fi;
 
         if ${{ inputs.database }}; then
           sudo find "${FILE_PATH}" -name "*" -print > "${GITHUB_WORKSPACE}/check_file_list.txt";
           if [[ -f "${GITHUB_WORKSPACE}/check_file_list.txt" ]]; then
-            echo -e "\n####################\ncheck_file_list database found\n####################\n";
+            echo -e '\n####################\ncheck_file_list database found\n####################\n';
             echo "DATABASE=${GITHUB_WORKSPACE}/check_file_list.txt" >> "${GITHUB_ENV}";
           else
-            echo 'Database check_file_list.txt not found exiting..' && exit 1
+            echo -e '\nDatabase check_file_list.txt not found exiting..' && exit 1
           fi;
         fi;
 
@@ -216,9 +215,10 @@ runs:
         else
           echo "dirname=${{ inputs.dirname }}" >> "$GITHUB_OUTPUT";
         fi;
-        echo "FILE_FIXED=0" >> "${GITHUB_ENV}";
-        echo "FILE_FOUND=0" >> "${GITHUB_ENV}";
-        echo "FILE_ERROR=0" >> "${GITHUB_ENV}";
+        echo 'FILE_FIXED=0' >> "${GITHUB_ENV}";
+        echo 'FILE_FOUND=0' >> "${GITHUB_ENV}";
+        echo 'FILE_ERROR=0' >> "${GITHUB_ENV}";
+        echo -e '\n●●●●●●●●●●●●●●\n SETUP COMPLETED \n●●●●●●●●●●●●●●\n';
       shell: bash
       continue-on-error: false
 
