Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -283,14 +283,14 @@ runs:
           [[ ! $(which deheader) ]] && exit 1
         fi;
         if [[ ! $(dpkg -s build-essential 2>/dev/null) ]] && ${{ inputs.project }}; then
-          sudo apt-get -yq install build-essential device-tree-compiler >/dev/null | sed -E "s/.*${end_pattern##.}\. //" && echo -e "\n####################\nbuild-essential dependencies Installed\n####################\n" || echo -e '::error::No build-essential installed for project build';
+          sudo apt-get -yq install build-essential device-tree-compiler | sed -E "s/.*${end_pattern##.}\. //" && echo -e "\n####################\nbuild-essential dependencies Installed\n####################\n" || echo -e '::error::No build-essential installed for project build';
         fi;
         if [[ ! $(which npm) ]]; then
-          sudo apt-get -yq install npm >/dev/null | sed -E "s/.*${end_pattern##.}\. //" && echo -e "\n####################\nnpm dependencies Installed\n####################\n" || echo -e '::error::No npm installed for term_width';
+          sudo apt-get -yq install npm | sed -E "s/.*${end_pattern##.}\. //" && echo -e "\n####################\nnpm dependencies Installed\n####################\n" || echo -e '::error::No npm installed for term_width';
           [[ ! $(which npm) ]] && exit 1
         fi;
         if [[ ! $(which tput) ]]; then
-          sudo apt-get -yq install tput >/dev/null | sed -E "s/.*${end_pattern##.}\. //" && echo -e "\n####################\ntput dependencies Installed\n####################\n" || echo -e '::error::No tput installed for term_width';
+          sudo apt-get -yq install tput | sed -E "s/.*${end_pattern##.}\. //" && echo -e "\n####################\ntput dependencies Installed\n####################\n" || echo -e '::error::No tput installed for term_width';
           [[ ! $(which tput) ]] && exit 1
         fi;
         if [[ ! $(which tqdm) ]] && ${{ inputs.project }} && ${{ inputs.analyzer == 3 }}; then
@@ -298,17 +298,17 @@ runs:
           [[ ! $(which tqdm) ]] && exit 1
         fi;
         if [[ ! $(which rg) ]] && [[ "${{ inputs.pattern }}" != '' ]] && ${{ inputs.database }}; then
-          sudo apt-get -yq install ripgrep >/dev/null | sed -E "s/.*${end_pattern##.}\. //" && echo -e "${text1}" || echo -e '::error::No ripgrep installed for pattern matching';
+          sudo apt-get -yq install ripgrep | sed -E "s/.*${end_pattern##.}\. //" && echo -e "${text1}" || echo -e '::error::No ripgrep installed for pattern matching';
           [[ ! $(which rg) ]] && exit 1
         fi;
         if [[ ! $(which ansi2txt) ]] && ${{ inputs.report }}; then
-          sudo apt-get -yq install ansi2txt >/dev/null | sed -E "s/.*${end_pattern##.}\. //" && echo -e "${text2}" || echo -e '::error::No ansi2txt installed for cleaning log report';
+          sudo apt-get -yq install ansi2txt | sed -E "s/.*${end_pattern##.}\. //" && echo -e "${text2}" || echo -e '::error::No ansi2txt installed for cleaning log report';
         fi;
         if [[ ! $(which update-ca-certificates) ]]; then
-          sudo apt-get -yq install ca-certificates >/dev/null | sed -E "s/.*${end_pattern##.}\. //" && echo -e "${text3}" || echo 'No ca-certificates installed effects can vary';
+          sudo apt-get -yq install ca-certificates | sed -E "s/.*${end_pattern##.}\. //" && echo -e "${text3}" || echo 'No ca-certificates installed effects can vary';
         fi;
         if [[ ! $(which cppcheck) ]] && [[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]]; then
-          sudo apt-get -yq install cppcheck >/dev/null | sed -E "s/.*${end_pattern##.}\. //" && echo -e "${text4}" || echo -e '::error::No cppcheck installed Exiting';
+          sudo apt-get -yq install cppcheck | sed -E "s/.*${end_pattern##.}\. //" && echo -e "${text4}" || echo -e '::error::No cppcheck installed Exiting';
           [[ ! $(which cppcheck) ]] && exit 1
         fi;
         if [[ ! $(which shellharden) ]] && [[ -n $(echo "${file_type}" | egrep -i "^sh$") ]] && ${{ inputs.repair }}; then
@@ -317,7 +317,7 @@ runs:
           [[ ! $(which shellharden) ]] && exit 1
         fi;
         if [[ ! $(which shellcheck) ]] && [[ -n $(echo "${file_type}" | egrep -i "^sh$") ]]; then
-          sudo apt-get -yq install shellcheck >/dev/null | sed -E "s/.*${end_pattern##.}\. //" && echo -e "${text7}" || echo -e '::error::No shellcheck installed Exiting';
+          sudo apt-get -yq install shellcheck | sed -E "s/.*${end_pattern##.}\. //" && echo -e "${text7}" || echo -e '::error::No shellcheck installed Exiting';
           [[ ! $(which shellcheck) ]] && exit 1
         fi;
         if [[ $(which checkmake) ]] && [[ -n ${file} ]] && [[ -n $(echo "${file_type}" | egrep -i "^mk$|.*Makefile$") ]]; then
@@ -336,7 +336,7 @@ runs:
           echo -e "\nalias batcat='bat'" | sudo tee -a ~/.bashrc >/dev/null;
           export BAT_THEME="ansi";
         elif [[ ! $(which batcat) ]]; then
-          sudo apt-get -yq install bat >/dev/null | sed -E "s/.*${end_pattern##.}\. //" && echo -e "${text9}" || echo -e '::error::No batcat installed Exiting';
+          sudo apt-get -yq install bat | sed -E "s/.*${end_pattern##.}\. //" && echo -e "${text9}" || echo -e '::error::No batcat installed Exiting';
           [[ ! $(which batcat) ]] && exit 1
           export BAT_THEME="ansi";
         fi;
@@ -357,7 +357,7 @@ runs:
         repair_file='check-file-repaired.txt';
         repository=$(sudo find ${GITHUB_WORKSPACE} -type d -name '.git' -print -quit);
         repo=$(echo ${{ github.repository }} | cut -d'/' -f 2-);
-        chmod -R 0755 "${{ github.action_path }}/scripts/*";
+        chmod -R 0755 "${{ github.action_path }}/scripts";
         echo 'database=database' >> "${GITHUB_ENV}";
         text1a="####################";
         text1b="DEFAULT DIRECTORY (SYSTEM ROOT)";
