Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -398,7 +398,7 @@ runs:
         export LLVM_ENABLE_THREADS=ON
         export CMAKE_EXPORT_COMPILE_COMMANDS=ON
         export LC_ALL=C
-        set -o pipefail
+        set +e
         compiler_list=$(dpkg --list | grep compiler | tr -d 'ii');
         clang_version=$(clang --version);
         verify_config=$(clang-tidy --verify-config 2>/dev/null);
@@ -737,7 +737,7 @@ runs:
                   echo -e "\n####################\nChecked on ${check_date}\nSkipping $(basename ${file})\n####################\n" | process_input;
                 elif ${{ inputs.stored }} && ${{ env.update }}; then
                   echo -e "\n\n####################\nCLANG-TIDY FILES ANALYZER (${count1})\n####################\n\n" | process_input;
-                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes --quiet 2>/dev/null | process_input || echo -e "::error:: ( $? ) Broken pipe check. PipeStatus [0]: ${PIPESTATUS[0]}, PipeStatus [1]: ${PIPESTATUS[1]}" | process_input;
+                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>/dev/null | process_input || echo -e "::error:: ( $? ) Broken pipe check. PipeStatus [0]: ${PIPESTATUS[0]}, PipeStatus [1]: ${PIPESTATUS[1]}" | process_input;
                   if [[ -s "${error_log}" ]] && [[ ! $(grep -sE "${file}.*error:" "${error_log}") ]]; then
                     echo -e "\n####################\nSTORING NO ERRORS FOUND\n####################\n\n${file}\n" | process_input;
                   else
@@ -748,7 +748,7 @@ runs:
                   fixed=true
                 elif ! ${{ inputs.stored }} || ! ${{ env.update }}; then
                   echo -e "\n\n####################\nCLANG-TIDY FILES ANALYZER (${count1})\n####################\n\n" | process_input;
-                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes --quiet 2>/dev/null | process_input || echo -e "::error:: ( $? ) Broken pipe check. PipeStatus [0]: ${PIPESTATUS[0]}, PipeStatus [1]: ${PIPESTATUS[1]}" | process_input;
+                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>/dev/null | process_input || echo -e "::error:: ( $? ) Broken pipe check. PipeStatus [0]: ${PIPESTATUS[0]}, PipeStatus [1]: ${PIPESTATUS[1]}" | process_input;
                   if [[ -s "${error_log}" ]] && [[ ! $(grep -sE "${file}.*error:" "${error_log}") ]]; then
                     echo -e "\n####################\nCHECK-FILE NO ERRORS FOUND ${file}\n####################\n" | process_input;
                   else
@@ -759,11 +759,13 @@ runs:
                 fi;
               else
                 echo -e "\n\n####################\nCPPCHECK FILE ANALYZER (${count1})\n####################\n\n" | process_input;
-                if ${{ inputs.stored }}; then
+                if ${{ inputs.project }} && ${{ inputs.stored }}; then
                   cppcheck -j "$(nproc --all)" --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress=missingInclude --suppress=missingIncludeSystem --suppress=unmatchedSuppression:"{}" --cppcheck-build-dir="${build_cache}" --project="${compile_json}" "${file}" 2>/dev/null | process_input || echo -e "::error:: ( $? ) Broken pipe check. PipeStatus [0]: ${PIPESTATUS[0]}, PipeStatus [1]: ${PIPESTATUS[1]}" | process_input;
                   echo 'build_cache=true' >> "${GITHUB_ENV}";
-                else
+                elif ${{ inputs.project }}; then
                   cppcheck --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress=missingInclude --suppress=missingIncludeSystem --suppress=unmatchedSuppression:"{}" --project="${compile_json}" "${file}" 2>/dev/null | process_input || echo -e "::error:: ( $? ) Broken pipe check. PipeStatus [0]: ${PIPESTATUS[0]}, PipeStatus [1]: ${PIPESTATUS[1]}" | process_input;
+                else
+                  cppcheck --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress="*" "${file}" 2>/dev/null | process_input || echo -e "::error:: ( $? ) Broken pipe check. PipeStatus [0]: ${PIPESTATUS[0]}, PipeStatus [1]: ${PIPESTATUS[1]}" | process_input;
                 fi;
                 if [[ -s "${error_log}" ]] && [[ ! $(grep -sE "${file}.*error:" "${error_log}") ]]; then
                   echo -e "\n####################\nCHECK-FILE NO ERRORS FOUND ${file}\n####################\n" | process_input;
@@ -794,7 +796,7 @@ runs:
             echo -e "\n::notice:: Total number of include file(s) was: ${count3}\n" | process_input;
           fi;
           echo -e "\n::notice:: Total number of ${{ inputs.filename }} file(s) checked is: ${count1}\n" | process_input;
-          echo -e "Scanning Completed!\nCheck-file Exiting!\n .....\n" | process_input;
+          echo -e "Scanning Completed!\nCheck-File Exiting!\n .....\n" | process_input;
           echo "file_found=1" >> "${GITHUB_ENV}";
           if [[ "${errors}" ]]; then
             echo "file_error=1" >> "${GITHUB_ENV}";
@@ -924,7 +926,7 @@ runs:
             fi;
           done; echo '| Runtime |'; } 2>&1
           echo -e "\n::notice:: Total number of ${{ inputs.filename }} file(s) checked is: ${count3}\n" | process_input;
-          echo -e "Scanning Completed!\nShellTools Exiting!\n .....\n" | process_input;
+          echo -e "Scanning Completed!\nCheck-File Exiting!\n .....\n" | process_input;
           echo "file_found=1" >> "${GITHUB_ENV}";
           if [[ "${errors}" ]]; then
             echo "file_error=1" >> "${GITHUB_ENV}";
@@ -1005,7 +1007,7 @@ runs:
             fi;
           done; echo '| Runtime |'; } 2>&1
           echo -e "\n::notice:: Total number of ${{ inputs.filename }} file(s) checked is: ${count4}\n" | process_input;
-          echo -e "Scanning Completed!\nCheckMake Exiting!\n .....\n" | process_input;
+          echo -e "Scanning Completed!\nCheck-File Exiting!\n .....\n" | process_input;
           if [[ "${errors}" ]]; then
             echo "file_error=1" >> "${GITHUB_ENV}";
           fi;
@@ -1057,7 +1059,7 @@ runs:
             fi;
           done; echo '| Runtime |'; } 2>&1
           echo -e "\n::notice:: Total number of ${{ inputs.filename }} file(s) checked is: ${count5}\n";
-          echo -e "Scanning Completed!\nCheckfile Exiting!\n .....\n";
+          echo -e "Scanning Completed!\nCheck-File Exiting!\n .....\n";
           echo "file_found=1" >> "${GITHUB_ENV}";
         else
           echo -e "\n####################\nFINISHED SEARCHING ALL FILES\nNO $(echo ${{ inputs.filename }} | sed 's/[\/\$]//g') FOUND\n####################\n";
@@ -1153,7 +1155,7 @@ runs:
       run: |
         echo '';
         set +e
-        min_size_bytes=$((25 * 1024 * 1024));
+        min_size_bytes=$((10 * 1024 * 1024));
         filename1="${GITHUB_WORKSPACE}/${{ env.repository }}_project.log";
         filename2="${GITHUB_WORKSPACE}/${{ inputs.filename }}_error.log";
         if [[ -s "${filename1}" ]]; then
