Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -183,6 +183,11 @@ inputs:
     type: number
     required: false
     default: 150
+  linux:
+    description: 'Linux project builds not android'
+    type: boolean
+    required: false
+    default: true
   arch:
     description: 'Arch to set for checking kernel project includes'
     type: string
@@ -334,17 +339,47 @@ runs: # Uses default x86_64 / linux user machine
         fi;
         AUTO_ARCH="${TARGET_ARCH}";
         COMPILERS='clang:clang++:gcc:g++:cc:c++';
-        if [[ "${arch}" == 'arm' ]]; then
-          AUTO_ARCH="${TARGET_ARCH:-arm-none-eabi}";
-          COMPILERS='gcc:g++:arm-linux-androideabi-gcc:arm-linux-androideabi-g++';
-        elif [[ "${arch}" == 'arm64' || "${arch}" == 'aarch64' ]]; then
-          AUTO_ARCH="${TARGET_ARCH:-aarch64-linux-android}";
-          COMPILERS='gcc:g++:aarch64-linux-android-gcc:aarch64-linux-android-g++';
-        elif [[ "${arch}" == 'x86_64' ]]; then
-          AUTO_ARCH="${TARGET_ARCH:-x86_64-pc-linux-gnu}";
-          COMPILERS='gcc:g++:cc:c++';
+        if ${{ inputs.linux == 'false' }}; then
+          if [[ "${arch}" == 'arm' || "${arch}" == 'aarch32' || "${arch}" == 'armv7'* || "${arch}" == 'armeabi'* ]]; then
+          # Use androideabi for Android; use arm-none-eabi ONLY for bare-metal
+            AUTO_ARCH="${TARGET_ARCH:-arm-linux-androideabi}";
+            COMPILERS='gcc:g++:arm-linux-androideabi-gcc:arm-linux-androideabi-g++';
+          elif [[ "${arch}" == 'arm64' || "${arch}" == 'aarch64' || "${arch}" == 'armv8'* || "${arch}" == 'armeabi-v8a' ]]; then
+            AUTO_ARCH="${TARGET_ARCH:-aarch64-linux-android}";
+            COMPILERS='gcc:g++:aarch64-linux-android-gcc:aarch64-linux-android-g++';
+          elif [[ "${arch}" == 'x86_64' ]]; then
+          # Use -linux-android for Android, -pc-linux-gnu for Desktop Linux
+            AUTO_ARCH="${TARGET_ARCH:-x86_64-linux-android}";
+            COMPILERS='gcc:g++:x86_64-linux-android-gcc:x86_64-linux-android-g++';
+          elif [[ "${arch}" == 'x86' || "${arch}" == 'i686' || "${arch}" == 'i386' ]]; then
+            AUTO_ARCH="${TARGET_ARCH:-i686-linux-android}";
+            COMPILERS='gcc:g++:i686-linux-android-gcc:i686-linux-android-g++';
+          fi;
+        else
+          if [[ "${arch}" == 'arm' || "${arch}" == 'armv7'* || "${arch}" == 'armhf' ]]; then
+          # Standard 32-bit ARM (Hard Float is common for PC/SBC)
+            AUTO_ARCH="${TARGET_ARCH:-arm-linux-gnueabihf}";
+            K_ARCH="arm";
+            COMPILERS='gcc:g++:arm-linux-gnueabihf-gcc:arm-linux-gnueabihf-g++';
+          elif [[ "${arch}" == 'arm64' || "${arch}" == 'aarch64' || "${arch}" == 'armv8'* ]]; then
+          # 64-bit ARM (Server/PC)
+            AUTO_ARCH="${TARGET_ARCH:-aarch64-linux-gnu}";
+            K_ARCH="arm64";
+           COMPILERS='gcc:g++:aarch64-linux-gnu-gcc:aarch64-linux-gnu-g++';
+          elif [[ "${arch}" == 'x86_64' || "${arch}" == 'amd64' ]]; then
+          # Standard 64-bit PC
+            AUTO_ARCH="${TARGET_ARCH:-x86_64-linux-gnu}";
+            K_ARCH="x86";
+            COMPILERS='gcc:g++:cc:c++';
+          elif [[ "${arch}" == 'i686' || "${arch}" == 'i386' || "${arch}" == 'x86' ]]; then
+          # 32-bit PC
+            AUTO_ARCH="${TARGET_ARCH:-i686-linux-gnu}";
+            K_ARCH="x86";
+            COMPILERS='gcc:g++:cc:c++';
+          fi;
         fi;
-        echo "BACKUP_PATH=$PATH" >> "${GITHUB_ENV}"
+        echo "BACKUP_PATH=$PATH" >> "${GITHUB_ENV}";
+        echo "K_ARCH=${K_ARCH}" >> "${GITHUB_ENV}";
         echo "TARGET_ARCH=${AUTO_ARCH}" >> "${GITHUB_ENV}";
         echo "CC_LOGGER_GCC_LIKE=${COMPILERS}" >> "${GITHUB_ENV}";
         echo "release1=" >> "${GITHUB_ENV}";
@@ -367,6 +402,9 @@ runs: # Uses default x86_64 / linux user machine
         echo 'include_missing=false' >> "${GITHUB_ENV}";
         echo "update=${{ inputs.update }}" >> "${GITHUB_ENV}";
         echo "dirname=${{ inputs.dirname }}" >> "${GITHUB_ENV}";
+        echo "export K_ARCH=${K_ARCH}" | sudo tee -a ~/.bashrc >/dev/null;
+        echo "export TARGET_ARCH=${AUTO_ARCH}" | sudo tee -a ~/.bashrc >/dev/null;
+        echo "export CC_LOGGER_GCC_LIKE=${COMPILERS}" | sudo tee -a ~/.bashrc >/dev/null;
         echo 'export ALLOW_MISSING_DEPENDENCIES=true' | sudo tee -a ~/.bashrc >/dev/null;
         echo 'export GIT_DISCOVERY_ACROSS_FILESYSTEM=1' | sudo tee -a ~/.bashrc >/dev/null;
         echo 'export DEBIAN_FRONTEND=noninteractive' | sudo tee -a ~/.bashrc >/dev/null;
@@ -392,7 +430,7 @@ runs: # Uses default x86_64 / linux user machine
         sudo add-apt-repository -y restricted >/dev/null;
         sudo add-apt-repository -y multiverse >/dev/null;
         sudo apt-get -yq update 2>&1 >/dev/null | sed -E '/Running/,/host./d';
-        sudo apt-get -yq install aptitude 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "####################\naptitude dependencies installed\n####################\n" || echo -e '::error::No aptitude installer for installing packages';
+        sudo apt-get -yq install aptitude 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "\n####################\naptitude dependencies installed\n####################\n" || echo -e '::error::No aptitude installer for installing packages';
         echo 'deb [trusted=yes] https://apt.gabe565.com /' | sudo tee -a /etc/apt/sources.list.d/gabe565.list >/dev/null;
       shell: bash
       continue-on-error: false
@@ -459,15 +497,15 @@ runs: # Uses default x86_64 / linux user machine
         clang_tidy_required_version='21.1.6';
         cmake_required_version="4.2.1";
         if (${{ inputs.project == 'true' }} || [[ "${file_type}" == [cth]* ]]) && ([[ ! $(which clang-tidy) ]] || [[ $(printf '%s\n%s' "${clang_tidy_version}" "${clang_tidy_required_version}" | sort -V | head -n1) == "${clang_tidy_version}" ]] && [[ "${clang_tidy_version}" != "${clang_tidy_required_version}" ]]); then
-          python3 -m pip install --upgrade clang-tools >/dev/null && echo -e "\n####################\nclang tools pip dependencies installed\n####################\n" || echo -e '::error::No clang tools installed for project check';
-          [[ -e "${HOME}/.local/bin/clang-tidy" ]] && sudo mv -f "${HOME}/.local/bin/clang-tidy" '/usr/bin/clang-tidy' && echo '';
-          [[ -e "${HOME}/.local/bin/run-clang-tidy" ]] && sudo mv -f "${HOME}/.local/bin/run-clang-tidy" '/usr/bin/run-clang-tidy'
+          python3 -m pip install --upgrade clang-tools >/dev/null && echo -e "\n####################\nclang tools pip dependencies installed\n####################" || echo -e '::error::No clang tools installed for project check';
+          [[ -e "${HOME}/.local/bin/clang-tidy" ]] && sudo mv -f "${HOME}/.local/bin/clang-tidy" '/usr/bin/clang-tidy';
+          [[ -e "${HOME}/.local/bin/run-clang-tidy" ]] && sudo mv -f "${HOME}/.local/bin/run-clang-tidy" '/usr/bin/run-clang-tidy';
           [[ ! $(which clang-tidy) ]] && exit 1
         fi;
         [[ ! $(which make) ]] && sudo aptitude install -yq make >/dev/null && echo -e "\n####################\nmake dependencies installed\n####################";
         if ${{ inputs.project == 'true' }}; then
           if [[ $(printf '%s\n%s' "${cmake_version}" "${cmake_required_version}" | sort -V | head -n1) == "${cmake_version}" ]] && [[ "${cmake_version}" != "${cmake_required_version}" ]] && ${{ inputs.project }}; then
-            echo -e "Current CMake version (${cmake_version}) is older than ${cmake_required_version}. Updating....";
+            echo -e "\nCurrent CMake version (${cmake_version}) is older than ${cmake_required_version}. Updating....";
             sudo apt-get remove --purge -yq cmake 2>&1 >/dev/null | sed '/Running/,/host./d'
             sudo aptitude install -yq ca-certificates gpg wget 2>&1 >/dev/null | sed '/Running/,/host./d'
             sudo bash -c "$(sudo wget -qO - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null)";
@@ -1969,7 +2007,7 @@ runs: # Uses default x86_64 / linux user machine
       continue-on-error: true
       
     - name: Build Project
-      if: inputs.project == 'true' && inputs.build > '0' && inputs.pattern == ''
+      if: inputs.project == 'true' && inputs.build > '0' && inputs.build < '5' && inputs.pattern == ''
       run: |
         source ~/.bashrc
         set +e
@@ -2003,7 +2041,7 @@ runs: # Uses default x86_64 / linux user machine
           done;
         }
         if ${{ inputs.repository == 'false' }} && ${{ env.dirname != '' }}; then
-          cd "${{ env.dirname }}" && echo -e "\033[1mUser Current Directory\033[0m:  ${{ env.dirname }}\n" | process_input;
+          cd "${{ env.dirname }}" && echo -e "\n\033[1mUser Current Directory\033[0m:  ${{ env.dirname }}\n" | process_input;
         fi;
         if [[ -f 'compile_commands.json' ]]; then
           compile_json='compile_commands.json';
@@ -2164,7 +2202,7 @@ runs: # Uses default x86_64 / linux user machine
           done;
         }
         if ${{ inputs.repository == 'false' }} && ${{ env.dirname != '' }}; then
-          cd "${{ env.dirname }}" && echo -e "\033[1mUser Current Directory\033[0m:  ${{ env.dirname }}\n" | process_input;
+          cd "${{ env.dirname }}" && echo -e "\n\033[1mUser Current Directory\033[0m:  ${{ env.dirname }}\n" | process_input;
           codechecker=$(fdfind -p -a -t f -1 'codechecker.yaml' "${github}");
           compile_json=$(fdfind -p -a -t f -1 'compile_commands.json' "${github}");
         fi;
@@ -2286,12 +2324,13 @@ runs: # Uses default x86_64 / linux user machine
           fi;
           export kroot="${kroot}";
           export TERM=dumb
+          export ALLOW_MISSING_DEPENDENCIES=true
           export MAKEFILE_NAME="${{ inputs.makefile }}";
           export FILENAME="${{ env.filename }}";
           FUNC_1=$(declare -f build_module);
           FUNC_2=$(declare -f build_alone);
           if [[ -e "${codechecker}" ]] && [[ -e "${envsetup}" ]] && ${{ inputs.module == 'true' }}; then
-            # make ARCH="${{ env.arch }}" tb8163p3_bsp_defconfig
+            make ARCH="${{ env.arch }}" tb8163p3_bsp_defconfig
             echo -e "Sources: ${envsetup}";
             echo -e "\n${codechecker} file was found continuing...\n" | process_input;
             BUILD_CMD="$FUNC_1; source ${envsetup} && export kroot=${kroot} && lunch \$MAKEFILE_NAME && build_module \$FILENAME -j\$(nproc) -k";
@@ -2318,7 +2357,7 @@ runs: # Uses default x86_64 / linux user machine
               check_exit=${PIPESTATUS[0]}
           fi;
           if [[ -e "${codechecker}" ]] && [[ -e "${envsetup}" ]] && ${{ inputs.module == 'false' }}; then
-            # make ARCH="${{ env.arch }}" tb8163p3_bsp_defconfig
+            make ARCH="${{ env.arch }}" tb8163p3_bsp_defconfig
             echo -e "Sources: ${envsetup}";
             echo -e "\n${codechecker} file was found continuing...\n" | process_input;
             BUILD_CMD="$FUNC_2; source ${envsetup} && lunch \$MAKEFILE_NAME && build_alone \$FILENAME -j\$(nproc) -k";
