Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -64,7 +64,7 @@ inputs:
     description: 'Clang compiler used for project building only'
     type: string
     required: false
-    default: 'clang'
+    default: 'clang-latest'
   content:
     description: 'Search will list dir contents of found filename'
     type: boolean
@@ -159,16 +159,17 @@ runs:
         file_name="${{ inputs.filename }}";
         file_type="${file_name##*.}";
         if [[ ! $(which clang) ]] && ${{ inputs.project }}; then
-          sudo apt-get -yq install clang clang-tools >/dev/null && echo -e "\n####################\nclang tools dependencies Installed\n####################\n" || echo -e '::error::No clang-tools installed for project build';
+          sudo apt-get -yq install clang clangd >/dev/null && echo -e "\n####################\nclang tools dependencies Installed\n####################\n" || echo -e '::error::No clang-tools installed for project build';
           [[ ! $(which clang) ]] && exit 1
         fi;
         if [[ ! $(clang-tidy --version 2>/dev/null) ]] && ([[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]] && ${{ inputs.repair }}) || ${{ inputs.project }}; then
-          wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - >/dev/null 2>&1;
-          sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs) main" >/dev/null;
-          sudo apt-get install -yq clang-tidy clang-format >/dev/null && echo -e "${text5}" || echo -e '::error::No clang-tools installed Exiting';
+          sudo apt-get install -yq clang-tidy clang-tools >/dev/null && echo -e "${text5}" || echo -e '::error::No clang-tools installed Exiting';
           [[ ! $(clang-tidy --version 2>/dev/null) ]] && exit 1
         fi;
         if [[ ! $(llvm-config --version 2>/dev/null) ]] && ${{ inputs.project }}; then
+          sudo bash -c "$(sudo wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - >/dev/null 2>&1)"
+          sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs) main" >/dev/null;
+          sudo bash -c "$(sudo wget -qO - https://apt.llvm.org/llvm.sh)"
           sudo apt-get -yq install llvm llvm-dev lld libclang-dev >/dev/null && echo -e "\n####################\nllvm tools dependencies Installed\n####################\n" || echo -e '::error::No llvm tools installed for project build';
           [[ ! $(llvm-config --version 2>/dev/null) ]] && exit 1
         fi;
@@ -210,7 +211,7 @@ runs:
           [[ ! $(which cppcheck) ]] && exit 1
         fi;
         if [[ ! $(which shellharden) ]] && [[ -n $(echo "${file_type}" | egrep -i "^sh$") ]] && ${{ inputs.repair }}; then
-          wget -qO 'shellharden.tar.gz' 'https://github.com/anordal/shellharden/releases/latest/download/shellharden-x86_64-unknown-linux-gnu.tar.gz';
+          sudo wget -qO 'shellharden.tar.gz' 'https://github.com/anordal/shellharden/releases/latest/download/shellharden-x86_64-unknown-linux-gnu.tar.gz' >/dev/null;
           sudo tar xf 'shellharden.tar.gz' -C '/usr/local/bin' 'shellharden' && rm -vrf 'shellharden.tar.gz' && echo -e "${text6}" || echo -e '::error::No shellharden installed Exiting';
           [[ ! $(which shellharden) ]] && exit 1
         fi;
@@ -432,7 +433,6 @@ runs:
         export LC_ALL=C
         check_build=false
         file_type='c';
-        clang_run=${{ github.action_path }}/scripts/tools/run-clang-tidy.py;
         src_tree=$(sudo find ${{ env.file_path }} -type d -name '.git' -print -quit);
         github=${GITHUB_WORKSPACE};
         update=true
@@ -474,6 +474,8 @@ runs:
           cmake_list='CMakeLists.txt';
           clang_file='parameter-file';
           clang_tidy='.clang-tidy';
+          clang_run=${{ github.action_path }}/scripts/tools/run-clang-tidy.py;
+          clang_fix=${{ github.action_path }}/scripts/tools/clang-apply-replacements;
           echo -e "\n####################\nWorkspace Folder: ${{ env.dirname }}\n####################\n" | process_input;
           echo -e "\n####################\nProject Build: ${{ github.repository }}\n####################\n" | process_input;
           echo -e "\n####################\nCompiler: ${gcc_version}\n####################\n" | process_input;
@@ -485,6 +487,7 @@ runs:
           echo -e "\n####################\nChecking Repository ${src_tree%/*}\n####################\n" | process_input;
           echo -e "\n####################\nChecking for ${file_type} file(s)\n####################\n" | process_input;
           echo "repository=${repository}" >> "${GITHUB_ENV}";
+          # export PATH="${clang_fix}:${PATH}"
           src_dirs() {
             sudo find -type d -maxdepth 1 -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r dir; do
               echo -n "${dir#./} "
@@ -552,7 +555,7 @@ runs:
           if [[ $(which run-clang-tidy.py) ]] && ${{ env.analysis == 2 }}; then
             echo -e "\n####################\n\trun-clang-tidy.py found continuing...\n####################\n" | process_input;
             echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
-            { time "${clang_run}" -p build -config-file "${clang_tidy}" -fix -fix-errors -export-fixes build/fixes -j "$(nproc --all)" 2>/dev/null | process_input; } 2>&1
+            { time "${clang_run}" -p build -config-file "${clang_tidy}" -fix -fix-errors -j "$(nproc --all)" 2>/dev/null | process_input; } 2>&1
             if [[ "${PIPESTATUS[1]}" == 0 ]]; then
               echo -e '\n|RUNTIME|\n' | process_input;
               check_build=true
@@ -563,8 +566,9 @@ runs:
           elif [[ -e "${clang_run}" ]] && ${{ env.analysis == 2 }}; then
             echo -e "\n####################\n\trun-clang-tidy.py found continuing...\n####################\n" | process_input;
             sudo chmod -v 0755 "${clang_run}" 2>/dev/null | process_input;
+            sudo chmod -R 0755 "${clang_fix}" 2>/dev/null;
             echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
-            "${clang_run}" -p build -config-file "${clang_tidy}" -fix -fix-errors -export-fixes build/fixes -j "$(nproc --all)" | process_input;
+            { time "${clang_run}" -p build -config-file "${clang_tidy}" -fix -fix-errors -j "$(nproc --all)" 2>/dev/null | process_input; } 2>&1
             if [[ "${PIPESTATUS[1]}" == 0 ]]; then
               echo -e '\n|RUNTIME|\n' | process_input;
               check_build=true
