Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,13 +4,14 @@ inputs:
   analyzer:
     description: 'Analyze all project files using options 1 - 2 - 3 - 4'
     required: false
-    default: 1
+    default: 0
     type: choice
     options:
-    - 1 # clang-tidy - parameter-file for small project file checks.
-    - 2 # run-clang-tidy.py - compile_commands.json for large project file checks.
-    - 3 # clangd-tidy - compile_commands.json for faster large project file checks.
-    - 4 # cmake - build sources and use clang-tidy for project file checks
+    - 0 # disable project analyzer
+    - 1 # run-clang-tidy.py - fastest for large project file checks. fix-its
+    - 2 # clang-tidy - faster for small an large project file checks. fix-its
+    - 3 # clangd-tidy - fast large project file checks.
+    - 4 # codechecker - compiler project file check reports. 
   filename:
     description: 'Check for filename or search for text word matches'
     type: string
@@ -109,12 +110,17 @@ inputs:
     description: 'Fix Errors found while building repository project'
     type: choice
     required: false
-    default: '1'
+    default: '0'
     options:
-    - 1 # Disable building projects.
-    - 2 # Build & check project.
-    - 3 # Build with new compile_commands_json & check project.
-
+    - 0 # Disable building projects.
+    - 1 # Build & check project.
+    - 2 # Build with new compile_commands_json & check project.
+    file:
+    description: 'Make filename for building project source'
+    type: string
+    required: false
+    default: ''
+    
 runs:
   using: composite
   steps:
@@ -229,12 +235,14 @@ runs:
           sudo apt-get -yq install python3 >/dev/null >/dev/null && echo -e "\n####################\npython3 dependencies Installed\n####################\n" || echo -e '::error::No python3 installed for project checks';
           [[ ! $(which python3) ]] && exit 1
         fi;
-        if [[ ! $(which clangd) ]] && ${{ inputs.project }}; then
-          sudo apt-get -yq install clangd >/dev/null && echo -e "\n####################\nclangd dependencies Installed\n####################\n" || echo -e '::error::No clangd installed for project build';
-          [[ ! $(which clangd) ]] && exit 1
+        if [[ ! $(llvm-config --version 2>/dev/null) ]] && ${{ inputs.project }}; then
+          sudo bash -c "$(sudo wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - >/dev/null 2>&1)"
+          sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs) main" >/dev/null;
+          sudo apt-get -yq install llvm-22-dev liblldb-22-dev llvm llvm-dev lld libclang-dev >/dev/null && echo -e "\n####################\nllvm tools dependencies Installed\n####################\n" || echo -e '::error::No llvm tools installed for project build';
+          [[ ! $(llvm-config --version 2>/dev/null) ]] && exit 1
         fi;
         if [[ ! $(which clang-tidy) ]] && ([[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]] && ${{ inputs.repair }}) || ${{ inputs.project }}; then
-          sudo apt-get install -yq clang-tidy clang-tools >/dev/null && echo -e "${text5}" || echo -e '::error::No clang-tidy installed Exiting';
+          sudo apt-get install -yq clang-tools clang-tidy clang >/dev/null && echo -e "${text5}" || echo -e '::error::No clang-tidy installed Exiting';
           [[ ! $(which clang-tidy) ]] && exit 1
         fi;
         if [[ ! $(which clangd-tidy) ]] && ${{ inputs.project }} && ${{ inputs.analyzer == 3 }}; then
@@ -244,6 +252,10 @@ runs:
           else
             exit 1
           fi;
+        fi;
+        if [[ ! $(which clangd) ]] && ${{ inputs.project }}; then
+          sudo apt-get -yq install clangd >/dev/null && echo -e "\n####################\nclangd dependencies Installed\n####################\n" || echo -e '::error::No clangd installed for project build';
+          [[ ! $(which clangd) ]] && exit 1
         fi;
         if [[ ! $(which CodeChecker) ]] && ${{ inputs.project }} && ${{ inputs.analyzer == 4 }}; then
           sudo apt-get -yq install python3-pip python3-venv make >/dev/null && echo -e "\n####################\npython3-pip dependencies Installed\n####################\n" || echo -e '::error::No python3-pip installed for project checks';
@@ -261,12 +273,6 @@ runs:
           else
             exit 1
           fi;
-        fi;
-        if [[ ! $(llvm-config --version 2>/dev/null) ]] && ${{ inputs.project }}; then
-          sudo bash -c "$(sudo wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - >/dev/null 2>&1)"
-          sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs) main" >/dev/null;
-          sudo apt-get -yq install llvm llvm-dev lld libclang-dev >/dev/null && echo -e "\n####################\nllvm tools dependencies Installed\n####################\n" || echo -e '::error::No llvm tools installed for project build';
-          [[ ! $(llvm-config --version 2>/dev/null) ]] && exit 1
         fi;
         if [[ ! $(dpkg -s build-essential 2>/dev/null) ]] && ${{ inputs.project }}; then
           sudo apt-get -yq install build-essential device-tree-compiler >/dev/null && echo -e "\n####################\nbuild-essential dependencies Installed\n####################\n" || echo -e '::error::No build-essential installed for project build';
@@ -535,6 +541,8 @@ runs:
       run: |
         export LLVM_ENABLE_THREADS=ON
         export CMAKE_EXPORT_COMPILE_COMMANDS=ON
+        export ALLOW_MISSING_DEPENDENCIES=true
+        export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
         export LC_ALL=C
         set +e
         repository=$(echo ${{ github.repository }} | cut -d'/' -f 2-);
@@ -662,7 +670,26 @@ runs:
           if [[ -e 'compile_commands.json' ]]; then
             echo -e '\n####################\n\tcompile_commands.json file symlinked continuing...\n####################\n' | process_input;
           fi;
-          if [[ -f "${clang_file}" ]] && ${{ env.analyzer == 1 }}; then
+          if [[ -e "${clang_run}" ]] && ${{ env.analyzer == 1 }}; then
+            echo -e "\n####################\n\trun-clang-tidy.py found continuing...\n####################\n" | process_input;
+            sudo chmod -v 0755 "${clang_run}" 2>/dev/null | process_input;
+            sudo chmod -R 0755 "${clang_fix}" 2>/dev/null;
+            echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
+            { time "${{ github.action_path }}/scripts/tools/run-clang-tidy.py" -p build -config-file "${clang_tidy}" -fix -export-fixes build/fixes -j "$(nproc --all)" -enable-check-profile; } 2>&1 | process_input;
+            if [[ -s "${project_log}" ]] && [[ $(grep -sE 'error:|Error:|Error while processing|ERROR:' "${project_log}") ]]; then
+              echo -e "::notice::Errors found checking project files" | process_input;
+              check_build=true
+              echo 'check_build=true' >> "${GITHUB_ENV}";
+            elif [[ -s "${project_log}" ]]; then
+              echo -e "::notice::No errors found checking project files" | process_input;
+              check_build=true
+              echo 'check_build=true' >> "${GITHUB_ENV}";
+            fi;
+          elif [[ ! -e "${clang_run}" ]] && ${{ env.analyzer == 1 }}; then
+            echo -e "\n####################\n\t::error:: run-clang-tidy.py missing in repo Exiting...\n####################\n" | process_input;
+            exit 1
+          fi;
+          if [[ -f "${clang_file}" ]] && ${{ env.analyzer == 2 }}; then
             echo ' ' >> "${clang_file}";
             files_list=false
             if [[ `header2_list` ]] && [[ `source_list` ]] ; then
@@ -695,27 +722,8 @@ runs:
             else
               exit 1
             fi;
-          elif [[ ! -e "${clang_file}" ]] && ${{ env.analyzer == 1 }}; then
+          elif [[ ! -e "${clang_file}" ]] && ${{ env.analyzer == 2 }}; then
             echo -e "\n####################\n\t::error:: parameter-file missing in repo Exiting...\n####################\n" | process_input;
-            exit 1
-          fi;
-          if [[ -e "${clang_run}" ]] && ${{ env.analyzer == 2 }}; then
-            echo -e "\n####################\n\trun-clang-tidy.py found continuing...\n####################\n" | process_input;
-            sudo chmod -v 0755 "${clang_run}" 2>/dev/null | process_input;
-            sudo chmod -R 0755 "${clang_fix}" 2>/dev/null;
-            echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
-            { time "${{ github.action_path }}/scripts/tools/run-clang-tidy.py" -p build -config-file "${clang_tidy}" -fix -export-fixes build/fixes -j "$(nproc --all)" -enable-check-profile; } 2>&1 | process_input;
-            if [[ -s "${project_log}" ]] && [[ $(grep -sE 'error:|Error:|Error while processing|ERROR:' "${project_log}") ]]; then
-              echo -e "::notice::Errors found checking project files" | process_input;
-              check_build=true
-              echo 'check_build=true' >> "${GITHUB_ENV}";
-            elif [[ -s "${project_log}" ]]; then
-              echo -e "::notice::No errors found checking project files" | process_input;
-              check_build=true
-              echo 'check_build=true' >> "${GITHUB_ENV}";
-            fi;
-          elif [[ ! -e "${clang_run}" ]] && ${{ env.analyzer == 2 }}; then
-            echo -e "\n####################\n\t::error:: run-clang-tidy.py missing in repo Exiting...\n####################\n" | process_input;
             exit 1
           fi;
           if [[ -f "${clangd_tidy}" ]] && ${{ env.analyzer == 3 }}; then
@@ -765,7 +773,7 @@ runs:
             else
              echo -e "\nUnable to source ( /home/runner/codechecker/venv/bin/activate ) file\n" | process_input;
             fi;
-            { time CodeChecker check -b "cmake clean && cmake" -o ./results && CodeChecker server && CodeChecker store ./results -n "${repository}"; } 2>&1 | process_input;
+            { time CodeChecker check -b "cmake clean && cmake ${{ inputs.file }}" -o ./results && CodeChecker server && CodeChecker store ./results -n "${repository}"; } 2>&1 | process_input;
             if [[ -s "${project_log}" ]] && [[ $(grep -sE 'error:|Error:|Error while processing|ERROR:' "${project_log}") ]]; then
               echo -e "::notice::Errors found checking project files" | process_input;
               check_build=true
@@ -792,7 +800,7 @@ runs:
              echo -e "\nUnable to source ( /home/runner/codechecker/venv/bin/activate ) file\n" | process_input;
             fi;
             [ -e '/build/compile_commands.json' ]] && rm -vf ./build/compile_commands.json | process_input;
-            { time CodeChecker log --build "make" --output ./build/compile_commands.json && CodeChecker server && CodeChecker store ./results -n "${repository}"; } 2>&1 | process_input;
+            { time CodeChecker log --build "make ${{ inputs.file }}" --output ./build/compile_commands.json && CodeChecker server && CodeChecker store ./results -n "${repository}"; } 2>&1 | process_input;
             if [[ -s "${project_log}" ]] && [[ $(grep -sE 'error:|Error:|Error while processing|ERROR:' "${project_log}") ]]; then
               echo -e "::notice::Errors found checking project files" | process_input;
               check_build=true
@@ -838,7 +846,7 @@ runs:
           if [[ ${update} ]] && ${{ env.analyzer == 1 }}; then
             echo -e "\nPARAMETERS: $(rm -vf ${clang_file} 2>/dev/null)\n" | process_input;
           fi;
-          if ${{ inputs.build > 1 }}; then
+          if ${{ inputs.build > 0 }}; then
             cp -Rf ./build ${github}/ && echo -e '\n####################\n\tbuild directory updated continuing...\n####################\n' | process_input;
           fi;
           echo -e "\n####################\n\tINSTALLED COMPILERS\n####################\n\n${compiler_list}\n" | process_input;
@@ -1522,7 +1530,7 @@ runs:
       continue-on-error: true
 
     - name: Uploading ${{ github.repository }} Project Build Release
-      if: inputs.build > '1' && inputs.project != 'false' && env.build_files == 1
+      if: inputs.build > '0' && inputs.project != 'false' && env.build_files == 1
       uses: softprops/action-gh-release@v1
       with:
         files: build/bin/*
@@ -1531,7 +1539,7 @@ runs:
       continue-on-error: true
 
     - name: Uploading ${{ github.repository }} Project Build Release
-      if: inputs.build > '1' && inputs.project != 'false' && env.build_files == 1
+      if: inputs.build > '0' && inputs.project != 'false' && env.build_files == 1
       uses: actions/upload-artifact@v4
       with:
         name: Build For ${{ github.repository }} Repository.
