Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1310,7 +1310,7 @@ runs:
               cp -vf "${clang_file}" 'build/parameter-source.txt' 2>/dev/null;
               echo -e '\n####################\nCLANG-TIDY ANALYZING FILES\n####################\n' | process_input;
               clang-tidy @parameter-file 2>&1 | process_input || echo -e "\n::notice::clang-tidy exit-code ($?)";
-              if [[ "$?" > '0' ]]; then
+              if [[ -s "${project_log}" ]] && [[ $(grep -siF 'process ended' "${project_log}") ]]; then
                 echo 'check_build=false' >> "${GITHUB_ENV}";
               elif [[ -s "${project_log}" ]] && [[ $(LC_ALL=C grep -sE 'error:|Error:|Error while processing|ERROR:' "${project_log}") ]]; then
                 echo -e "\n::notice::Errors found checking project files" | process_input && echo 'check_build=true' >> "${GITHUB_ENV}" && echo 'build_error=true' >> "${GITHUB_ENV}" && check_build=true;
@@ -1324,7 +1324,7 @@ runs:
           if [[ -f "${clangd_tidy}" ]] && ${{ env.analyzer == '3' }} && [[ -e "${compile_json}" ]]; then
             echo -e '\n####################\nCLANGD-TIDY ANALYZING FILES\n####################\n' | process_input;
             fdfind -p -c auto "${abs}" -e "${{ inputs.filetype }}" "${{ env.base }}" -x clangd-tidy -p build -j "$(nproc --all)" --color always --tqdm 2>&1 | process_input || echo -e "\n::notice::clangd-tidy exit-code ($?)";
-            if [[ "$?" > '0' ]]; then
+            if [[ -s "${project_log}" ]] && [[ $(grep -siF 'process ended' "${project_log}") ]]; then
               echo 'check_build=false' >> "${GITHUB_ENV}";
             elif [[ -s "${project_log}" ]] && [[ $(LC_ALL=C grep -sE 'error:|Error:|Error while processing|ERROR:' "${project_log}") ]]; then
               echo -e "\n::notice::Errors found checking project files" | process_input && echo 'check_build=true' >> "${GITHUB_ENV}" && echo 'build_error=true' >> "${GITHUB_ENV}" && check_build=true;
@@ -1345,16 +1345,16 @@ runs:
             fi;
             if ${{ inputs.repair }}; then
               echo -e "\nRepair mode continuing without config file continuing...\n" | process_input;
-              CodeChecker analyze "${compile_json}" --jobs "$(nproc --all)" --output ./reports 2>&1 | process_input || echo -e "\nCodeChecker analyzer exit-code ($?)";
-              CodeChecker fixit --checker-name bugprone-suspicious-string-compare --jobs "$(nproc --all)" --apply ./reports 2>&1 | process_input || echo -e "\n::notice::CodeChecker fixit exit-code ($?)";
-              CodeChecker parse ./reports 2>&1 | process_input || echo -e "\n::notice::CodeChecker parse exit-code ($?)";
+              CodeChecker analyze "${compile_json}" --jobs "$(nproc --all)" --output ./reports 2>&1 | process_input || echo -e "\nCodeChecker analyzer exit-code ($?)" | process_input;
+              CodeChecker fixit --checker-name bugprone-suspicious-string-compare --jobs "$(nproc --all)" --apply ./reports 2>&1 | process_input || echo -e "\nCodeChecker fixit exit-code ($?)" | process_input;
+              CodeChecker parse ./reports 2>&1 | process_input || echo -e "\nCodeChecker parse exit-code ($?)" | process_input;
             else
               [[ -e "${codechecker}" ]] && echo -e "\n${codechecker} file was found continuing...\n" | process_input || echo -e "\n::warning::${codechecker} file was not found continuing...\n" | process_input;
-              CodeChecker check --logfile "${compile_json}" --config "${codechecker}" --jobs "$(nproc --all)" 2>&1 | process_input || echo -e "\n::notice::CodeChecker check exit-code ($?)";
+              CodeChecker check --logfile "${compile_json}" --config "${codechecker}" --jobs "$(nproc --all)" 2>&1 | process_input || echo -e "\nCodeChecker check exit-code ($?)" | process_input;
             fi;
-            if [[ "$?" -gt 0 ]]; then
+            if [[ -s "${project_log}" ]] && [[ $(grep -siF 'process ended' "${project_log}") ]]; then
               echo 'check_build=false' >> "${GITHUB_ENV}";
-            elif [[ -s "${project_log}" ]] && [[ $(LC_ALL=C grep -sE 'error:|Error:|Error while processing|ERROR:' "${project_log}") ]]; then
+            elif [[ -s "${project_log}" ]] && [[ $(grep -siE 'error:|Error while processing' "${project_log}") ]]; then
               echo -e "\n::notice::Errors found checking project files" | process_input && echo 'check_build=true' >> "${GITHUB_ENV}" && echo 'build_error=true' >> "${GITHUB_ENV}" && check_build=true;
             elif [[ -s "${project_log}" ]]; then
               echo -e "\n::notice::No errors found checking project files" | process_input && echo 'check_build=true' >> "${GITHUB_ENV}" && check_build=true;
@@ -1437,12 +1437,12 @@ runs:
           [[ -e 'build/envsetup.sh' ]] && source build/envsetup.sh
           if [[ -e "${codechecker}" ]]; then
             echo -e "\n${codechecker} file was found continuing...\n" | process_input;
-            CodeChecker check -b "make -j$(nproc --all)" --config "${codechecker}" --jobs "$(nproc --all)" --print-steps 2>&1 | process_input || echo -e "\n::notice::CodeChecker check exit-code ($?)";
+            CodeChecker check -b "make -j$(nproc --all)" --config "${codechecker}" --jobs "$(nproc --all)" --print-steps 2>&1 | process_input || echo -e "\n::notice::CodeChecker check exit-code ($?)" | process_input;
           else
             echo -e "\n${codechecker} file was not found continuing without...\n" | process_input;
             CodeChecker check -b "make" --jobs "$(nproc --all)" --print-steps 2>&1 | process_input || echo -e "\n::notice::CodeChecker check exit-code ($?)";
           fi;
-          if [[ "$?" > '0' ]]; then
+          if [[ -s "${project_log}" ]] && [[ $(grep -siF 'process ended' "${project_log}") ]]; then
             echo 'check_build=false' >> "${GITHUB_ENV}";
           elif [[ -s "${project_log}" ]] && [[ $(LC_ALL=C grep -sE 'error:|Error:|Error while processing|ERROR:' "${project_log}") ]]; then
             echo -e "\n::notice::Errors found building project files" | process_input && echo 'check_build=true' >> "${GITHUB_ENV}" && echo 'build_error=true' >> "${GITHUB_ENV}" && check_build=true;
@@ -1465,8 +1465,8 @@ runs:
             echo -e "\nUnable to source ( /home/runner/codechecker/venv/bin/activate ) file\n" | process_input;
           fi;
           [[ -e "${compile_json}" ]] && rm -vf "${compile_json}" | process_input;
-          CodeChecker log --build "make -j$(nproc --all)" --output "${compile_json}" 2>&1 | process_input || echo -e "\n::notice::CodeChecker log exit-code ($?)";
-          if [[ "$?" > '0' ]]; then
+          CodeChecker log --build "make -j$(nproc --all)" --output "${compile_json}" 2>&1 | process_input || echo -e "\n::notice::CodeChecker log exit-code ($?)" | process_input;
+          if [[ -s "${project_log}" ]] && [[ $(grep -siF 'process ended' "${project_log}") ]]; then
             echo 'check_build=false' >> "${GITHUB_ENV}";
           elif [[ -s "${project_log}" ]] && [[ $(LC_ALL=C grep -sE 'error:|Error:|Error while processing|ERROR:' "${project_log}") ]]; then
             echo -e "\n::notice::Errors found building commands JSON file" | process_input && echo 'check_build=true' >> "${GITHUB_ENV}" && echo 'build_error=true' >> "${GITHUB_ENV}" && check_build=true;
@@ -1482,8 +1482,8 @@ runs:
         if ${{ env.build_files == '1' }} && ${{ inputs.build == '3' }} && ${{ env.build_error == 'false' }}; then
           echo -e '\n####################\n\tDeheader analyze sources includes on build...(dry-run -3)\n####################\n' | process_input;
           sudo bash -c 'source ~/.bashrc'
-          deheader -v -r -m "make -n -j$(nproc --all)" | process_input || echo -e "\n::notice::deheader check exit-code ($?)";
-          if [[ "$?" > '0' ]]; then
+          deheader -v -r -m "make -n -j$(nproc --all)" | process_input || echo -e "\n::notice::deheader check exit-code ($?)" | process_input;
+          if [[ -s "${project_log}" ]] && [[ $(grep -siF 'process ended' "${project_log}") ]]; then
             echo 'check_build=false' >> "${GITHUB_ENV}";
           elif [[ -s "${project_log}" ]] && [[ $(LC_ALL=C grep -sE ' duplicates|inclusion' "${project_log}") ]]; then
             echo -e "\n::notice::duplicate includes found building project files" | process_input && echo 'check_build=true' >> "${GITHUB_ENV}" && check_build=true;
@@ -1500,8 +1500,8 @@ runs:
           echo -e '\n####################\n\tDeheader analyze & repair sources includes on build...(test-run -4)\n####################\n' | process_input;
           sudo bash -c 'source ~/.bashrc'
           [[ -e 'build/envsetup.sh' ]] && source build/envsetup.sh
-          deheader -v -r -m "lunch ${{ inputs.makefile }} && make clean && make ${{ inputs.filename }} -j$(nproc --all) -k" | process_input || echo -e "\n::notice::deheader build exit-code ($?)";
-          if [[ "$?" > '0' ]]; then
+          deheader -v -r -m "lunch ${{ inputs.makefile }} && make clean && make ${{ inputs.filename }} -j$(nproc --all) -k" | process_input || echo -e "\n::notice::deheader build exit-code ($?)" | process_input;
+          if [[ -s "${project_log}" ]] && [[ $(grep -siF 'process ended' "${project_log}") ]]; then
             echo 'check_build=false' >> "${GITHUB_ENV}";
           elif [[ -s "${project_log}" ]] && [[ $(LC_ALL=C grep -sE ' duplicates|inclusion' "${project_log}") ]]; then
             echo -e "\n::notice::duplicate includes found building project files" | process_input && echo 'check_build=true' >> "${GITHUB_ENV}" && check_build=true;
@@ -1519,12 +1519,14 @@ runs:
           deheader_duplicates=$(grep -sFc 'duplicates' "${project_log}");
           deheader_inclusion=$(grep -sFc 'inclusion' "${project_log}");
           deheader_removed=$(grep -sFc 'remove' "${project_log}");
+          codechecker_defects=$(grep -sEo 'Found [1-9] defect(s) in|Found 1 defect(s) in' "${project_log}" | cut -d ' ' -f1 | awk '{sum += $1} END {print sum}');
+          codechecker_no_defects=$(grep -sFo 'Found no defects in' "${project_log}" | cut -d ' ' -f1 | awk '{sum += $1} END {print sum}');
           codechecker_success=$(grep -sFc 'successfully' "${project_log}");
           codechecker_errors=$(grep -sFc 'Error while processing' "${project_log}");
           clang_replacements=$(grep -sF 'Replacements:' "${build_fixes}" | grep -vc '[\[\]]');
           clang_information=$(grep -siFc 'information:' "${project_log}");
           clang_files_missing=$(grep -sFc 'file not found' "${project_log}");
-          clang_files_list=$(grep -sF 'file not found' "${project_log}" | awk '{print $3}' | awk '!seen[$0]++');
+          clang_files_list=$(grep -sEo '^#include[[:space:]]+[<"].*[>"]' "${project_log}" | awk '{print $2}' | tr -d '<">' | sort -u);
           clang_warnings=$(grep -sEo '[1-9] warnings generated|1 warning generated' "${project_log}" | cut -d ' ' -f1 | awk '{sum += $1} END {print sum}');
           clang_errors=$(grep -sEo '[1-9] errors generated|1 error generated' "${project_log}" | cut -d ' ' -f1 | awk '{sum += $1} END {print sum}');
           clang_fixit1=$(grep -siEc 'fixit|fix-its' "${project_log}");
@@ -1538,6 +1540,12 @@ runs:
           fi;
           if [[ -n "${clang_warnings}" ]] && [[ "${clang_warnings:-0}" > '0' ]]; then
             echo -e "\n####################\n::notice::⚠️ check-file found ${clang_warnings}️ warnings in ${file_type} file(s) checked. [Hints] Try using ( warnings-as-errors ) for possible errors.\n####################" | process_input;
+          fi;
+          if [[ -n "${codechecker_defects}" ]] && [[ "${codechecker_defects:-0}" > '0' ]] && (${{ inputs.analyzer == '4' }} || ${{ inputs.build == '1' }} || ${{ inputs.build == '2' }}); then
+            echo -e "\n####################\n::notice::⚠️ check-file checked ${codechecker_defects} ${file_type} file(s) with defects. [Hints] Check require for those files.\n####################" | process_input;
+          fi;
+          if [[ -n "${codechecker_no_defects}" ]] && [[ "${codechecker_no_defects:-0}" > '0' ]] && (${{ inputs.analyzer == '4' }} || ${{ inputs.build == '1' }} || ${{ inputs.build == '2' }}); then
+            echo -e "\n####################\n::notice::✅ check-file checked ${codechecker_no_defects} ${file_type} file(s) without defects. [Hints] No check require for those files.\n####################" | process_input;
           fi;
           if [[ -n "${codechecker_success}" ]] && [[ "${codechecker_success:-0}" > '0' ]] && (${{ inputs.analyzer == '4' }} || ${{ inputs.build == '1' }} || ${{ inputs.build == '2' }}); then
             echo -e "\n####################\n::notice::✅ check-file checked ${codechecker_success} ${file_type} file(s) successfully without issues. [Hints] No check require for those files.\n####################" | process_input;
@@ -1569,47 +1577,49 @@ runs:
             echo -e "\n####################\n::notice::🚫 check-file found ${deheader_inclusion} extra inclusions in ${file_type} file(s) checked. [Hints] Try using (update: true) if headers were fixed to update remote repository.\n####################" | process_input;
           fi;
           if [[ -n "${clang_files_missing}" ]] && [[ "${clang_files_missing:-0}" > '0' ]]; then
-            echo -e "\n####################\n::notice::❌ check-file discovered ${clang_files_missing} missing include files in ${file_type} file(s) checked. [Hints] Files may be there yet not included and many duplicate files.\n####################" | process_input;
-            echo -e "\n####################\nMISSING FILES:\n####################\n\n${clang_files_list}" | process_input;
+            echo -e "\n####################\n::notice::❌ check-file discovered ${clang_files_missing} missing include files being called in ${file_type} file(s) checked. [Hints] Files may be there yet not included an/or duplicate missing files.\n####################" | process_input;
+            echo -e "\n####################\nMISSING FILES LIST:\n####################\n\n${clang_files_list}" | process_input;
             echo -e "\n####################\nCHECK-FILE AUTO LOCATE FILES IN: ${{ env.base }}\n####################\n" | process_input;
             declare -A missing
             found=false
             while IFS= read -r missing_file; do
-              file_count=$((file_count + 1));
-              echo "Locating missing ${missing_file} file ...." | process_input;
-              path1="${missing_file//\'/}";
-              path2="${path1##[:]*}";
-              path3="${path2%'\n'}";
-              path4="${path3%\\}";
-              clean_path="${path4##+(*./)}";
-              file1="${missing_file//\'/}";
-              file2="${file1##[:]*}";
-              file3="${file2%'\n'}";
-              file4="${file3%\\}";
-              clean_file="${clean_file##*/}";
-              shopt -s extglob
-              if [[ ${missing_file} == *"/"* ]]; then          
-                locate=$(fdfind -p -c auto "${abs}" -t f -g "**/${clean_path##+(*./)}" "${{ env.base }}");
-              else
-                locate=$(fdfind -p -c auto "${abs}" -t f "${clean_file##+(*./)}" "${{ env.base }}");
-              fi;
-              if [[ "${locate}" ]]; then            
-                while IFS= read -r includes; do
-                  located_count=$((located_count + 1));
-                  echo -e "\n\033[32mSource Location:\033[0m ${includes}  [ ✅ ]" | process_input;
-                  echo "${includes%/*}" >> 'check-file-includes.txt';
-                done <<< "${locate[@]}";
-                includes_found=true
-              elif [[ -n "${missing[$missing_file]}" ]]; then
-                includes_found=false
-                echo -e "\n\033[33mSource file #include \033[0m( ${missing_file} )\033[33m already listed missing!\033[0m  [\033[1m skipped \033[0m]" | process_input;
-              else
-                includes_found=false
-                missing["$missing_file"]=1
-                missing_count=$((missing_count + 1));
-                echo -e "\n\033[31mCannot locate missing file\033[0m ${missing_file}  [ ❌ ]" | process_input;
-              fi;
-              shopt -u extglob             
+              if [[ "${missing_file}" == *.[h]* ]] || [[ "${missing_file}" == *.[c]* ]]; then
+                file_count=$((file_count + 1));
+                echo "Locating missing ${missing_file} file ...." | process_input;
+                path1="${missing_file//\'/}";
+                path2="${path1##[:]*}";
+                path3="${path2%'\n'}";
+                path4="${path3%\\}";
+                clean_path="${path4##+(*./)}";
+                file1="${missing_file//\'/}";
+                file2="${file1##[:]*}";
+                file3="${file2%'\n'}";
+                file4="${file3%\\}";
+                clean_file="${clean_file##*/}";
+                shopt -s extglob
+                if [[ ${missing_file} == *"/"* ]]; then          
+                  locate=$(fdfind -p -c auto "${abs}" -t f -g "**/${clean_path##+(*./)}" "${{ env.base }}");
+                else
+                  locate=$(fdfind -p -c auto "${abs}" -t f "${clean_file##+(*./)}" "${{ env.base }}");
+                fi;
+                if [[ "${locate}" ]]; then            
+                  while IFS= read -r includes; do
+                    located_count=$((located_count + 1));
+                    echo -e "\n\033[32mSource Location:\033[0m ${includes}  [ ✅ ]" | process_input;
+                    echo "${includes%/*}" >> 'check-file-includes.txt';
+                  done <<< "${locate[@]}";
+                  includes_found=true
+                elif [[ -n "${missing[$missing_file]}" ]]; then
+                  includes_found=false
+                  echo -e "\n\033[33mSource file #include \033[0m( ${missing_file} )\033[33m already listed missing!\033[0m  [\033[1m skipped \033[0m]" | process_input;
+                else
+                  includes_found=false
+                  missing["$missing_file"]=1
+                  missing_count=$((missing_count + 1));
+                  echo -e "\n\033[31mCannot locate missing file\033[0m ${missing_file}  [ ❌ ]" | process_input;
+                fi;
+                shopt -u extglob
+              fi;             
             done <<< "${clang_files_list}";
             unset missing;
             if [[ -s 'check-file-includes.txt' ]]; then
@@ -2230,7 +2240,7 @@ runs:
       run: |
         echo '';
         set +e
-        min_size_bytes=$((10 * 1024 * 1024));
+        min_size_bytes=$((20 * 1024 * 1024));
         filename1="${{ env.github_repository }}_project.log";
         filename2="${{ inputs.filename }}_error.log";
         if [[ -s "${filename1}" ]]; then
@@ -2238,7 +2248,7 @@ runs:
           ansi2txt "${filename1}" > "${filename1}.tmp";
           mv -vf "${filename1}.tmp" "${filename1}";
           if (( filesize1 > min_size_bytes )); then
-            split -l 100000 "${filename1}" 'part_'
+            split -d -b 10M "${filename1}" 'part_'
             echo "file1_parted=1" >> "${GITHUB_ENV}";
           fi;
         fi;
@@ -2247,7 +2257,7 @@ runs:
           ansi2txt "${filename2}" > "${filename2}.tmp";
           mv -vf "${filename2}.tmp" "${filename2}";
           if (( filesize2 > min_size_bytes )); then
-            split -l 100000 "${filename2}" 'part_'
+            split -d -b 10M "${filename2}" 'part_'
             echo "file2_parted=1" >> "${GITHUB_ENV}";
           fi;
         fi;
