Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -162,6 +162,9 @@ runs:
         DEFAULT_PATH: "*" 
       run: |
         set -o pipefail
+        repair_file='check-file-repaired.txt';
+        repository=$(sudo find ${GITHUB_WORKSPACE} -type d -name '.git' -print -quit);
+        
         if ${{ inputs.rootdir }}; then
           echo -e "\n####################\nDEFAULT DIRECTORY (SYSTEM ROOT)\n####################\n";
           echo -e "\n ~/\n";
@@ -174,11 +177,23 @@ runs:
           FILE_PATH=${GITHUB_WORKSPACE}
         fi;
 
+        if [[ -d ${repository} ]] && ${{ inputs.repair }}; then
+          repository="${repository%/*}/${repair_file}";
+          if [[ -f ${repository} ]]; then
+            echo -e "\n####################\nRepaired files list found!!!\n####################\n";
+          else
+            echo -e "\nCreating ${repair_file} for checked files\n"
+            echo -n '' > "${repository}";
+          fi;
+        fi;
+
         if ${{ inputs.database }}; then
           sudo find "${FILE_PATH}" -name "*" -print > "${GITHUB_WORKSPACE}/check_file_list.txt";
           if [[ -f "${GITHUB_WORKSPACE}/check_file_list.txt" ]]; then
             echo -e "\n####################\ncheck_file_list database found\n####################\n";
             echo "DATABASE=${GITHUB_WORKSPACE}/check_file_list.txt" >> "${GITHUB_ENV}";
+          else
+            echo 'Database check_file_list.txt not found exiting..' && exit 1
           fi;
         fi;
 
@@ -218,8 +233,6 @@ runs:
         file_type=$(echo ${{ inputs.filename }} | sed 's/.*\.\([^.]*\)$/\1/');
         clang_file=${GITHUB_WORKSPACE}/.clang-tidy;
         repaired=$(sudo rg -F 'check-file-repaired.txt' "${{ env.DATABASE }}");
-        repository=$(sudo find ${GITHUB_WORKSPACE} -type d -name '.git' -print -quit);
-        repair_file='check-file-repaired.txt';
         count2=0
         checked=false
         file_count=1
@@ -232,15 +245,6 @@ runs:
           fi;
           if ${{ inputs.content }}; then
             echo -e "\n# Found File Path(s)\n${files}\n";
-          fi;
-          if [[ -d ${repository} ]] && ${{ inputs.repair }}; then
-            repository="${repository%/*}/${repair_file}";
-            if [[ -f ${repository} ]]; then
-              echo -e "\n####################\nRepaired files list found!!!\n####################\n";
-            else
-              touch "${repository}";
-              sudo find "${{ env.FILE_PATH }}" -name "*" -print > "${GITHUB_WORKSPACE}/check_file_list.txt";
-            fi;
           fi;
           time -p for f in ${files[@]}; do
             SEARCH_PATH="${f}";
@@ -398,24 +402,13 @@ runs:
         set -o pipefail
         fixed=false
         shellcheck_count=1
-        repair_file='check-file-repaired.txt';
-        repaired=$(sudo rg -F 'check-file-repaired.txt' "${{ env.DATABASE }}");
-        repository=$(sudo find ${GITHUB_WORKSPACE} -type d -name '.git' -print -quit);
+        repaired=$(sudo rg -F 'check-file-repaired.txt' "${{ env.DATABASE }}";
         files=$(sudo rg "/${{ inputs.filename }}$" "${{ env.DATABASE }}");
         file_type=$(echo ${{ inputs.filename }} | sed 's/.*\.\([^.]*\)$/\1/');
         if [[ -n $(echo "${file_type}" | grep -i "^sh$") ]] && [[ -n ${files} ]]; then
           echo -e "\n####################\nWorkspace Folder: ${{ steps.set_dirname.outputs.dirname }}\n####################\n";
           if ${{ inputs.content }}; then
             echo -e "\n# Found File Path(s)\n${files}\n";
-          fi;
-          if [[ -d ${repository} ]] && ${{ inputs.repair }}; then
-            repository="${repository%/*}/${repair_file}";
-            if [[ -f ${repository} ]]; then
-              echo -e "\n####################\nRepaired files list found!!!\n####################\n";
-            else
-              touch "${repository}";
-              sudo find "${{ env.FILE_PATH }}" -name "*" -print > "${GITHUB_WORKSPACE}/check_file_list.txt";
-            fi;
           fi;
           time -p for f in ${files[@]}; do
             SEARCH_PATH="${f}";
@@ -574,8 +567,6 @@ runs:
         file_type=$(echo ${{ inputs.filename }} | sed 's/.*\.\([^.]*\)$/\1/');
         clang_file=${GITHUB_WORKSPACE}/.clang-tidy;
         repaired=$(sudo find ${{ env.FILE_PATH }} -type f -name 'check-file-repaired.txt' -print -quit);
-        repository=$(sudo find ${GITHUB_WORKSPACE} -type d -name ".git" -print -quit);
-        repair_file='check-file-repaired.txt';
         count2=0
         checked=false
         file_count=1
@@ -588,14 +579,6 @@ runs:
           fi;
           if ${{ inputs.content }}; then
             echo -e "\n# Found File Path(s)\n${files}\n";
-          fi;
-          if [[ -d ${repository} ]] && ${{ inputs.repair }}; then
-            repository="${repository%/*}/${repair_file}";
-            if [[ -f ${repository} ]]; then
-              echo -e "\n####################\nRepaired files list found!!!\n####################\n";
-            else
-              touch "${repository}";
-            fi;
           fi;
           time -p for f in ${files[@]}; do
             SEARCH_PATH="${f}";
@@ -753,22 +736,12 @@ runs:
         fixed=false
         shellcheck_count=1
         repaired=$(sudo find ${{ env.FILE_PATH }} -type f -name 'check-file-repaired.txt' -print -quit);
-        repository=$(sudo find ${GITHUB_WORKSPACE} -type d -name ".git" -print -quit);
-        repair_file='check-file-repaired.txt';
         files=$(sudo find ${{ env.FILE_PATH }} -type f \( -path "*/${{ steps.set_dirname.outputs.dirname }}/*" -o -path "*" \) -name "${{ inputs.filename }}" -print);
         file_type=$(echo ${{ inputs.filename }} | sed 's/.*\.\([^.]*\)$/\1/');
         if [[ -n $(echo "${file_type}" | grep -i "^sh$") ]] && [[ -n ${files} ]]; then
           echo -e "\n####################\nWorkspace Folder: ${{ steps.set_dirname.outputs.dirname }}\n####################\n";
           if ${{ inputs.content }}; then
             echo -e "\n# Found File Path(s)\n${files}\n";
-          fi;
-          if [[ -d ${repository} ]] && ${{ inputs.repair }}; then
-            repository="${repository%/*}/${repair_file}";
-            if [[ -f ${repository} ]]; then
-              echo -e "\n####################\nRepaired files list found!!!\n####################\n";
-            else
-              touch "${repository}";
-            fi;
           fi;
           time -p for f in ${files[@]}; do
             SEARCH_PATH="${f}";
