Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -174,6 +174,7 @@ runs:
         linux_distro2="22.04";
         linux_distro3="20.04";
         linux_verison=$(lsb_release -r | awk '{print $2}');
+        repository=$(sudo find ${GITHUB_WORKSPACE} -type d -name '.git' -print -quit);
         echo 'export GIT_DISCOVERY_ACROSS_FILESYSTEM=1' | sudo tee -a ~/.bashrc >/dev/null;
         echo 'export DEBIAN_FRONTEND=noninteractive' | sudo tee -a ~/.bashrc >/dev/null;
         echo 'deb [trusted=yes] https://apt.gabe565.com /' | sudo tee -a /etc/apt/sources.list.d/gabe565.list >/dev/null;
@@ -212,7 +213,7 @@ runs:
         file_name="${{ inputs.filename }}";
         file_type="${file_name##*.}";
         github=${GITHUB_WORKSPACE};
-        if [[ "${cmake_version}" < "${required_version}" ]] && ${{ inputs.project }}; then
+        if ${{ inputs.project }} && [[ "${cmake_version}" < "${required_version}" ]]; then
           echo -e "CMake version $cmake_version upgrading to latest python cmake\n"
           sudo rm -vf "$(which cmake)";
           sudo mkdir -p '/usr/local/bin'
@@ -221,11 +222,11 @@ runs:
           sudo cp -vpf "/home/runner/.local/bin/cmake" '/usr/local/bin/'
           echo '';
         fi;
-        if [[ ! $(which cmake) ]] && ${{ inputs.project }}; then
+        if ${{ inputs.project }} && [[ ! $(which cmake) ]]; then
           sudo apt-get -yq install cmake 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\ncmake dependencies Installed\n####################" || echo -e '::error::No cmake installed for project build'; 
           [[ ! $(which cmake) ]] && exit 1
         fi;
-        if [[ ! $(apt list linux-headers-generic 2>/dev/null) ]] && ${{ inputs.project }}; then
+        if ${{ inputs.project }} && [[ ! $(apt list linux-headers-generic 2>/dev/null) ]]; then
           sudo apt-get -yq install linux-headers-generic 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\n$(apt list linux-headers-generic 2>/dev/null) - $(uname -r) dependencies Installed\n####################" || echo -e "::error::No linux-headers-generic $(uname -r) installed for project build"; 
           [[ ! $(apt list linux-headers-generic 2>/dev/null) ]] && exit 1
         fi;
@@ -237,21 +238,21 @@ runs:
           sudo apt-get -yq install gcc g++ 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\ngcc g++ dependencies Installed\n####################" || echo -e '::error::No gcc or g++ installed for repo updates';
           [[ ! $(which gcc) ]] || [[ ! $(which g++) ]] && exit 1
         fi;
-        if [[ ! $(which python3) ]] && ${{ inputs.project }} && ${{ inputs.analyzer == '2' }}; then
+        if ${{ inputs.project }} && ${{ inputs.analyzer == '2' }} && [[ ! $(which python3) ]]; then
           sudo apt-get -yq install python3 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\npython3 dependencies Installed\n####################" || echo -e '::error::No python3 installed for project checks';
           [[ ! $(which python3) ]] && exit 1
         fi;
-        if [[ ! $(llvm-config --version 2>/dev/null) ]] && ${{ inputs.project }}; then
+        if ${{ inputs.project }} && [[ ! $(llvm-config --version 2>/dev/null) ]]; then
           sudo bash -c "$(sudo wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - >/dev/null 2>&1)"
           sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs) main" >/dev/null;
           sudo apt-get -yq install lld llvm llvm-dev liblldb-dev libclang-dev 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\nllvm tools dependencies Installed\n####################" || echo -e '::error::No llvm tools installed for project build';
           [[ ! $(llvm-config --version 2>/dev/null) ]] && exit 1
         fi;
-        if [[ ! $(which clang-tidy) ]] && ([[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]] && ${{ inputs.repair }}) || ${{ inputs.project }}; then
+        if ${{ inputs.project }} && ${{ inputs.project }} && ([[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]] && [[ ! $(which clang-tidy) ]]; then
           sudo apt-get install -yq clang-tools clang-tidy 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "${text5}" || echo -e '::error::No clang-tools installed Exiting';
           [[ ! $(which clang-tidy) ]] && exit 1
         fi;
-        if [[ ! $(which clangd-tidy) ]] && ${{ inputs.project }} && ${{ inputs.analyzer == '3' }}; then
+        if ${{ inputs.project }} && ${{ inputs.analyzer == '3' }} && [[ ! $(which clangd-tidy) ]]; then
           python3 -m pip install clangd-tidy >/dev/null && echo -e "\n####################\nclangd-tidy dependencies Installed\n####################\n" || echo -e '::error::No clangd-tidy installed for project checks';
           if [[ $(which clangd-tidy) ]]; then
             echo -e "\nclangd-tidy path: $(which clangd-tidy)\n";
@@ -259,18 +260,18 @@ runs:
             exit 1
           fi;
         fi;
-        if [[ ! $(which clangd) ]] && ${{ inputs.project }}; then
+        if ${{ inputs.project }} && [[ ! $(which clangd) ]]; then
           sudo apt-get -yq install clangd 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\nclangd dependencies Installed\n####################" || echo -e '::error::No clangd installed for project build';
           [[ ! $(which clangd) ]] && exit 1
         fi;
-        if [[ $(whereis -b run-clang-tidy) ]] && ${{ inputs.analyzer == '1' }} && ${{ inputs.project }}; then
+        if ${{ inputs.analyzer == '1' }} && ${{ inputs.project }} && [[ $(whereis -b run-clang-tidy) ]]; then
           echo -e "\nrun-clang-tidy installed in $(whereis -b run-clang-tidy)";
           echo 'run_clang_tidy=run-clang-tidy' >> "${GITHUB_ENV}";
         elif ${{ inputs.analyzer == '1' }} && ${{ inputs.project }}; then
           echo -e '\nrun-clang-tidy not installed using built-in run-clang-tide.py script';
           echo "run_clang_tidy=${{ github.action_path }}/scripts/tools/run-clang-tidy.py" >> "${GITHUB_ENV}";
         fi;
-        if [[ ! $(which CodeChecker) ]] && ${{ inputs.project }} && (${{ inputs.analyzer == '4' }} || ${{ inputs.build > '0' }}); then
+        if ${{ inputs.project }} && (${{ inputs.analyzer == '4' }} || ${{ inputs.build > '0' }}) && [[ ! $(which CodeChecker) ]]; then
           sudo apt-get -yq install python3-pip python3-venv make 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "\n####################\npython3-pip dependencies Installed\n####################" || echo -e '::error::No python3-pip installed for project checks';
           python3 -m pip install codechecker >/dev/null && echo -e "\n####################\ncodechecker dependencies Installed\n####################" || echo -e '::error::No codechecker installed for project checks';
           export PATH="/home/runner/codechecker/build/CodeChecker/bin:${PATH}" | sudo tee -a ~/.bashrc >/dev/null;
@@ -287,48 +288,54 @@ runs:
             exit 1
           fi;
         fi;
-        if [[ ! $(which deheader) ]] && ([[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]] && ${{ inputs.repair }}) || (${{ inputs.project }} && ${{ inputs.build > '2' }}); then
+        if ${{ inputs.repair }}) || (${{ inputs.project }} && ${{ inputs.build > '2' }} && ([[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]]) && [[ ! $(which deheader) ]]; then
           sudo apt-get -yq install deheader 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\ndeheader dependencies Installed\n####################" || echo -e '::error::No deheader installed for project includes check';
           [[ ! $(which deheader) ]] && exit 1
         fi;
-        if [[ ! $(dpkg -s build-essential 2>/dev/null) ]] && ${{ inputs.project }}; then
+        if ${{ inputs.project }} && [[ ! $(dpkg -s build-essential 2>/dev/null) ]]; then
           sudo apt-get -yq install build-essential device-tree-compiler 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\nbuild-essential dependencies Installed\n####################" || echo -e '::error::No build-essential installed for project build';
         fi;
-        if [[ ! $(which tqdm) ]] && ${{ inputs.project }} && ${{ inputs.analyzer == 3 }}; then
+        if ${{ inputs.project }} && ${{ inputs.analyzer == 3 }} && [[ ! $(which tqdm) ]]; then
           python -m pip install tqdm >/dev/null && echo -e "\n####################\ntqdm dependencies Installed\n####################\n" || echo -e '::warning::No tpdm installed for project progress checks';
           [[ ! $(which tqdm) ]] && exit 1
         fi;
-        if [[ ! $(which rg) ]] && [[ "${{ inputs.pattern }}" != '' ]] && ${{ inputs.database }}; then
+        if [[ "${{ inputs.pattern }}" != '' ]] && ${{ inputs.database }} && [[ ! $(which rg) ]]; then
           sudo apt-get -yq install ripgrep 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "${text1}" || echo -e '::error::No ripgrep installed for pattern matching';
           [[ ! $(which rg) ]] && exit 1
         fi;
-        if [[ ! $(which ansi2txt) ]] && ${{ inputs.report }}; then
+        if ${{ inputs.report }} && [[ ! $(which ansi2txt) ]]; then
           sudo apt-get -yq install ansi2txt 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "${text2}" || echo -e '::error::No ansi2txt installed for cleaning log report';
         fi;
-        if [[ ! $(which update-ca-certificates) ]]; then
+        if ${{ inputs.project }} && [[ ! $(which update-ca-certificates) ]]; then
           sudo apt-get -yq install ca-certificates 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "${text3}" || echo 'No ca-certificates installed effects can vary';
         fi;
-        if [[ ! $(which cppcheck) ]] && [[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]]; then
+        if [[ -n $(echo "${file_type}" | egrep "^c$|^c.$|^c..$|^h$|^h.$|^h..$|^t$|^t.$|^t..$") ]] && [[ ! $(which cppcheck) ]]; then
           sudo apt-get -yq install cppcheck 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "${text4}" || echo -e '::error::No cppcheck installed Exiting';
           [[ ! $(which cppcheck) ]] && exit 1
         fi;
-        if [[ ! $(which shellharden) ]] && [[ -n $(echo "${file_type}" | egrep -i "^sh$") ]] && ${{ inputs.repair }}; then
+        if [[ -n $(echo "${file_type}" | egrep -i "^sh$") ]] && ${{ inputs.repair }} && [[ ! $(which shellharden) ]]; then
           sudo wget -qO 'shellharden.tar.gz' 'https://github.com/anordal/shellharden/releases/latest/download/shellharden-x86_64-unknown-linux-gnu.tar.gz' >/dev/null;
           sudo tar xf 'shellharden.tar.gz' -C '/usr/local/bin' 'shellharden' && rm -vrf 'shellharden.tar.gz' && echo -e "${text6}" || echo -e '::error::No shellharden installed Exiting';
           [[ ! $(which shellharden) ]] && exit 1
         fi;
-        if [[ ! $(which shellcheck) ]] && [[ -n $(echo "${file_type}" | egrep -i "^sh$") ]]; then
+        if [[ -n $(echo "${file_type}" | egrep -i "^sh$") ]] && [[ ! $(which shellcheck) ]]; then
           sudo apt-get -yq install shellcheck 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "${text7}" || echo -e '::error::No shellcheck installed Exiting';
           [[ ! $(which shellcheck) ]] && exit 1
         fi;
-        if [[ $(which checkmake) ]] && [[ -n ${file} ]] && [[ -n $(echo "${file_type}" | egrep -i "^mk$|.*Makefile$") ]]; then
-          sudo cp -vf "${file}" "${path}" 2>/dev/null;
-        elif [[ ! -n ${file} ]] && [[ -n $(echo "${file_type}" | egrep -i "^mk$|.*Makefile$") ]]; then
-          echo -e '\ncheckmake.ini file missing, needed for checkmake to function properly\n';
-        fi;
-        if [[ ! $(which checkmake) ]] && [[ -n $(echo "${file_type}" | egrep -i "^mk$|.*Makefile$") ]]; then
-          go install "github.com/checkmake/checkmake/cmd/checkmake@latest" >/dev/null && echo -e "\n${text8}\n" || echo -e '::error::No checkmake installed Exiting';
-          [[ ! $(which checkmake) ]] && exit 1
+        if [[ -d ${repository} ]]; then
+          cd "${repository%/*}";
+          checkmake_src='checkmake.ini';
+          checkmake_des='/usr/PATH/checkmake.ini';
+          if [[ ${checkmake_src} ]] && [[ -n $(echo "${file_type}" | egrep -i "^mk$|.*Makefile$") ]] && [[ $(which checkmake) ]]; then
+            sudo cp -vf "${checkmake_src}" "${checkmake_des}" 2>/dev/null;
+          elif [[ ! -n ${checkmake_src} ]] && [[ -n $(echo "${file_type}" | egrep -i "^mk$|.*Makefile$") ]]; then
+            echo -e '\ncheckmake.ini file missing, needed for checkmake to function properly\n';
+          fi;
+          if [[ ${checkmake_src} ]] && [[ -n $(echo "${file_type}" | egrep -i "^mk$|.*Makefile$") ]] [[ ! $(which checkmake) ]]; then
+            go install "github.com/checkmake/checkmake/cmd/checkmake@latest" >/dev/null && echo -e "\n${text8}\n" || echo -e '::error::No checkmake installed Exiting';
+            sudo cp -vf "${checkmake_src}" "${checkmake_des}" 2>/dev/null;
+            [[ ! $(which checkmake) ]] && exit 1
+          fi;
         fi;
         if ${{ inputs.filename != '' }} || ${{ inputs.pattern != '' }}; then
           if [[ $(which bat) ]] && [[ ! $(which batcat) ]]; then
@@ -343,8 +350,8 @@ runs:
           fi;
         fi;
         echo "update=${{ inputs.update }}" >> "${GITHUB_ENV}";
-        if [[ -d '/home/runner/.local/bin' ]]; then
-          echo "export PATH=/home/runner/.local/bin:${PATH}" | sudo tee -a ~/.bashrc >/dev/null;
+        if [[ -d "${HOME}/.local/bin" ]]; then
+          echo "${HOME}/.local/bin" >> "${GITHUB_PATH}";
         fi;
         echo '';
       shell: bash
@@ -631,18 +638,18 @@ runs:
             done;
           }
           header1_list() {
-            find -not \( -path "*/.github" -prune -o -path "*/.git" -prune \) -type f \( -name "*.h" -o -name "*.hh" -o -name "*.hpp" -o -name "*.h++" \) -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r header; do
-              header="${header#./}"
+            find -not \( -path '*/.github' -prune -o -path '*/.git' -prune \) -type f \( -name '*.h' -o -name '*.hh' -o -name '*.hpp' \) -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r header; do
+   '          header="${header#./}"
               echo "${header%/*}" >> "${header_file1}"
             done;
             if [[ -s "${header_file1}" ]]; then
               awk '!seen[$0]++' "${header_file1}" > "${header_file2}";
-              for headers in $(cat ${header_file2}); do
+              while IFS= read -r headers; do
                 echo -n "${headers%/*} "
-              done;
-              echo 'running header test'
+              done < "${header_file2}";
+              echo 'running/header/test'
             fi;
-            echo -e "$(cat ${header_file2})\n" || echo -e "$(cat ${header_file1})\n"
+            echo -e "test/a/$(cat ${header_file2})\n" || echo -e "test/b/$(cat ${header_file1})\n"
           }
           header2_list() {
             find "${src_tree%/*}" -not \( -path "*/.github" -prune -o -path "*/.git" -prune \) -type d -name 'include' -print | awk '{ print length($0), $0 }' | sort -n | cut -d' ' -f 2- 2>/dev/null | while IFS= read -r include; do
