Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -192,7 +192,7 @@ inputs:
     description: 'Use cmake includes.C.rsp file for including many header paths in compile json file'
     type: boolean 
     required: false
-    default: 'true'
+    default: 'false'
 outputs:
   llvm-path:
     description: The absolute path to the LLVM installation
@@ -1561,7 +1561,7 @@ runs: # Uses default x86_64 / linux user machine
               fi;
             else
               header_source=$(sudo find "${linux_usr_src}" \( -path "*/${{ inputs.dirpath }}/*" -o -path "/*linux-headers-${{ env.release1 }}/*" -o -path "*/linux-headers-${{ env.release2 }}/*" -o -path "*/linux-headers-${{ env.release3 }}/*" \) -xdev -xtype d -name 'include' -print | grep . || sudo find "${linux_usr_src}" -xtype d -name 'include' -print);
-              ${{ inputs.internal == 'true' }} && header_source=$(find "${{ env.base }}" -path "*/${{ inputs.dirpath }}/*" -xtype d \( -name 'uapi' -o -name 'include' \) -print | grep . || fdfind "${abs}" -t d '^(uapi|include)$' "${{ env.base }}");
+              ${{ inputs.internal == 'true' }} && header_source=$(find "${{ env.base }}" -path "*/${{ inputs.dirpath }}/*" -xtype d \( -name 'radix-tree' -o -name 'uapi' -o -name 'include' \) -print | grep . || fdfind -j "$(nproc)" -p "${abs}" -t d '^(radix-tree|uapi|include)$' "${{ env.base }}");
               while IFS= read -r include; do
                 include_count=$((include_count + 1));
                 echo "${include_count}" > "${count1}";
@@ -1782,7 +1782,7 @@ runs: # Uses default x86_64 / linux user machine
           fi;
           if [[ -f "${clangd_tidy}" ]] && ${{ env.analyzer == '3' }} && [[ -e "${compile_json}" ]]; then
             echo -e '\n####################\nCLANGD-TIDY ANALYZING FILES\n####################\n' | process_input;
-            fdfind -p -c auto "${abs}" -e "${{ inputs.filetype }}" "${{ env.base }}" -X clangd-tidy -p build -j "$(nproc --all)" --color always --tqdm 2>&1 | process_input || echo -e "\n::notice::clangd-tidy exit-code ($?)" | process_input;
+            fdfind -j "$(nproc)" -p "${abs}" -e "${{ inputs.filetype }}" "${{ env.base }}" -X clangd-tidy -p build/ -j "$(nproc)" --color always --tqdm 2>&1 | process_input || echo -e "\n::notice::clangd-tidy exit-code ($?)" | process_input;
             if [[ "${PIPESTATUS[0]}" == '1' ]] || [[ -s "${project_log}" ]] && [[ $(grep -aiF 'Process completed with exit code' "${project_log}") ]]; then
               echo 'check_build=false' >> "${GITHUB_ENV}";
             elif [[ -s "${project_log}" ]] && [[ $(grep -aF 'error:' "${project_log}") ]]; then
@@ -2314,9 +2314,9 @@ runs: # Uses default x86_64 / linux user machine
                   clean_path="${include##*./}";
                   clean_file="${include##*/}";
                   if [[ "${include}" == *"/"* && "${clean_path}" != "/" ]]; then
-                    header=$(fdfind "${path}" -p -t f -g "**/${clean_path//./\\.}" "${{ env.base }}");
+                    header=$(fdfind -j "$(nproc)" "${path}" -p -t f -g "**/${clean_path//./\\.}" "${{ env.base }}");
                   elif [[ -n "${clean_file}" ]]; then
-                    header=$(fdfind "${path}" -p -t f -g "**/${clean_file//./\\.}" "${{ env.base }}");
+                    header=$(fdfind -j "$(nproc)" "${path}" -p -t f -g "**/${clean_file//./\\.}" "${{ env.base }}");
                   fi;
                   if [[ -n "${header}" ]]; then
                     while IFS= read -r includes; do
@@ -2335,22 +2335,19 @@ runs: # Uses default x86_64 / linux user machine
                   fi;
                 fi;
               done <<< "${include_source[@]}";
-              echo -e "\n::notice::\033[32mTotal include files found:\033[0m \033[1m${count2}\033[0m" | process_input;
+              echo -e "\n::notice::\033[1m${file##*/}\033[0m \033[32mtotal header files found:\033[0m \033[1m${count2}\033[0m" | process_input;
               [[ ! $(echo "$includes_bases" | grep -sF 'tools/testing/radix-tree ') ]] && include_bases+='-Itools/testing/radix-tree ';
-              if [[ -s 'temp-file' ]]; then
-                echo -e "\ncheck-file: objectives for \033[1m${file##*/}\033[0m -I/\033[36minclude/directory/paths\033[0m/ added!" | process_input;
-              fi;
               if ${{ inputs.repair == 'true' }}; then
                 if ${{ inputs.stored == 'true' }} && ${{ env.update == 'true' }} && [[ $(grep -sF "${search_path}" "${repaired}") ]]; then
                   echo -e "\n####################\n\033[1mCHECK-FILE\033[0m STORED NOTHING TO REPAIR\n####################" | process_input;
                   echo -e "\n####################\nChecked on ${check_date}\nSkipping {file%/*}\n####################" | process_input;
                 elif ${{ inputs.stored == 'true' }} && ${{ env.update == 'true' }}; then
-                  echo -e "\n\n####################\nCLANG-TIDY FIX FILES ANALYZER: ( ${count1} )\n####################\n" | process_input;
+                  echo -e "\n\n####################\nCLANG-TIDY ERRORS REPAIR ANALYZER: ( ${count1} )\n####################\n" | process_input;
                   clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes "${include_bases}" 2>&1 | process_input || error2="$?";
                   if [[ -s "${error_log}" ]] && [[ ! $(grep -sE "${file//./\\.}.*error:" "${error_log}") ]]; then
-                    echo -e "\n####################\n\033[1mCHECK-FILE\033[0m STORING NO ERRORS FOUND: ${file##*/}\n####################" | process_input;
+                    echo -e "\n####################\n\033[1mCHECK-FILE:\033[0m STORING NO ERRORS FOUND: ${file##*/}\n####################" | process_input;
                   else
-                    echo -e "\n####################\n\033[1mCHECK-FILE\033[0m STORING FOUND ERRORS TO REPAIR\n####################" | process_input;
+                    echo -e "\n####################\n\033[1mCHECK-FILE:\033[0m STORING FOUND ERRORS TO REPAIR\n####################" | process_input;
                     errors=true
                   fi;
                   echo "${file} $(date)" >> "${repaired}";
@@ -2367,19 +2364,23 @@ runs: # Uses default x86_64 / linux user machine
                   fixed=true
                 fi;
               else
-                if [[ "${compile_json}" ]]; then
-                  if ${{ inputs.absolute == 'true' }}; then
-                    echo -e "\n####################\nCPPCHECK INCLUDE FILES ANALYZER: ( ${count1} ) \033[2mabsolute path\033[0m\n####################\n" | process_input;
-                    file="${file#/*/*/*/*/*/}";
-                    [[ -s 'temp-file' ]] && sed -E '/\/include\// s|/[^/]+$||' temp-file | sed -E 's|^(/[^/]*){5}/||' | sort -u > "${include_paths}" && cp "${include_paths}" build/
-                    [[ -n $"includes_bases" ]] && includes_bases=$(echo "$includes_bases" | xargs -n1 | sed -E '/\/include\// s|/[^/]+$||' | sed -E 's|^(/[^/]*){5}/||' | awk '!seen[$0]++' | xargs);
-                  else
-                    echo -e "\n####################\nCPPCHECK INCLUDE FILES ANALYZER: ( ${count1} ) \033[2mrelative path\033[0m\n####################\n" | process_input;
-                    file="${file#*./}";
-                    [[ -s 'temp-file' ]] && sed -E '/\/include\// s|/[^/]+$||' temp-file | sort -u > "${include_paths}" && cp "${include_paths}" build/
-                    [[ -n $"includes_bases" ]] && includes_bases=$(echo "$includes_bases" | xargs -n1 | sed -E '/\/include\// s|/[^/]+$||' | awk '!seen[$0]++' | xargs);
-                  fi;
-                  cppcheck -j "$(nproc)" -l 2 --verbose --force --enable="${cppchecks}" --report-progress --showtime=file-total --suppress=checkersReport --cppcheck-build-dir="${build_dir}" --project="${compile_json}" --include="${{ env.kconfig }}" --file-filter="${file}" -Itools/testing/radix-tree 2>&1 | process_input || error="$?";
+                if ${{ inputs.absolute == 'true' }}; then
+                  echo -e "\n####################\nCPPCHECK INCLUDE FILES ANALYZER: ( ${count1} ) \033[2mabsolute path\033[0m\n####################\n" | process_input;
+                  file="${file#/*/*/*/*/*/}";
+                  [[ -s 'temp-file' ]] && sed -E '/\/include\// s|/[^/]+$||' temp-file | sed -E 's|^(/[^/]*){5}/||' | sort -u > "${include_paths}" && cp "${include_paths}" build/
+                  [[ -n $"includes_bases" ]] && includes_bases=$(echo "$includes_bases" | xargs -n1 | sed -E '/\/include\// s|/[^/]+$||' | sed -E 's|^(/[^/]*){5}/||' | awk '!seen[$0]++' | xargs);
+                else
+                  echo -e "\n####################\nCPPCHECK INCLUDE FILES ANALYZER: ( ${count1} ) \033[2mrelative path\033[0m\n####################\n" | process_input;
+                  file="${file#*./}";
+                  [[ -s 'temp-file' ]] && sed -E '/\/include\// s|/[^/]+$||' temp-file | sort -u > "${include_paths}" && cp "${include_paths}" build/
+                  [[ -n $"includes_bases" ]] && includes_bases=$(echo "$includes_bases" | xargs -n1 | sed -E '/\/include\// s|/[^/]+$||' | awk '!seen[$0]++' | xargs);
+                fi;
+                if [[ -s 'temp-file' ]]; then
+                  count=$(gawk 'NF > 0 { count++; } END { print count + 0; }' "${include_paths}")
+                  echo -e "\n\033[1mcheck-file: ${count} include paths for \033[1m${file##*/}\033[0m added!" | process_input;
+                fi;
+                if [[ -e "${compile_json}" ]]; then
+                  cppcheck -j "$(nproc)" -l 2 --verbose --force --enable="${cppchecks}" --report-progress --showtime=file-total --suppress=checkersReport --cppcheck-build-dir="${build_dir}" --project="${compile_json}" --include="${{ env.kconfig }}" --file-filter="${file}" 2>&1 | process_input || error="$?";
                 else
                   cppcheck -j "$(nproc)" -l 2 --verbose --force --enable="${cppchecks}" --report-progress --showtime=file-total --suppress=missingIncludeSystem --suppress=checkersReport --cppcheck-build-dir="${build_dir}" "${file}" --includes-file="${include_paths}" 2>&1 | process_input || error="$?";
                 fi;
