Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -485,7 +485,7 @@ runs:
             echo -e '\n####################\nCLANG-TIDY CONFIG CHECKED\n####################\n';
             if [[ "${files_list}" ]]; then
               echo -e '\n####################\nCLANG-TIDY ANALYZING FILE\n####################\n';
-              { time -p clang-tidy @parameter-file --fix-errors --quiet; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
+              { time -p clang-tidy @parameter-file --fix-errors --quiet 2>/dev/null; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
               echo -e '\n|RUNTIME|\n';
               check_build=true
               echo 'check_build=true' >> "${GITHUB_ENV}";
@@ -499,7 +499,7 @@ runs:
           if [[ $(which run-clang-tidy.py) ]] && ${{ env.analysis == 2 }}; then
             echo -e "\n####################\n\trun-clang-tidy.py found continuing...\n####################\n";
             echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n';
-            { time -p run-clang-tidy.py -p build -config-file="${clang_tidy}" -use-color -quiet -fix -j "$(nproc --all)"; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
+            { time -p run-clang-tidy.py -p build -config-file="${clang_tidy}" -use-color -quiet -fix -j "$(nproc --all)" 2>/dev/null; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
             echo -e '\n|RUNTIME|\n';
             check_build=true
             echo 'check_build=true' >> "${GITHUB_ENV}";
@@ -507,7 +507,7 @@ runs:
             echo -e "\n####################\n\trun-clang-tidy.py found continuing...\n####################\n";
             sudo chmod -v 0755 "${clang_run}" 2>/dev/null;
             echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n';
-            { time -p "${clang_run}" -p build -config-file="${clang_tidy}" -use-color -quiet -fix -j "$(nproc --all)"; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
+            { time -p "${clang_run}" -p build -config-file="${clang_tidy}" -use-color -quiet -fix -j "$(nproc --all)" 2>/dev/null; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
             echo -e '\n|RUNTIME|\n';
             check_build=true
             echo 'check_build=true' >> "${GITHUB_ENV}";
@@ -517,13 +517,12 @@ runs:
           fi;
           if [[ -d 'build' ]] && ${{ env.analysis == 3 }}; then
             echo -e '\n####################\n\tbuild directory created continuing...\n####################\n';
-              cmake -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build || echo "::error:: ( $? ) cmake missing or malformed CMakeList.txt (?)";
-              cmake --build build || echo "::error:: ( $? ) cmake build source corrupted or malformed CMakeList.txt (?)";
-              check_build=true
-              if ${{ inputs.upload }}; then
-                echo 'build_files=1' >> "${GITHUB_ENV}";
-                cp -Rf ./build ${github}/ && echo -e '\n####################\n\tbuild directory copied continuing...\n####################\n';
-              fi;
+            cmake -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build || echo "::error:: ( $? ) cmake missing or malformed CMakeList.txt (?)";
+            cmake --build build || echo "::error:: ( $? ) cmake build source corrupted or malformed CMakeList.txt (?)";
+            check_build=true
+            if ${{ inputs.upload }}; then
+              echo 'build_files=1' >> "${GITHUB_ENV}";
+              cp -Rf ./build ${github}/ && echo -e '\n####################\n\tbuild directory copied continuing...\n####################\n';
             fi;
           elif [[ ! -d 'build' ]] && ${{ env.analysis == 3 }}; then
             echo -e "\n####################\n\t::error:: build directory missing in repo Exiting...\n####################\n";
