Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -464,9 +464,11 @@ runs:
           if [[ -d 'build' ]]; then
             echo -e '\n####################\n\tbuild directory created continuing...\n####################\n' | process_input;
             cmake -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build || echo "::error:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
-            if ${{ inputs.upload }}; then
-              echo 'build_files=1' >> "${GITHUB_ENV}";
-              cp -Rf ./build ${github}/ && echo -e '\n####################\n\tbuild directory copied continuing...\n####################\n' | process_input;
+            if [[ $? -eq 0 ]]; then
+              if ${{ inputs.upload }}; then
+                echo 'build_files=1' >> "${GITHUB_ENV}";
+                cp -Rf ./build ${github}/ && echo -e '\n####################\n\tbuild directory copied continuing...\n####################\n' | process_input;
+              fi;
             fi;
           fi;
           if [[ -e 'compile_commands.json' ]]; then
@@ -487,9 +489,11 @@ runs:
             if [[ "${files_list}" ]]; then
               echo -e '\n####################\nCLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
               { time -p clang-tidy @parameter-file --fix-errors --quiet 2>/dev/null; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files" | process_input;
-              echo -e '\n|RUNTIME|\n' | process_input;
-              check_build=true
-              echo 'check_build=true' >> "${GITHUB_ENV}";
+              if [[ $? -eq 0 ]]; then
+                echo -e '\n|RUNTIME|\n' | process_input;
+                check_build=true
+                echo 'check_build=true' >> "${GITHUB_ENV}";
+              fi;
             else
               exit 1
             fi;
@@ -500,18 +504,22 @@ runs:
           if [[ $(which run-clang-tidy.py) ]] && ${{ env.analysis == 2 }}; then
             echo -e "\n####################\n\trun-clang-tidy.py found continuing...\n####################\n" | process_input;
             echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
-            { time -p run-clang-tidy.py -p build -config-file="${clang_tidy}" -use-color -quiet -fix -j "$(nproc --all)" 2>/dev/null; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
-            echo -e '\n|RUNTIME|\n';
-            check_build=true
-            echo 'check_build=true' >> "${GITHUB_ENV}";
+            { time -p run-clang-tidy.py -p build -config-file="${clang_tidy}" -use-color -quiet -fix-error -j "$(nproc --all)" 2>/dev/null; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
+            if [[ $? -eq 0 ]]; then
+              echo -e '\n|RUNTIME|\n' | process_input;
+              check_build=true
+              echo 'check_build=true' >> "${GITHUB_ENV}";
+            fi;
           elif [[ -e "${clang_run}" ]] && ${{ env.analysis == 2 }}; then
             echo -e "\n####################\n\trun-clang-tidy.py found continuing...\n####################\n" | process_input;
             sudo chmod -v 0755 "${clang_run}" 2>/dev/null;
             echo -e '\n####################\nRUN-CLANG-TIDY ANALYZING FILE\n####################\n' | process_input;
-            { time -p "${clang_run}" -p build -config-file="${clang_tidy}" -use-color -quiet -fix -j "$(nproc --all)" 2>/dev/null; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
-            echo -e '\n|RUNTIME|\n';
-            check_build=true
-            echo 'check_build=true' >> "${GITHUB_ENV}";
+            { time -p "${clang_run}" -p build -config-file="${clang_tidy}" -use-color -quiet -fix-error -j "$(nproc --all)" 2>/dev/null; } 2>&1 | process_input || echo -e "::error:: ( $? ) checking project files";
+            if [[ $? -eq 0 ]]; then
+              echo -e '\n|RUNTIME|\n' | process_input;
+              check_build=true
+              echo 'check_build=true' >> "${GITHUB_ENV}";
+            fi;
           elif [[ ! -e "${clang_run}" ]] && ${{ env.analysis == 2 }}; then
             echo -e "\n####################\n\t::error:: run-clang-tidy.py missing in repo Exiting...\n####################\n" | process_input;
             exit 1
@@ -519,8 +527,12 @@ runs:
           if [[ -d 'build' ]] && ${{ env.analysis == 3 }}; then
             echo -e '\n####################\n\tbuild directory created continuing...\n####################\n';
             cmake -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON build || echo "::error:: ( $? ) cmake missing or malformed CMakeList.txt (?)" | process_input;
-            cmake --build build || echo "::error:: ( $? ) cmake build source corrupted or malformed CMakeList.txt (?)" | process_input;
-            check_build=true
+            { time -p cmake --build build; } 2>&1 || echo "::error:: ( $? ) cmake build source corrupted or malformed CMakeList.txt (?)" | process_input;
+            if [[ $? -eq 0 ]]; then
+              echo -e '\n|RUNTIME|\n' | process_input;
+              check_build=true
+              echo 'check_build=true' >> "${GITHUB_ENV}";
+            fi;
             if ${{ inputs.upload }}; then
               echo 'build_files=1' >> "${GITHUB_ENV}";
               cp -Rf ./build ${github}/ && echo -e '\n####################\n\tbuild directory copied continuing...\n####################\n' | process_input;
