Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -2153,7 +2153,7 @@ runs: # Uses default x86_64 / linux user machine
               --config "${codechecker}" \
               --jobs "$(nproc)" \
               --print-steps \
-              -b "source ${envsetup} && lunch ${{ inputs.makefile }} && $make ${{ env.filename }} -j$(nproc --all) -k" \
+              -b "bash -c 'source ${envsetup} && lunch ${{ inputs.makefile }} && $make ${{ env.filename }} -j$(nproc --all) -k'" \
               2>&1 | process_input || echo -e "\n::notice::CodeChecker check exit-code ($?)" | process_input;
           elif [[ "${envsetup}" ]]; then
             echo -e "\n${codechecker} file was not found continuing without...\n" | process_input;
@@ -2161,7 +2161,7 @@ runs: # Uses default x86_64 / linux user machine
             CodeChecker check \
               --jobs "$(nproc)" \
               --print-steps \
-              -b "source ${envsetup} && lunch ${{ inputs.makefile }} && $make ${{ env.filename }} -j$(nproc) -k" \
+              -b "bash -c 'source ${envsetup} && lunch ${{ inputs.makefile }} && $make ${{ env.filename }} -j$(nproc) -k'" \
               2>&1 | process_input || echo -e "\n::notice::CodeChecker check exit-code ($?)" | process_input;
           else
             echo -e "\n${codechecker} file was not found continuing without...\n" | process_input;
@@ -2172,6 +2172,17 @@ runs: # Uses default x86_64 / linux user machine
               -b "$make ${{ inputs.makefile }} -nB -j$(nproc) -k" \
               2>&1 | process_input || echo -e "\n::notice::CodeChecker check exit-code ($?)" | process_input;
           fi;
+          if [[ "${PIPESTATUS[0]}" == '1' ]] || [[ -s "${project_log}" ]] && [[ $(grep -aiF 'Process completed with exit code' "${project_log}") ]]; then
+            echo 'check_build=false' >> "${GITHUB_ENV}";
+          elif [[ -s "${project_log}" ]] && [[ $(grep -aF 'error:' "${project_log}") ]]; then
+            echo -e "\n::notice::Errors found building project files!" | process_input && echo 'check_build=true' >> "${GITHUB_ENV}" && echo 'build_error=true' >> "${GITHUB_ENV}" && check_build=true;
+          elif [[ -s "${project_log}" ]]; then
+            echo -e "\n::notice::No errors found building project files!" | process_input && echo 'check_build=true' >> "${GITHUB_ENV}" && check_build=true;
+          fi;
+          if ${{ inputs.upload }}; then
+            echo 'build_files=1' >> "${GITHUB_ENV}";     
+          fi;
+          echo "Build test-run completed" | process_input;
         else
           echo '::error::No cmake build files were found. Is (project: true) set?\n Exiting.....' | process_inputs;
         fi;
