Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1952,82 +1952,53 @@ runs:
               batcat --theme=ansi --paging=never --show-all --color=always --style=full "{file}";
             fi;
             if ${{ inputs.include }}; then
-              IFS=$'\n';
-              includes=$(find $(dirname ${file}) -name $(basename ${file}) -exec sed -n 's/^#include <\(.*\)>/\1/p; s/^#include "\(.*\)"/\1/p' "{}" \;);
-              include1='include_file1.txt';
-              include2='include_file2.txt';
-              if [[ ${includes} ]]; then
-                echo -e "\n# Found Include File(s):\n${includes}\n" | process_input;
-                echo > "${include1}";
-                for i in ${includes[@]}; do
-                  final="${i}";
-                  count2=$((include_count++));
-                  count3=$((include_total++));
-                  header=$(find . -type f \( -path "*/$(dirname ${i})/*" -o -path "*/$(dirname ${file})/*" -o -path "*/*/*" \) -name "$(basename ${i})" -print -quit);
-                  if [[ -f "${header}" ]]; then
-                    echo "$(dirname ${header#./})" >> "${include1}";
-                  else
-                    echo -e "\n::notice:: include source file ${i} is missing\n" | process_input;
+              if ${{ inputs.repair }}; then
+                if ${{ inputs.stored }} && ${{ env.update }} && [[ $(LC_ALL=C grep -sF "${search_path}" "${repaired}") ]]; then
+                  echo -e "\n####################\nSTORED NOTHING TO REPAIR\n####################\n" | process_input;
+                  echo -e "\n####################\nChecked on ${check_date}\nSkipping $(basename ${file})\n####################\n" | process_input;
+                elif ${{ inputs.stored }} && ${{ env.update }}; then
+                  echo -e "\n\n####################\nGCC/G++ FILES ANALYZER (${count1})\n####################\n\n" | process_input;
+                  if [[ "${file_type}" == [c] ]]; then
+                    gcc -M -MG "${file}" | process_input || echo -e "::error:: ( $? ) gcc" | process_input;
+                  elif [[ "${file_type}" == [c]* ]]; then
+                    g++ -M -MG "${file}" | process_input || echo -e "::error:: ( $? ) g++" | process_input;
                   fi;
-                done;
-                IFS=${SAVEIFS};
-                if [[ -f "${include1}" ]]; then
-                  awk '!seen[$0]++' "${include1}" > "${include2}";
-                fi;
-                if [[ -f "${include2}" ]]; then
-                  if ${{ inputs.repair }}; then
-                    if ${{ inputs.stored }} && ${{ env.update }} && [[ $(LC_ALL=C grep -sF "${search_path}" "${repaired}") ]]; then
-                      echo -e "\n####################\nSTORED NOTHING TO REPAIR\n####################\n" | process_input;
-                      echo -e "\n####################\nChecked on ${check_date}\nSkipping $(basename ${file})\n####################\n" | process_input;
-                    elif ${{ inputs.stored }} && ${{ env.update }}; then
-                      echo -e "\n\n####################\nGCC/G++ FILES ANALYZER (${count1})\n####################\n\n" | process_input;
-                      if [[ "${file_type}" == [c] ]]; then
-                        gcc -MM -MP "${file}" | process_input || echo -e "::error:: ( $? ) & broken pipe" | process_input;
-                      elif [[ "${file_type}" == [c]* ]]; then
-                        g++ -MM -MP "${file}" | process_input || echo -e "::error:: ( $? ) & broken pipe" | process_input;
-                      fi;
-                      echo -e "\n\n####################\nCLANG-TIDY FIX FILES ANALYZER (${count1})\n####################\n\n" | process_input;
-                      clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes -- -I"include/" | process_input || echo -e "::error:: ( $? )" | process_input;
-                      if [[ -s "${error_log}" ]] && [[ ! $(LC_ALL=C grep -sE "${file}.*error:" "${error_log}") ]]; then
-                        echo -e "\n####################\nSTORING NO ERRORS FOUND\n####################\n\n${file}\n" | process_input;
-                      else
-                        echo -e "\n####################\nSTORING FOUND ERROR(S) TO REPAIR\n####################\n" | process_input;
-                        errors=true
-                      fi;
-                      echo "${file} $(date)" >> "${repaired}";
-                      fixed=true
-                    elif ! ${{ inputs.stored }} || ! ${{ env.update }}; then
-                      echo -e "\n\n####################\nCLANG-TIDY FILES ANALYZER (${count1})\n####################\n\n" | process_input;
-                      if [[ $(echo "${file_type}" | LC_ALL=C egrep "^c$|^cc$") ]]; then
-                        gcc -MM "${file}" | process_input || echo -e "::error:: ( $? ) & broken pipe" | process_input;
-                      elif [[ $(echo "${file_type}" | LC_ALL=C egrep "^c..$") ]]; then
-                        g++ -MM "${file}" | process_input || echo -e "::error:: ( $? ) & broken pipe" | process_input;
-                      fi;
-                      clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes -- -I"include/" 2>/dev/null | process_input || echo -e "::error:: ( $? )" | process_input;
-                      if [[ -s "${error_log}" ]] && [[ ! $(LC_ALL=C grep -sE "${file}.*error:" "${error_log}") ]]; then
-                        echo -e "\n####################\nCHECK-FILE NO ERRORS FOUND ${file}\n####################\n" | process_input;
-                      else
-                        echo -e "\n####################\nCHECK-FILE FOUND ERROR(S) TO REPAIR\n####################\n" | process_input;
-                        errors=true
-                      fi;
-                      fixed=true
-                    fi;
+                  echo -e "\n\n####################\nCLANG-TIDY FIX FILES ANALYZER (${count1})\n####################\n\n" | process_input;
+                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>&1 | process_input || echo -e "::warning:: ( $? ) clang-tidy" | process_input;
+                  if [[ -s "${error_log}" ]] && [[ ! $(LC_ALL=C grep -sE "${file}.*error:" "${error_log}") ]]; then
+                    echo -e "\n####################\nSTORING NO ERRORS FOUND\n####################\n\n${file}\n" | process_input;
                   else
-                    echo -e "\n####################\nCPPCHECK INCLUDE FILE(S) ANALYZER (${count2})\n####################\n\nFinal File: ${final}\n\n" | process_input;
-                    cppcheck --verbose --force --enable="${cppchecks}" --report-progress --suppress=* --suppress=checkersReport --includes-file="${include2}" "${file}" 2>/dev/null | process_input || echo -e "::error:: ( $? )" | process_input;
-                    if [[ -s "${error_log}" ]] && [[ ! $(LC_ALL=C grep -sE "${file}.*error:" "${error_log}") ]]; then
-                      echo -e "\n####################\nCHECK-FILE NO ERRORS FOUND ${file}\n####################\n" | process_input;
-                    else
-                      echo -e "\n####################\nCHECK-FILE FOUND ERROR(S)\n####################\n" | process_input;
-                      errors=true
-                    fi;
+                    echo -e "\n####################\nSTORING FOUND ERROR(S) TO REPAIR\n####################\n" | process_input;
+                    errors=true
                   fi;
+                  echo "${file} $(date)" >> "${repaired}";
+                  fixed=true
+                elif ! ${{ inputs.stored }} || ! ${{ env.update }}; then
+                  echo -e "\n\n####################\nCLANG-TIDY FILES ANALYZER (${count1})\n####################\n\n" | process_input;
+                  if [[ "${file_type}" == [c] ]]; then
+                    gcc -MM "${file}" | process_input || echo -e "::warning:: ( $? ) gcc" | process_input;
+                  elif [[ "${file_type}" == [c]* ]]; then
+                    g++ -MM "${file}" | process_input || echo -e "::warning:: ( $? ) g++" | process_input;
+                  fi;
+                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>&1 | process_input || echo -e "::warning:: ( $? ) clang-tidy" | process_input;
+                  if [[ -s "${error_log}" ]] && [[ ! $(LC_ALL=C grep -sE "${file}.*error:" "${error_log}") ]]; then
+                    echo -e "\n####################\nCHECK-FILE NO ERRORS FOUND ${file}\n####################\n" | process_input;
+                  else
+                    echo -e "\n####################\nCHECK-FILE FOUND ERROR(S) TO REPAIR\n####################\n" | process_input;
+                    errors=true
+                  fi;
+                  fixed=true
                 fi;
               else
-                echo -e "\n\n####################\nINCLUDE FILE(S) FOR $(basename ${file}) NOT PRESENT\n####################\n\n" | process_input;
+                echo -e "\n####################\nCPPCHECK INCLUDE FILE(S) ANALYZER (${count2})\n####################\n\nFinal File: ${final}\n\n" | process_input;
+                cppcheck --verbose --force --enable="${cppchecks}" --report-progress --suppress=* --suppress=checkersReport --includes-file="${include2}" "${file}" 2>&1 | process_input || echo -e "::warning:: ( $? ) cppcheck" | process_input;
+                if [[ -s "${error_log}" ]] && [[ ! $(LC_ALL=C grep -sE "${file}.*error:" "${error_log}") ]]; then
+                  echo -e "\n####################\nCHECK-FILE NO ERRORS FOUND ${file}\n####################\n" | process_input;
+                else
+                  echo -e "\n####################\nCHECK-FILE FOUND ERROR(S)\n####################\n" | process_input;
+                  errors=true
+                fi;
               fi;
-              echo -e "\n::notice:: Number of $(basename ${file}) include file(s): ${count2}\n" | process_input;
-              include_count=1
             else
               if ${{ inputs.repair }}; then
                 if ${{ inputs.stored }} && ${{ env.update }} && [[ $(LC_ALL=C grep -sF "${search_path}" "${repaired}") ]]; then
@@ -2035,7 +2006,7 @@ runs:
                   echo -e "\n####################\nChecked on ${check_date}\nSkipping $(basename ${file})\n####################\n" | process_input;
                 elif ${{ inputs.stored }} && ${{ env.update }}; then
                   echo -e "\n\n####################\nCLANG-TIDY FILES ANALYZER (${count1})\n####################\n\n" | process_input;
-                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>/dev/null | process_input || echo -e "::error:: ( $? )" | process_input;
+                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>&1 | process_input || echo -e "::warning:: ( $? )" | process_input;
                   if [[ -s "${error_log}" ]] && [[ ! $(LC_ALL=C grep -sE "${file}.*error:" "${error_log}") ]]; then
                     echo -e "\n####################\nSTORING NO ERRORS FOUND\n####################\n\n${file}\n" | process_input;
                   else
@@ -2046,7 +2017,7 @@ runs:
                   fixed=true
                 elif ${{ inputs.stored == 'false' }} || ${{ env.update == 'false' }}; then
                   echo -e "\n\n####################\nCLANG-TIDY FILES ANALYZER (${count1})\n####################\n\n" | process_input;
-                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>/dev/null | process_input || echo -e "::error:: ( $? )" | process_input;
+                  clang-tidy "${file}" --config-file="${clang_file}" --fix-errors --fix-notes 2>&1 | process_input || echo -e "::warning:: ( $? )" | process_input;
                   if [[ -s "${error_log}" ]] && [[ ! $(LC_ALL=C grep -sE "${file}.*error:" "${error_log}") ]]; then
                     echo -e "\n####################\nCHECK-FILE NO ERRORS FOUND ${file}\n####################\n" | process_input;
                   else
@@ -2058,12 +2029,12 @@ runs:
               else
                 echo -e "\n\n####################\nCPPCHECK FILE ANALYZER (${count1})\n####################\n\n" | process_input;
                 if ${{ inputs.project }} && ${{ inputs.stored }}; then
-                  cppcheck -j "$(nproc --all)" --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress=missingInclude --suppress=missingIncludeSystem --suppress=unmatchedSuppression:"{}" --cppcheck-build-dir="${build_cache}" --project="${compile_json}" "${file}" 2>/dev/null | process_input || echo -e "::error:: ( $? )" | process_input;
+                  cppcheck -j "$(nproc --all)" --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress=missingInclude --suppress=missingIncludeSystem --suppress=unmatchedSuppression:"{}" --cppcheck-build-dir="${build_cache}" --project="${compile_json}" "${file}" 2>&1 | process_input || echo -e "::warning:: ( $? ) cppcheck" | process_input;
                   echo 'build_cache=true' >> "${GITHUB_ENV}";
                 elif ${{ inputs.project }}; then
-                  cppcheck --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress=missingInclude --suppress=missingIncludeSystem --suppress=unmatchedSuppression:"{}" --project="${compile_json}" "${file}" 2>/dev/null | process_input || echo -e "::error:: ( $? )" | process_input;
+                  cppcheck --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress=missingInclude --suppress=missingIncludeSystem --suppress=unmatchedSuppression:"{}" --project="${compile_json}" "${file}" 2>&1 | process_input || echo -e "::warning:: ( $? ) cppcheck" | process_input;
                 else
-                  cppcheck --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress="*" "${file}" 2>/dev/null | process_input || echo -e "::error:: ( $? )" | process_input;
+                  cppcheck --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress="*" "${file}" 2>&1 | process_input || echo -e "::warning:: ( $? ) cppcheck" | process_input;
                 fi;
                 if [[ -s "${error_log}" ]] && [[ ! $(LC_ALL=C grep -sE "${file}.*error:" "${error_log}") ]]; then
                   echo -e "\n####################\nCHECK-FILE NO ERRORS FOUND ${file}\n####################\n" | process_input;
@@ -2075,7 +2046,7 @@ runs:
             fi;
             if ${{ inputs.recheck }} && ${{ inputs.repair }}; then
               echo -e "\n\n####################\nCPPCHECK RE-ANALYZING FILE(S) (${count1})\n####################\n\n" | process_input;
-              cppcheck -j "$(nproc --all)" --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress=* --quiet "${file}" 2>/dev/null | process_input || echo -e "::error:: ( $? )" | process_input;
+              cppcheck -j "$(nproc --all)" --verbose --force --enable="${cppchecks}" --report-progress --suppress=checkersReport --suppress=* --quiet "${file}" 2>&1 | process_input || echo -e "::warning:: ( $? ) cppcheck" | process_input;
               if [[ -s "${error_log}" ]] && [[ ! $(LC_ALL=C grep -sE "${file}.*error:" "${error_log}") ]]; then
                 echo -e "\n####################\nRECHECK-FILE NO ERRORS FOUND ${file}\n####################\n" | process_input;
               else
@@ -2090,9 +2061,6 @@ runs:
               fi;
             fi;
           done; echo '| Runtime |'; } 2>&1
-          if ${{ inputs.include }}; then
-            echo -e "\n::notice:: Total number of include file(s) was: ${count3}\n" | process_input;
-          fi;
           echo -e "\n::notice:: Total number of ${{ inputs.filename }} file(s) checked is: ${count1}\n" | process_input;
           echo -e "Scanning Completed!\nCheck-File Exiting!\n .....\n" | process_input;
           echo "file_found=1" >> "${GITHUB_ENV}";
