Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -304,14 +304,15 @@ runs:
         cmake_version=$(cmake --version | grep version | awk '{ print $3; }');
         clang_version=$(clang --version | awk '{ print $4; }');
         clang_tidy_version=$(clang-tidy --version | grep version | awk '{ print $3; }');
-        required_version="4.2.1";
+        clang_tidy_required_version='21.1.6';
+        cmake_required_version="4.2.1";
         linux_distro1="24.04";
         linux_distro2="22.04";
         linux_distro3="20.04";
         linux_verison=$(lsb_release -r | awk '{ print $2; }');
         if ${{ inputs.project }}; then
-          if [[ "${cmake_version}" < "${required_version}" ]] && ${{ inputs.project }}; then
-            echo -e "Current CMake version (${cmake_version}) is older than ${required_version}. Updating....";
+          if [[ "${cmake_version}" < "${cmake_required_version}" ]] && ${{ inputs.project }}; then
+            echo -e "Current CMake version (${cmake_version}) is older than ${cmake_required_version}. Updating....";
             sudo apt-get remove --purge -yq cmake 2>&1 >/dev/null | sed '/Running/,/host./d'
             sudo aptitude install -yq ca-certificates gpg wget 2>&1 >/dev/null | sed '/Running/,/host./d'
             [[ ! $(which make) ]] && sudo apt-get install -yq make >/dev/null && echo -e "####################\nmake dependencies already installed\n####################\n";
@@ -352,7 +353,7 @@ runs:
           sudo aptitude -yq install gawk 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\ngawk dependencies installed\n####################" || echo -e "\n::error::No gawk installed in linux exiting";
         fi;
         echo 'deb [trusted=yes] https://apt.gabe565.com /' | sudo tee -a /etc/apt/sources.list.d/gabe565.list >/dev/null;
-        if ${{ inputs.project }} && [[ "${cmake_version}" < "${required_version}" ]]; then
+        if ${{ inputs.project }} && [[ $(printf '%s\n%s' "$cmake_version" "$cmake_required_version" | sort -x | head -n1) == "$cmake_version" ]] && [[ "$cmake_version" != "$cmake_required_version" ]]; then
           python3 -m pip install --upgrade pip >/dev/null && echo -e "\n####################\npip dependencies installed\n####################" || echo -e '::warning::pip not updated for project checks';
           echo -e "\nCMake version $cmake_version upgrading to latest python cmake";
           sudo rm -f "$(which cmake)";
@@ -369,8 +370,8 @@ runs:
           sudo aptitude -yq install git git-core 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "${text0}" || echo -e '::error::No git installed for repo updates';
           [[ ! $(which git) ]] && exit 1
         fi;
-        if (${{ inputs.project }} || [[ "${file_type}" == [cth]* ]]) && ([[ ! $(which clang-tidy) ]] || [[ "${clang_tidy_version}" < '21.1.5' ]]); then
-          python3 -m pip install --upgrade clang-tools >/dev/null && echo -e "\n####################\nclang tools pip dependencies installed\n####################\n" || echo -e '::error::No clang tools installed for project check'; # Adjust directory as needed
+        if (${{ inputs.project }} || [[ "${file_type}" == [cth]* ]]) && ([[ ! $(which clang-tidy) ]] || [[ $(printf '%s\n%s' "$clang_tidy_version" "$clang_tidy_required_version" | sort -x | head -n1) == "$clang_tidy_version" ]] && [[ "$clang_tidy_version" != "$clang_tidy_required_version" ]]); then
+          python3 -m pip install --upgrade clang-tools >/dev/null && echo -e "\n####################\nclang tools pip dependencies installed\n####################\n" || echo -e '::error::No clang tools installed for project check';
           [[ ! -e '/usr/bin/clang-tidy' ]] && [[ -e "${HOME}/.local/bin/clang-tidy" ]] && sudo mv -vf "${HOME}/.local/bin/clang-tidy" '/usr/bin/clang-tidy'
           [[ -e "${HOME}/.local/bin/run-clang-tidy" ]] && sudo mv -vf "${HOME}/.local/bin/run-clang-tidy" '/usr/bin/run-clang-tidy'
           [[ ! $(which clang-tidy) ]] && exit 1
