Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -297,8 +297,9 @@ runs:
           sudo aptitude -yq install cmake make 2>&1 >/dev/null | sed '/Running/,/host./d' && echo -e "####################\ncmake dependencies installed\n####################" || echo -e '::error::No cmake installed for project build';        
           [[ ! $(which cmake) ]] && exit 1
         fi;
-        cmake_version=$(cmake --version 2>/dev/null | grep version | awk '{ print $3; }');
+        cmake_version=$(cmake --version | grep version | awk '{ print $3; }');
         clang_version=$(clang --version | awk '{ print $4; }');
+        clang_tidy_version=$(clang-tidy --version | grep version | awk '{ print $3; }');
         required_version="4.2.1";
         linux_distro1="24.04";
         linux_distro2="22.04";
@@ -364,8 +365,8 @@ runs:
           sudo aptitude -yq install git git-core 2>&1 >/dev/null | sed -E '/Running/,/host./d' && echo -e "${text0}" || echo -e '::error::No git installed for repo updates';
           [[ ! $(which git) ]] && exit 1
         fi;
-        if (${{ inputs.project }} || [[ "${file_type}" == [cth]* ]]) && ([[ "${clang_version}" < '20.0' ]] || [[ ! $(which clang-tidy) ]]); then
-          python3 -m pip install --upgrade clang-tools >/dev/null && clang-tools --install latest --directory /usr/bin >/dev/null && echo -e "\n####################\nclang tools pip dependencies installed\n####################\n" || echo -e '::error::No clang tools installed for project check'; # Adjust directory as needed
+        if (${{ inputs.project }} || [[ "${file_type}" == [cth]* ]]) && ([[ ! $(which clang-tidy) ]] || [[ "${clang_version}" < '21.1.6' ]] || [[ "${clang_tidy_version}" < '21.1.6' ]]); then
+          python3 -m pip install --upgrade clang-tools >/dev/null && echo -e "\n####################\nclang tools pip dependencies installed\n####################\n" || echo -e '::error::No clang tools installed for project check'; # Adjust directory as needed
           [[ ! -e '/usr/bin/clang-tidy' ]] && [[ -e "${HOME}/.local/bin/clang-tidy" ]] && sudo mv -vf "${HOME}/.local/bin/clang-tidy" '/usr/bin/clang-tidy'
           [[ -e "${HOME}/.local/bin/run-clang-tidy" ]] && sudo mv -vf "${HOME}/.local/bin/run-clang-tidy" '/usr/bin/run-clang-tidy'
           [[ ! $(which clang-tidy) ]] && exit 1
@@ -1070,9 +1071,8 @@ runs:
         fixed=false;
         if ${{ inputs.repository == 'false' }} && ${{ env.dirname != '' }}; then
           cd "${{ env.dirname }}";
-          cmakelist=$(find "${github}" -type f -name 'CMakeLists.txt' -print -quit);
+          cmakelist="${{ github.action_path }}/CMakeLists.txt";
           [[ ! -f 'CMakeLists.txt' ]] && cp -v "${cmakelist}" . 2>/dev/null;
-          [[ ! -f 'CMakeLists.txt' ]] && cp -v "${{ github.action_path }}/CMakeLists.txt" . 2>/dev/null;
           echo '';
         fi;
         process_input() {
@@ -1544,14 +1544,14 @@ runs:
               --config "${codechecker}" \
               --jobs "$(nproc)" \
               --print-steps \
-              -b "bash -c 'source ${envsetup} && lunch ${{ inputs.makefile }} && make ${{ inputs.filename }} -j$(nproc --all) -O2 -k'" \
+              -b "bash -c 'source ${envsetup} && lunch ${{ inputs.makefile }} && make ${{ inputs.filename }} -j$(nproc --all) -k'" \
               2>&1 | process_input || echo -e "\n::notice::CodeChecker check exit-code ($?)" | process_input;
           elif [[ "${envsetup}" ]]; then
             echo -e "\n${codechecker} file was not found continuing without...\n" | process_input;
             CodeChecker check \
               --jobs "$(nproc)" \
               --print-steps \
-              -b "bash -c 'source ${envsetup} && lunch ${{ inputs.makefile }} && make ${{ inputs.filename }} -j$(nproc) -O2 -k'" \
+              -b "bash -c 'source ${envsetup} && lunch ${{ inputs.makefile }} && make ${{ inputs.filename }} -j$(nproc) -k'" \
               2>&1 | process_input || echo -e "\n::notice::CodeChecker check exit-code ($?)" | process_input;
           else
             echo -e "\n${codechecker} file was not found continuing without...\n" | process_input;
@@ -1618,7 +1618,7 @@ runs:
           echo -e '\n####################\n\tDeheader analyze & repair sources includes on build...(test-run -4)\n####################\n' | process_input;
           sudo bash -c 'source ~/.bashrc'
           [[ "${envsetup}" ]] && echo -e "Sources: ${envsetup}\n" || echo '::error::No envsetup.sh file to source for lunch mode exiting';
-          deheader -v -r -m "bash -c 'source ${envsetup} && lunch ${{ inputs.makefile }} && make ${{ inputs.filename }} -j$(nproc) -O3 -k'" 2>&1 | process_input || echo -e "\n::notice::deheader build exit-code ($?)" | process_input;
+          deheader -v -r -m "bash -c 'source ${envsetup} && lunch ${{ inputs.makefile }} && make ${{ inputs.filename }} -j$(nproc) -k'" 2>&1 | process_input || echo -e "\n::notice::deheader build exit-code ($?)" | process_input;
           if [[ "${PIPESTATUS[0]}" == '1' ]] || [[ -s "${project_log}" ]] && [[ $(grep -siF 'Process completed with exit code' "${project_log}") ]]; then
             echo 'check_build=false' >> "${GITHUB_ENV}";
           elif [[ -s "${project_log}" ]] && [[ $(grep -sE ' duplicates|inclusion' "${project_log}") ]]; then
